// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearBillingAPIKey = `-- name: ClearBillingAPIKey :exec
UPDATE claude_billing
SET api_key_enc = NULL, api_key_hint = '', bot_uses_api_key = false, updated_at = now()
WHERE id = 1
`

// Sem chave o bot não tem como usá-la: apagar também desliga a troca.
func (q *Queries) ClearBillingAPIKey(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearBillingAPIKey)
	return err
}

const getBilling = `-- name: GetBilling :one
SELECT bot_uses_api_key, api_key_enc, api_key_hint, updated_at FROM claude_billing WHERE id = 1
`

type GetBillingRow struct {
	BotUsesApiKey bool
	ApiKeyEnc     []byte
	ApiKeyHint    string
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetBilling(ctx context.Context) (GetBillingRow, error) {
	row := q.db.QueryRow(ctx, getBilling)
	var i GetBillingRow
	err := row.Scan(
		&i.BotUsesApiKey,
		&i.ApiKeyEnc,
		&i.ApiKeyHint,
		&i.UpdatedAt,
	)
	return i, err
}

const saveBillingAPIKey = `-- name: SaveBillingAPIKey :exec
UPDATE claude_billing
SET api_key_enc = $1, api_key_hint = $2, updated_at = now()
WHERE id = 1
`

type SaveBillingAPIKeyParams struct {
	ApiKeyEnc  []byte
	ApiKeyHint string
}

func (q *Queries) SaveBillingAPIKey(ctx context.Context, arg SaveBillingAPIKeyParams) error {
	_, err := q.db.Exec(ctx, saveBillingAPIKey, arg.ApiKeyEnc, arg.ApiKeyHint)
	return err
}

const setBotUsesAPIKey = `-- name: SetBotUsesAPIKey :execrows
UPDATE claude_billing
SET bot_uses_api_key = $1::boolean, updated_at = now()
WHERE id = 1 AND (NOT $1::boolean OR api_key_enc IS NOT NULL)
`

// Ligar exige chave gravada (checado no mesmo UPDATE, sem corrida com o DELETE):
// 0 linhas afetadas = tentou ligar sem chave.
func (q *Queries) SetBotUsesAPIKey(ctx context.Context, enabled bool) (int64, error) {
	result, err := q.db.Exec(ctx, setBotUsesAPIKey, enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
