// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConversation = `-- name: DeleteConversation :execrows
DELETE FROM claude_conversations
WHERE id = $1::uuid AND user_id = $2
`

type DeleteConversationParams struct {
	Column1 pgtype.UUID
	UserID  int64
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConversation, arg.Column1, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConversation = `-- name: GetConversation :one
SELECT id::text, user_id, title, repo, workdir, model, status, session_id::text, session_started, tools_disabled, effort, web_search, created_at, updated_at
FROM claude_conversations
WHERE id = $1::uuid AND user_id = $2
`

type GetConversationParams struct {
	Column1 pgtype.UUID
	UserID  int64
}

type GetConversationRow struct {
	ID             string
	UserID         int64
	Title          *string
	Repo           *string
	Workdir        string
	Model          string
	Status         string
	SessionID      string
	SessionStarted bool
	ToolsDisabled  bool
	Effort         string
	WebSearch      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (GetConversationRow, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.Column1, arg.UserID)
	var i GetConversationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Repo,
		&i.Workdir,
		&i.Model,
		&i.Status,
		&i.SessionID,
		&i.SessionStarted,
		&i.ToolsDisabled,
		&i.Effort,
		&i.WebSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConversation = `-- name: InsertConversation :exec
INSERT INTO claude_conversations (id, user_id, title, repo, workdir, model, status, session_id, session_started, tools_disabled, effort, web_search)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertConversationParams struct {
	ID             pgtype.UUID
	UserID         int64
	Title          *string
	Repo           *string
	Workdir        string
	Model          string
	Status         string
	SessionID      pgtype.UUID
	SessionStarted bool
	ToolsDisabled  bool
	Effort         string
	WebSearch      bool
}

func (q *Queries) InsertConversation(ctx context.Context, arg InsertConversationParams) error {
	_, err := q.db.Exec(ctx, insertConversation,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Repo,
		arg.Workdir,
		arg.Model,
		arg.Status,
		arg.SessionID,
		arg.SessionStarted,
		arg.ToolsDisabled,
		arg.Effort,
		arg.WebSearch,
	)
	return err
}

const listConversations = `-- name: ListConversations :many
SELECT id::text, user_id, title, repo, workdir, model, status, session_id::text, session_started, tools_disabled, effort, web_search, created_at, updated_at
FROM claude_conversations
WHERE user_id = $1
ORDER BY updated_at DESC
`

type ListConversationsRow struct {
	ID             string
	UserID         int64
	Title          *string
	Repo           *string
	Workdir        string
	Model          string
	Status         string
	SessionID      string
	SessionStarted bool
	ToolsDisabled  bool
	Effort         string
	WebSearch      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListConversations(ctx context.Context, userID int64) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Repo,
			&i.Workdir,
			&i.Model,
			&i.Status,
			&i.SessionID,
			&i.SessionStarted,
			&i.ToolsDisabled,
			&i.Effort,
			&i.WebSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionStarted = `-- name: MarkSessionStarted :exec
UPDATE claude_conversations
SET session_started = true, updated_at = now()
WHERE id = $1::uuid
`

func (q *Queries) MarkSessionStarted(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markSessionStarted, dollar_1)
	return err
}

const rotateSession = `-- name: RotateSession :exec
UPDATE claude_conversations
SET session_id = $1::uuid, session_started = false, updated_at = now()
WHERE id = $2::uuid AND user_id = $3
`

type RotateSessionParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
	UserID  int64
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) error {
	_, err := q.db.Exec(ctx, rotateSession, arg.Column1, arg.Column2, arg.UserID)
	return err
}

const setConversationStatus = `-- name: SetConversationStatus :exec
UPDATE claude_conversations
SET status = $1, updated_at = now()
WHERE id = $2::uuid
`

type SetConversationStatusParams struct {
	Status  string
	Column2 pgtype.UUID
}

func (q *Queries) SetConversationStatus(ctx context.Context, arg SetConversationStatusParams) error {
	_, err := q.db.Exec(ctx, setConversationStatus, arg.Status, arg.Column2)
	return err
}

const setTitleIfEmpty = `-- name: SetTitleIfEmpty :exec
UPDATE claude_conversations
SET title = $1, updated_at = now()
WHERE id = $2::uuid AND (title IS NULL OR title = '')
`

type SetTitleIfEmptyParams struct {
	Title   *string
	Column2 pgtype.UUID
}

func (q *Queries) SetTitleIfEmpty(ctx context.Context, arg SetTitleIfEmptyParams) error {
	_, err := q.db.Exec(ctx, setTitleIfEmpty, arg.Title, arg.Column2)
	return err
}

const updateConversationModel = `-- name: UpdateConversationModel :exec
UPDATE claude_conversations
SET model = $1, updated_at = now()
WHERE id = $2::uuid AND user_id = $3
`

type UpdateConversationModelParams struct {
	Model   string
	Column2 pgtype.UUID
	UserID  int64
}

func (q *Queries) UpdateConversationModel(ctx context.Context, arg UpdateConversationModelParams) error {
	_, err := q.db.Exec(ctx, updateConversationModel, arg.Model, arg.Column2, arg.UserID)
	return err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :exec
UPDATE claude_conversations
SET title = $1, updated_at = now()
WHERE id = $2::uuid AND user_id = $3
`

type UpdateConversationTitleParams struct {
	Title   *string
	Column2 pgtype.UUID
	UserID  int64
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error {
	_, err := q.db.Exec(ctx, updateConversationTitle, arg.Title, arg.Column2, arg.UserID)
	return err
}
