// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package db

import (
	"context"
)

const clearOAuthToken = `-- name: ClearOAuthToken :exec
UPDATE claude_credentials
SET oauth_token_enc = NULL, status = 'logged_out', updated_at = now()
WHERE id = 1
`

func (q *Queries) ClearOAuthToken(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearOAuthToken)
	return err
}

const getOAuthStatus = `-- name: GetOAuthStatus :one
SELECT status FROM claude_credentials WHERE id = 1
`

func (q *Queries) GetOAuthStatus(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getOAuthStatus)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT oauth_token_enc FROM claude_credentials WHERE id = 1
`

func (q *Queries) GetOAuthToken(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOAuthToken)
	var oauth_token_enc []byte
	err := row.Scan(&oauth_token_enc)
	return oauth_token_enc, err
}

const saveOAuthToken = `-- name: SaveOAuthToken :exec
UPDATE claude_credentials
SET oauth_token_enc = $1, status = 'logged_in', updated_at = now()
WHERE id = 1
`

func (q *Queries) SaveOAuthToken(ctx context.Context, oauthTokenEnc []byte) error {
	_, err := q.db.Exec(ctx, saveOAuthToken, oauthTokenEnc)
	return err
}
