// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: design_shares.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveDesignShare = `-- name: GetActiveDesignShare :one
SELECT token, created_at
FROM claude_design_shares
WHERE conversation_id = $1::uuid AND revoked_at IS NULL
LIMIT 1
`

type GetActiveDesignShareRow struct {
	Token     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetActiveDesignShare(ctx context.Context, dollar_1 pgtype.UUID) (GetActiveDesignShareRow, error) {
	row := q.db.QueryRow(ctx, getActiveDesignShare, dollar_1)
	var i GetActiveDesignShareRow
	err := row.Scan(&i.Token, &i.CreatedAt)
	return i, err
}

const getSharedDesignWorkdir = `-- name: GetSharedDesignWorkdir :one
SELECT c.workdir
FROM claude_design_shares s
JOIN claude_conversations c ON c.id = s.conversation_id
WHERE s.token = $1 AND s.revoked_at IS NULL AND c.kind = 'design'
`

func (q *Queries) GetSharedDesignWorkdir(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRow(ctx, getSharedDesignWorkdir, token)
	var workdir string
	err := row.Scan(&workdir)
	return workdir, err
}

const insertDesignShare = `-- name: InsertDesignShare :exec
INSERT INTO claude_design_shares (token, conversation_id, created_by)
VALUES ($1, $2::uuid, $3)
`

type InsertDesignShareParams struct {
	Token     string
	Column2   pgtype.UUID
	CreatedBy int64
}

func (q *Queries) InsertDesignShare(ctx context.Context, arg InsertDesignShareParams) error {
	_, err := q.db.Exec(ctx, insertDesignShare, arg.Token, arg.Column2, arg.CreatedBy)
	return err
}

const revokeDesignShares = `-- name: RevokeDesignShares :execrows
UPDATE claude_design_shares
SET revoked_at = now()
WHERE conversation_id = $1::uuid AND revoked_at IS NULL
`

func (q *Queries) RevokeDesignShares(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDesignShares, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
