// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO claude_messages (conversation_id, role, kind, content, usage)
VALUES ($1::uuid, $2, $3, $4, $5)
`

type InsertMessageParams struct {
	Column1 pgtype.UUID
	Role    string
	Kind    string
	Content []byte
	Usage   []byte
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.Column1,
		arg.Role,
		arg.Kind,
		arg.Content,
		arg.Usage,
	)
	return err
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id::text, role, kind, content, usage, created_at
FROM claude_messages
WHERE conversation_id = $1::uuid
ORDER BY id
`

type ListMessagesRow struct {
	ID             int64
	ConversationID string
	Role           string
	Kind           string
	Content        []byte
	Usage          []byte
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ListMessages(ctx context.Context, dollar_1 pgtype.UUID) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Kind,
			&i.Content,
			&i.Usage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
