// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: misc.sql

package db

import (
	"context"
)

const userIDByAPIKeyHash = `-- name: UserIDByAPIKeyHash :one
UPDATE api_keys
SET last_used_at = now()
WHERE key_hash = $1 AND (expires_at IS NULL OR expires_at > now())
RETURNING user_id
`

func (q *Queries) UserIDByAPIKeyHash(ctx context.Context, keyHash string) (int32, error) {
	row := q.db.QueryRow(ctx, userIDByAPIKeyHash, keyHash)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const userRole = `-- name: UserRole :one
SELECT role FROM users WHERE id = $1
`

func (q *Queries) UserRole(ctx context.Context, id int64) (int16, error) {
	row := q.db.QueryRow(ctx, userRole, id)
	var role int16
	err := row.Scan(&role)
	return role, err
}
