// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         int64
	UserID     int32
	Name       string
	KeyPrefix  string
	KeyHash    string
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type ClaudeConversation struct {
	ID             pgtype.UUID
	UserID         int64
	Title          *string
	Repo           *string
	Workdir        string
	Model          string
	Status         string
	SessionID      pgtype.UUID
	SessionStarted bool
	ToolsDisabled  bool
	Effort         string
	WebSearch      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ClaudeCredential struct {
	ID            int32
	OauthTokenEnc []byte
	Status        string
	UpdatedAt     pgtype.Timestamptz
}

type ClaudeMessage struct {
	ID             int64
	ConversationID pgtype.UUID
	Role           string
	Kind           string
	Content        []byte
	Usage          []byte
	CreatedAt      pgtype.Timestamptz
}

type ClaudePushToken struct {
	Token     string
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID   int64
	Role int16
}
