// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package db

import (
	"context"
)

const pushTokensForUser = `-- name: PushTokensForUser :many
SELECT token FROM claude_push_tokens WHERE user_id = $1
`

func (q *Queries) PushTokensForUser(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, pushTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePushToken = `-- name: SavePushToken :exec
INSERT INTO claude_push_tokens (token, user_id)
VALUES ($1, $2)
ON CONFLICT (token) DO UPDATE SET user_id = $2
`

type SavePushTokenParams struct {
	Token  string
	UserID int64
}

func (q *Queries) SavePushToken(ctx context.Context, arg SavePushTokenParams) error {
	_, err := q.db.Exec(ctx, savePushToken, arg.Token, arg.UserID)
	return err
}
