// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUsageEvent = `-- name: InsertUsageEvent :exec
INSERT INTO claude_usage_events (
  source, task, model, conversation_id,
  total_cost_usd, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens,
  duration_ms, is_error
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8, $9,
  $10, $11
)
`

type InsertUsageEventParams struct {
	Source           string
	Task             string
	Model            string
	ConversationID   pgtype.UUID
	TotalCostUsd     float64
	InputTokens      int64
	OutputTokens     int64
	CacheReadTokens  int64
	CacheWriteTokens int64
	DurationMs       int64
	IsError          bool
}

func (q *Queries) InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) error {
	_, err := q.db.Exec(ctx, insertUsageEvent,
		arg.Source,
		arg.Task,
		arg.Model,
		arg.ConversationID,
		arg.TotalCostUsd,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.DurationMs,
		arg.IsError,
	)
	return err
}

const usageBySource = `-- name: UsageBySource :many
SELECT
  source,
  COALESCE(SUM(total_cost_usd), 0)::float8 AS cost_usd,
  COUNT(*)::bigint AS calls
FROM claude_usage_events
WHERE created_at >= $1
GROUP BY source
ORDER BY cost_usd DESC
`

type UsageBySourceRow struct {
	Source  string
	CostUsd float64
	Calls   int64
}

func (q *Queries) UsageBySource(ctx context.Context, createdAt pgtype.Timestamptz) ([]UsageBySourceRow, error) {
	rows, err := q.db.Query(ctx, usageBySource, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageBySourceRow
	for rows.Next() {
		var i UsageBySourceRow
		if err := rows.Scan(&i.Source, &i.CostUsd, &i.Calls); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageDaily = `-- name: UsageDaily :many
SELECT
  date_trunc('day', created_at)::date AS day,
  COALESCE(SUM(total_cost_usd), 0)::float8 AS cost_usd,
  COUNT(*)::bigint AS calls
FROM claude_usage_events
WHERE created_at >= $1
GROUP BY day
ORDER BY day
`

type UsageDailyRow struct {
	Day     pgtype.Date
	CostUsd float64
	Calls   int64
}

func (q *Queries) UsageDaily(ctx context.Context, createdAt pgtype.Timestamptz) ([]UsageDailyRow, error) {
	rows, err := q.db.Query(ctx, usageDaily, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageDailyRow
	for rows.Next() {
		var i UsageDailyRow
		if err := rows.Scan(&i.Day, &i.CostUsd, &i.Calls); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageSummary = `-- name: UsageSummary :one
SELECT
  COALESCE(SUM(total_cost_usd), 0)::float8 AS total_cost_usd,
  COUNT(*)::bigint AS calls
FROM claude_usage_events
WHERE created_at >= $1
`

type UsageSummaryRow struct {
	TotalCostUsd float64
	Calls        int64
}

func (q *Queries) UsageSummary(ctx context.Context, createdAt pgtype.Timestamptz) (UsageSummaryRow, error) {
	row := q.db.QueryRow(ctx, usageSummary, createdAt)
	var i UsageSummaryRow
	err := row.Scan(&i.TotalCostUsd, &i.Calls)
	return i, err
}
