// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const pendingBookingGet = `-- name: PendingBookingGet :one
SELECT conversation_id, client_phone, client_name,
       COALESCE(student_name, '')    AS student_name,
       kind, course,
       proposed_day,
       COALESCE(proposed_date, '')   AS proposed_date,
       proposed_time, proposed_period,
       COALESCE(age, 0)              AS age,
       notes, status,
       COALESCE(channel, 'whatsapp') AS channel,
       created_at
FROM pending_booking
WHERE tenant_id = $1 AND id = $2 AND status = 'open'
`

type PendingBookingGetParams struct {
	TenantID string
	ID       string
}

type PendingBookingGetRow struct {
	ConversationID string
	ClientPhone    string
	ClientName     string
	StudentName    string
	Kind           string
	Course         string
	ProposedDay    string
	ProposedDate   string
	ProposedTime   string
	ProposedPeriod string
	Age            int
	Notes          string
	Status         string
	Channel        string
	CreatedAt      time.Time
}

func (q *Queries) PendingBookingGet(ctx context.Context, arg PendingBookingGetParams) (PendingBookingGetRow, error) {
	row := q.db.QueryRowContext(ctx, pendingBookingGet, arg.TenantID, arg.ID)
	var i PendingBookingGetRow
	err := row.Scan(
		&i.ConversationID,
		&i.ClientPhone,
		&i.ClientName,
		&i.StudentName,
		&i.Kind,
		&i.Course,
		&i.ProposedDay,
		&i.ProposedDate,
		&i.ProposedTime,
		&i.ProposedPeriod,
		&i.Age,
		&i.Notes,
		&i.Status,
		&i.Channel,
		&i.CreatedAt,
	)
	return i, err
}

const pendingBookingInsert = `-- name: PendingBookingInsert :exec
INSERT INTO pending_booking
  (tenant_id, conversation_id, client_phone, client_name, student_name, kind, course,
   proposed_day, proposed_date, proposed_time, proposed_period, age, notes, channel, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, 'open')
`

type PendingBookingInsertParams struct {
	TenantID       string
	ConversationID string
	ClientPhone    string
	ClientName     string
	StudentName    string
	Kind           string
	Course         string
	ProposedDay    string
	ProposedDate   string
	ProposedTime   string
	ProposedPeriod string
	Age            sql.NullInt32
	Notes          string
	Channel        string
}

func (q *Queries) PendingBookingInsert(ctx context.Context, arg PendingBookingInsertParams) error {
	_, err := q.db.ExecContext(ctx, pendingBookingInsert,
		arg.TenantID,
		arg.ConversationID,
		arg.ClientPhone,
		arg.ClientName,
		arg.StudentName,
		arg.Kind,
		arg.Course,
		arg.ProposedDay,
		arg.ProposedDate,
		arg.ProposedTime,
		arg.ProposedPeriod,
		arg.Age,
		arg.Notes,
		arg.Channel,
	)
	return err
}

const pendingBookingListOpen = `-- name: PendingBookingListOpen :many
SELECT id, conversation_id, client_phone, client_name,
       COALESCE(student_name, '')    AS student_name,
       kind, course,
       proposed_day,
       COALESCE(proposed_date, '')   AS proposed_date,
       proposed_time, proposed_period,
       COALESCE(age, 0)              AS age,
       notes, status,
       COALESCE(channel, 'whatsapp') AS channel,
       created_at
FROM pending_booking
WHERE tenant_id = $1 AND status = 'open'
ORDER BY created_at
`

type PendingBookingListOpenRow struct {
	ID             string
	ConversationID string
	ClientPhone    string
	ClientName     string
	StudentName    string
	Kind           string
	Course         string
	ProposedDay    string
	ProposedDate   string
	ProposedTime   string
	ProposedPeriod string
	Age            int
	Notes          string
	Status         string
	Channel        string
	CreatedAt      time.Time
}

func (q *Queries) PendingBookingListOpen(ctx context.Context, tenantID string) ([]PendingBookingListOpenRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingBookingListOpen, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingBookingListOpenRow
	for rows.Next() {
		var i PendingBookingListOpenRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.ClientPhone,
			&i.ClientName,
			&i.StudentName,
			&i.Kind,
			&i.Course,
			&i.ProposedDay,
			&i.ProposedDate,
			&i.ProposedTime,
			&i.ProposedPeriod,
			&i.Age,
			&i.Notes,
			&i.Status,
			&i.Channel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingBookingMarkStatus = `-- name: PendingBookingMarkStatus :exec
UPDATE pending_booking SET status = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
`

type PendingBookingMarkStatusParams struct {
	TenantID string
	ID       string
	Status   string
}

func (q *Queries) PendingBookingMarkStatus(ctx context.Context, arg PendingBookingMarkStatusParams) error {
	_, err := q.db.ExecContext(ctx, pendingBookingMarkStatus, arg.TenantID, arg.ID, arg.Status)
	return err
}

const pendingBookingUpdateProposed = `-- name: PendingBookingUpdateProposed :exec
UPDATE pending_booking
SET proposed_date = $3,
    proposed_time = $4,
    proposed_day  = '',
    updated_at    = now()
WHERE tenant_id = $1 AND id = $2
`

type PendingBookingUpdateProposedParams struct {
	TenantID     string
	ID           string
	ProposedDate string
	ProposedTime string
}

func (q *Queries) PendingBookingUpdateProposed(ctx context.Context, arg PendingBookingUpdateProposedParams) error {
	_, err := q.db.ExecContext(ctx, pendingBookingUpdateProposed,
		arg.TenantID,
		arg.ID,
		arg.ProposedDate,
		arg.ProposedTime,
	)
	return err
}

const pendingQuestionGet = `-- name: PendingQuestionGet :one
SELECT conversation_id, client_phone, client_name,
       question, status,
       COALESCE(draft, '')           AS draft,
       COALESCE(channel, 'whatsapp') AS channel,
       created_at
FROM pending_question
WHERE tenant_id = $1 AND id = $2 AND status IN ('open', 'drafted')
`

type PendingQuestionGetParams struct {
	TenantID string
	ID       string
}

type PendingQuestionGetRow struct {
	ConversationID string
	ClientPhone    string
	ClientName     string
	Question       string
	Status         string
	Draft          string
	Channel        string
	CreatedAt      time.Time
}

func (q *Queries) PendingQuestionGet(ctx context.Context, arg PendingQuestionGetParams) (PendingQuestionGetRow, error) {
	row := q.db.QueryRowContext(ctx, pendingQuestionGet, arg.TenantID, arg.ID)
	var i PendingQuestionGetRow
	err := row.Scan(
		&i.ConversationID,
		&i.ClientPhone,
		&i.ClientName,
		&i.Question,
		&i.Status,
		&i.Draft,
		&i.Channel,
		&i.CreatedAt,
	)
	return i, err
}

const pendingQuestionInsert = `-- name: PendingQuestionInsert :exec
INSERT INTO pending_question
  (tenant_id, conversation_id, client_phone, client_name, question, channel, status)
SELECT $1, $2, $3, $4, $5, $6, 'open'
WHERE NOT EXISTS (
    SELECT 1 FROM pending_question
    WHERE tenant_id = $1
      AND conversation_id = $2
      AND status IN ('open', 'drafted')
)
`

type PendingQuestionInsertParams struct {
	TenantID       string
	ConversationID string
	ClientPhone    string
	ClientName     string
	Question       string
	Channel        string
}

func (q *Queries) PendingQuestionInsert(ctx context.Context, arg PendingQuestionInsertParams) error {
	_, err := q.db.ExecContext(ctx, pendingQuestionInsert,
		arg.TenantID,
		arg.ConversationID,
		arg.ClientPhone,
		arg.ClientName,
		arg.Question,
		arg.Channel,
	)
	return err
}

const pendingQuestionListOpen = `-- name: PendingQuestionListOpen :many
SELECT id, conversation_id, client_phone, client_name,
       question, status,
       COALESCE(draft, '')                    AS draft,
       COALESCE(channel, 'whatsapp')          AS channel,
       created_at
FROM pending_question
WHERE tenant_id = $1 AND status IN ('open', 'drafted')
ORDER BY created_at
`

type PendingQuestionListOpenRow struct {
	ID             string
	ConversationID string
	ClientPhone    string
	ClientName     string
	Question       string
	Status         string
	Draft          string
	Channel        string
	CreatedAt      time.Time
}

func (q *Queries) PendingQuestionListOpen(ctx context.Context, tenantID string) ([]PendingQuestionListOpenRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingQuestionListOpen, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingQuestionListOpenRow
	for rows.Next() {
		var i PendingQuestionListOpenRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.ClientPhone,
			&i.ClientName,
			&i.Question,
			&i.Status,
			&i.Draft,
			&i.Channel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingQuestionMarkResolved = `-- name: PendingQuestionMarkResolved :exec
UPDATE pending_question SET status = 'resolved', updated_at = now()
WHERE tenant_id = $1 AND id = $2
`

type PendingQuestionMarkResolvedParams struct {
	TenantID string
	ID       string
}

func (q *Queries) PendingQuestionMarkResolved(ctx context.Context, arg PendingQuestionMarkResolvedParams) error {
	_, err := q.db.ExecContext(ctx, pendingQuestionMarkResolved, arg.TenantID, arg.ID)
	return err
}

const pendingQuestionStoreDraft = `-- name: PendingQuestionStoreDraft :exec
UPDATE pending_question
SET draft      = $3,
    status     = 'drafted',
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND status IN ('open', 'drafted')
`

type PendingQuestionStoreDraftParams struct {
	TenantID string
	ID       string
	Draft    sql.NullString
}

func (q *Queries) PendingQuestionStoreDraft(ctx context.Context, arg PendingQuestionStoreDraftParams) error {
	_, err := q.db.ExecContext(ctx, pendingQuestionStoreDraft, arg.TenantID, arg.ID, arg.Draft)
	return err
}
