// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package db

import (
	"context"
	"encoding/json"
)

const tenantConfigAppendKB = `-- name: TenantConfigAppendKB :exec
UPDATE tenant_config
SET kb_content = COALESCE(kb_content, '[]'::jsonb) || $2::jsonb
WHERE tenant_id = $1
`

type TenantConfigAppendKBParams struct {
	TenantID string
	Column2  json.RawMessage
}

func (q *Queries) TenantConfigAppendKB(ctx context.Context, arg TenantConfigAppendKBParams) error {
	_, err := q.db.ExecContext(ctx, tenantConfigAppendKB, arg.TenantID, arg.Column2)
	return err
}

const tenantConfigGet = `-- name: TenantConfigGet :one
SELECT tc.bot_name,
       tc.bot_gender,
       false                          AS reveal_ai_if_asked,
       tc.kb_content::text            AS kb_content,
       tc.system_prompt,
       tc.admin_system_prompt,
       t.timezone,
       tc.quiet_hours->>'start'       AS quiet_hours_start,
       tc.quiet_hours->>'end'         AS quiet_hours_end,
       tc.bot_enabled_by_default,
       tc.bot_allowed_numbers,
       tc.admin_whatsapp_number,
       tc.admin_whatsapp_numbers
FROM tenant_config tc
JOIN tenants t ON t.id = tc.tenant_id
WHERE tc.tenant_id = $1
`

type TenantConfigGetRow struct {
	BotName              string
	BotGender            string
	RevealAiIfAsked      bool
	KbContent            string
	SystemPrompt         string
	AdminSystemPrompt    string
	Timezone             string
	QuietHoursStart      interface{}
	QuietHoursEnd        interface{}
	BotEnabledByDefault  bool
	BotAllowedNumbers    json.RawMessage
	AdminWhatsappNumber  string
	AdminWhatsappNumbers json.RawMessage
}

func (q *Queries) TenantConfigGet(ctx context.Context, tenantID string) (TenantConfigGetRow, error) {
	row := q.db.QueryRowContext(ctx, tenantConfigGet, tenantID)
	var i TenantConfigGetRow
	err := row.Scan(
		&i.BotName,
		&i.BotGender,
		&i.RevealAiIfAsked,
		&i.KbContent,
		&i.SystemPrompt,
		&i.AdminSystemPrompt,
		&i.Timezone,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.BotEnabledByDefault,
		&i.BotAllowedNumbers,
		&i.AdminWhatsappNumber,
		&i.AdminWhatsappNumbers,
	)
	return i, err
}

const tenantConfigGetAdmins = `-- name: TenantConfigGetAdmins :one
SELECT admin_whatsapp_number, admin_whatsapp_numbers FROM tenant_config WHERE tenant_id = $1
`

type TenantConfigGetAdminsRow struct {
	AdminWhatsappNumber  string
	AdminWhatsappNumbers json.RawMessage
}

func (q *Queries) TenantConfigGetAdmins(ctx context.Context, tenantID string) (TenantConfigGetAdminsRow, error) {
	row := q.db.QueryRowContext(ctx, tenantConfigGetAdmins, tenantID)
	var i TenantConfigGetAdminsRow
	err := row.Scan(&i.AdminWhatsappNumber, &i.AdminWhatsappNumbers)
	return i, err
}

const tenantConfigGetBotNameGender = `-- name: TenantConfigGetBotNameGender :one
SELECT bot_name, bot_gender FROM tenant_config WHERE tenant_id = $1
`

type TenantConfigGetBotNameGenderRow struct {
	BotName   string
	BotGender string
}

func (q *Queries) TenantConfigGetBotNameGender(ctx context.Context, tenantID string) (TenantConfigGetBotNameGenderRow, error) {
	row := q.db.QueryRowContext(ctx, tenantConfigGetBotNameGender, tenantID)
	var i TenantConfigGetBotNameGenderRow
	err := row.Scan(&i.BotName, &i.BotGender)
	return i, err
}

const tenantConfigGetBotReplyEnabled = `-- name: TenantConfigGetBotReplyEnabled :one
SELECT evolution_bot_reply_enabled FROM tenant_config WHERE tenant_id = $1
`

func (q *Queries) TenantConfigGetBotReplyEnabled(ctx context.Context, tenantID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, tenantConfigGetBotReplyEnabled, tenantID)
	var evolution_bot_reply_enabled bool
	err := row.Scan(&evolution_bot_reply_enabled)
	return evolution_bot_reply_enabled, err
}

const tenantConfigGetCaptureDisabled = `-- name: TenantConfigGetCaptureDisabled :one
SELECT evolution_capture_disabled FROM tenant_config WHERE tenant_id = $1
`

func (q *Queries) TenantConfigGetCaptureDisabled(ctx context.Context, tenantID string) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, tenantConfigGetCaptureDisabled, tenantID)
	var evolution_capture_disabled json.RawMessage
	err := row.Scan(&evolution_capture_disabled)
	return evolution_capture_disabled, err
}

const tenantConfigGetDebounce = `-- name: TenantConfigGetDebounce :one
SELECT debounce_ms FROM tenant_config WHERE tenant_id = $1
`

func (q *Queries) TenantConfigGetDebounce(ctx context.Context, tenantID string) (int, error) {
	row := q.db.QueryRowContext(ctx, tenantConfigGetDebounce, tenantID)
	var debounce_ms int
	err := row.Scan(&debounce_ms)
	return debounce_ms, err
}

const tenantConfigGetFull = `-- name: TenantConfigGetFull :one
SELECT tc.bot_name,
       tc.bot_gender,
       tc.bot_enabled_by_default,
       tc.bot_allowed_numbers,
       tc.quiet_hours->>'start'           AS quiet_hours_start,
       tc.quiet_hours->>'end'             AS quiet_hours_end,
       tc.kb_content::text                AS kb_content,
       tc.system_prompt,
       tc.admin_system_prompt,
       tc.admin_whatsapp_numbers,
       tc.debounce_ms,
       tc.evolution_bot_reply_enabled,
       tc.evolution_lead_capture_enabled,
       tc.evolution_capture_disabled,
       tc.notif_phone,
       tc.notif_instance,
       tc.notif_enabled,
       tc.notif_on_success,
       tc.notif_on_container_down
FROM tenant_config tc
WHERE tc.tenant_id = $1
`

type TenantConfigGetFullRow struct {
	BotName                     string
	BotGender                   string
	BotEnabledByDefault         bool
	BotAllowedNumbers           json.RawMessage
	QuietHoursStart             interface{}
	QuietHoursEnd               interface{}
	KbContent                   string
	SystemPrompt                string
	AdminSystemPrompt           string
	AdminWhatsappNumbers        json.RawMessage
	DebounceMs                  int
	EvolutionBotReplyEnabled    bool
	EvolutionLeadCaptureEnabled bool
	EvolutionCaptureDisabled    json.RawMessage
	NotifPhone                  string
	NotifInstance               string
	NotifEnabled                bool
	NotifOnSuccess              bool
	NotifOnContainerDown        bool
}

func (q *Queries) TenantConfigGetFull(ctx context.Context, tenantID string) (TenantConfigGetFullRow, error) {
	row := q.db.QueryRowContext(ctx, tenantConfigGetFull, tenantID)
	var i TenantConfigGetFullRow
	err := row.Scan(
		&i.BotName,
		&i.BotGender,
		&i.BotEnabledByDefault,
		&i.BotAllowedNumbers,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.KbContent,
		&i.SystemPrompt,
		&i.AdminSystemPrompt,
		&i.AdminWhatsappNumbers,
		&i.DebounceMs,
		&i.EvolutionBotReplyEnabled,
		&i.EvolutionLeadCaptureEnabled,
		&i.EvolutionCaptureDisabled,
		&i.NotifPhone,
		&i.NotifInstance,
		&i.NotifEnabled,
		&i.NotifOnSuccess,
		&i.NotifOnContainerDown,
	)
	return i, err
}

const tenantConfigGetNotif = `-- name: TenantConfigGetNotif :one
SELECT notif_phone, notif_instance, notif_enabled, notif_on_success, notif_on_container_down
FROM tenant_config WHERE tenant_id = $1
`

type TenantConfigGetNotifRow struct {
	NotifPhone           string
	NotifInstance        string
	NotifEnabled         bool
	NotifOnSuccess       bool
	NotifOnContainerDown bool
}

func (q *Queries) TenantConfigGetNotif(ctx context.Context, tenantID string) (TenantConfigGetNotifRow, error) {
	row := q.db.QueryRowContext(ctx, tenantConfigGetNotif, tenantID)
	var i TenantConfigGetNotifRow
	err := row.Scan(
		&i.NotifPhone,
		&i.NotifInstance,
		&i.NotifEnabled,
		&i.NotifOnSuccess,
		&i.NotifOnContainerDown,
	)
	return i, err
}

const tenantConfigPatch = `-- name: TenantConfigPatch :exec
UPDATE tenant_config
SET bot_name                        = $1,
    bot_gender                      = $2,
    bot_enabled_by_default          = $3,
    bot_allowed_numbers             = $4::jsonb,
    quiet_hours                     = CASE WHEN $5::text IS NULL THEN '{}'::jsonb ELSE $5::jsonb END,
    kb_content                      = $6::jsonb,
    system_prompt                   = $8,
    admin_whatsapp_number           = $9,
    admin_whatsapp_numbers          = $10::jsonb,
    debounce_ms                     = $11,
    admin_system_prompt             = $12,
    evolution_bot_reply_enabled     = $13,
    evolution_lead_capture_enabled  = $14,
    evolution_capture_disabled      = $15::jsonb,
    notif_phone                     = $16,
    notif_instance                  = $17,
    notif_enabled                   = $18,
    notif_on_success                = $19,
    notif_on_container_down         = $20
WHERE tenant_id = $7
`

type TenantConfigPatchParams struct {
	BotName                     string
	BotGender                   string
	BotEnabledByDefault         bool
	Column4                     json.RawMessage
	Column5                     string
	Column6                     json.RawMessage
	TenantID                    string
	SystemPrompt                string
	AdminWhatsappNumber         string
	Column10                    json.RawMessage
	DebounceMs                  int
	AdminSystemPrompt           string
	EvolutionBotReplyEnabled    bool
	EvolutionLeadCaptureEnabled bool
	Column15                    json.RawMessage
	NotifPhone                  string
	NotifInstance               string
	NotifEnabled                bool
	NotifOnSuccess              bool
	NotifOnContainerDown        bool
}

func (q *Queries) TenantConfigPatch(ctx context.Context, arg TenantConfigPatchParams) error {
	_, err := q.db.ExecContext(ctx, tenantConfigPatch,
		arg.BotName,
		arg.BotGender,
		arg.BotEnabledByDefault,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.TenantID,
		arg.SystemPrompt,
		arg.AdminWhatsappNumber,
		arg.Column10,
		arg.DebounceMs,
		arg.AdminSystemPrompt,
		arg.EvolutionBotReplyEnabled,
		arg.EvolutionLeadCaptureEnabled,
		arg.Column15,
		arg.NotifPhone,
		arg.NotifInstance,
		arg.NotifEnabled,
		arg.NotifOnSuccess,
		arg.NotifOnContainerDown,
	)
	return err
}
