// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const channelIdentityFindFirst = `-- name: ChannelIdentityFindFirst :one
SELECT id, tenant_id, contact_id, channel::text AS channel, external_id, created_at
FROM channel_identity
WHERE tenant_id = $1 AND contact_id = $2
ORDER BY created_at ASC
LIMIT 1
`

type ChannelIdentityFindFirstParams struct {
	TenantID  string
	ContactID string
}

type ChannelIdentityFindFirstRow struct {
	ID         string
	TenantID   string
	ContactID  string
	Channel    string
	ExternalID string
	CreatedAt  time.Time
}

func (q *Queries) ChannelIdentityFindFirst(ctx context.Context, arg ChannelIdentityFindFirstParams) (ChannelIdentityFindFirstRow, error) {
	row := q.db.QueryRowContext(ctx, channelIdentityFindFirst, arg.TenantID, arg.ContactID)
	var i ChannelIdentityFindFirstRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContactID,
		&i.Channel,
		&i.ExternalID,
		&i.CreatedAt,
	)
	return i, err
}

const channelIdentityUpsert = `-- name: ChannelIdentityUpsert :one
INSERT INTO channel_identity (tenant_id, contact_id, channel, external_id, display_handle)
VALUES ($1, $2, $3::channel, $4, $5)
ON CONFLICT (tenant_id, channel, external_id) DO UPDATE
    SET display_handle = EXCLUDED.display_handle
RETURNING id, tenant_id, contact_id, channel::text AS channel, external_id, created_at
`

type ChannelIdentityUpsertParams struct {
	TenantID      string
	ContactID     string
	Column3       Channel
	ExternalID    string
	DisplayHandle sql.NullString
}

type ChannelIdentityUpsertRow struct {
	ID         string
	TenantID   string
	ContactID  string
	Channel    string
	ExternalID string
	CreatedAt  time.Time
}

func (q *Queries) ChannelIdentityUpsert(ctx context.Context, arg ChannelIdentityUpsertParams) (ChannelIdentityUpsertRow, error) {
	row := q.db.QueryRowContext(ctx, channelIdentityUpsert,
		arg.TenantID,
		arg.ContactID,
		arg.Column3,
		arg.ExternalID,
		arg.DisplayHandle,
	)
	var i ChannelIdentityUpsertRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContactID,
		&i.Channel,
		&i.ExternalID,
		&i.CreatedAt,
	)
	return i, err
}

const contactFindByChannelIdentity = `-- name: ContactFindByChannelIdentity :one
SELECT c.id, c.tenant_id, c.display_name, c.communication_style, c.created_at, c.updated_at,
       ci.id AS ci_id, ci.tenant_id AS ci_tenant_id, ci.contact_id AS ci_contact_id,
       ci.channel::text AS ci_channel, ci.external_id AS ci_external_id, ci.created_at AS ci_created_at
FROM contact c
JOIN channel_identity ci ON ci.contact_id = c.id AND ci.tenant_id = c.tenant_id
WHERE ci.channel = $1::channel
  AND ci.external_id = $2
`

type ContactFindByChannelIdentityParams struct {
	Column1    Channel
	ExternalID string
}

type ContactFindByChannelIdentityRow struct {
	ID                 string
	TenantID           string
	DisplayName        sql.NullString
	CommunicationStyle sql.NullString
	CreatedAt          time.Time
	UpdatedAt          time.Time
	CiID               string
	CiTenantID         string
	CiContactID        string
	CiChannel          string
	CiExternalID       string
	CiCreatedAt        time.Time
}

func (q *Queries) ContactFindByChannelIdentity(ctx context.Context, arg ContactFindByChannelIdentityParams) (ContactFindByChannelIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, contactFindByChannelIdentity, arg.Column1, arg.ExternalID)
	var i ContactFindByChannelIdentityRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.CommunicationStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CiID,
		&i.CiTenantID,
		&i.CiContactID,
		&i.CiChannel,
		&i.CiExternalID,
		&i.CiCreatedAt,
	)
	return i, err
}

const contactFindByPhone = `-- name: ContactFindByPhone :one
SELECT c.id, c.tenant_id, c.display_name, c.communication_style, c.created_at, c.updated_at
FROM contact c
JOIN channel_identity ci ON ci.contact_id = c.id AND ci.tenant_id = c.tenant_id
WHERE c.tenant_id = $1
  AND regexp_replace(ci.external_id, '\D', '', 'g') = $2
ORDER BY c.created_at ASC
LIMIT 1
`

type ContactFindByPhoneParams struct {
	TenantID   string
	ExternalID string
}

type ContactFindByPhoneRow struct {
	ID                 string
	TenantID           string
	DisplayName        sql.NullString
	CommunicationStyle sql.NullString
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) ContactFindByPhone(ctx context.Context, arg ContactFindByPhoneParams) (ContactFindByPhoneRow, error) {
	row := q.db.QueryRowContext(ctx, contactFindByPhone, arg.TenantID, arg.ExternalID)
	var i ContactFindByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.CommunicationStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const contactInsert = `-- name: ContactInsert :one
INSERT INTO contact (tenant_id, display_name)
VALUES ($1, $2)
RETURNING id, tenant_id, display_name, created_at, updated_at
`

type ContactInsertParams struct {
	TenantID    string
	DisplayName sql.NullString
}

type ContactInsertRow struct {
	ID          string
	TenantID    string
	DisplayName sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ContactInsert(ctx context.Context, arg ContactInsertParams) (ContactInsertRow, error) {
	row := q.db.QueryRowContext(ctx, contactInsert, arg.TenantID, arg.DisplayName)
	var i ContactInsertRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const contactSetCommunicationStyle = `-- name: ContactSetCommunicationStyle :exec
UPDATE contact SET communication_style = $1, updated_at = now()
WHERE tenant_id = $2 AND id = $3
`

type ContactSetCommunicationStyleParams struct {
	CommunicationStyle sql.NullString
	TenantID           string
	ID                 string
}

func (q *Queries) ContactSetCommunicationStyle(ctx context.Context, arg ContactSetCommunicationStyleParams) error {
	_, err := q.db.ExecContext(ctx, contactSetCommunicationStyle, arg.CommunicationStyle, arg.TenantID, arg.ID)
	return err
}

const leadSummaryUpsert = `-- name: LeadSummaryUpsert :exec
INSERT INTO lead_summary (tenant_id, contact_id, summary)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, contact_id) DO UPDATE SET summary = EXCLUDED.summary, updated_at = now()
`

type LeadSummaryUpsertParams struct {
	TenantID  string
	ContactID string
	Summary   string
}

func (q *Queries) LeadSummaryUpsert(ctx context.Context, arg LeadSummaryUpsertParams) error {
	_, err := q.db.ExecContext(ctx, leadSummaryUpsert, arg.TenantID, arg.ContactID, arg.Summary)
	return err
}
