// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const conversationCreate = `-- name: ConversationCreate :one
INSERT INTO conversation (tenant_id, channel_identity_id, channel, state, bot_enabled)
VALUES ($1, $2, $3::channel, 'NEW', $4)
RETURNING id, tenant_id, channel_identity_id, channel::text AS channel, state::text AS state,
          bot_enabled, last_inbound_at, last_outbound_at,
          last_inbound_modality::text AS last_inbound_modality,
          created_at, updated_at
`

type ConversationCreateParams struct {
	TenantID          string
	ChannelIdentityID string
	Column3           Channel
	BotEnabled        bool
}

type ConversationCreateRow struct {
	ID                  string
	TenantID            string
	ChannelIdentityID   string
	Channel             string
	State               string
	BotEnabled          bool
	LastInboundAt       sql.NullTime
	LastOutboundAt      sql.NullTime
	LastInboundModality string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) ConversationCreate(ctx context.Context, arg ConversationCreateParams) (ConversationCreateRow, error) {
	row := q.db.QueryRowContext(ctx, conversationCreate,
		arg.TenantID,
		arg.ChannelIdentityID,
		arg.Column3,
		arg.BotEnabled,
	)
	var i ConversationCreateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelIdentityID,
		&i.Channel,
		&i.State,
		&i.BotEnabled,
		&i.LastInboundAt,
		&i.LastOutboundAt,
		&i.LastInboundModality,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const conversationDelete = `-- name: ConversationDelete :exec
DELETE FROM conversation
WHERE tenant_id = $1 AND id = $2
`

type ConversationDeleteParams struct {
	TenantID string
	ID       string
}

func (q *Queries) ConversationDelete(ctx context.Context, arg ConversationDeleteParams) error {
	_, err := q.db.ExecContext(ctx, conversationDelete, arg.TenantID, arg.ID)
	return err
}

const conversationFindByChannelIdentity = `-- name: ConversationFindByChannelIdentity :one
SELECT id, tenant_id, channel_identity_id, channel::text AS channel, state::text AS state,
       bot_enabled, last_inbound_at, last_outbound_at, last_inbound_modality::text AS last_inbound_modality,
       created_at, updated_at
FROM conversation
WHERE channel_identity_id = $1
`

type ConversationFindByChannelIdentityRow struct {
	ID                  string
	TenantID            string
	ChannelIdentityID   string
	Channel             string
	State               string
	BotEnabled          bool
	LastInboundAt       sql.NullTime
	LastOutboundAt      sql.NullTime
	LastInboundModality string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) ConversationFindByChannelIdentity(ctx context.Context, channelIdentityID string) (ConversationFindByChannelIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, conversationFindByChannelIdentity, channelIdentityID)
	var i ConversationFindByChannelIdentityRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelIdentityID,
		&i.Channel,
		&i.State,
		&i.BotEnabled,
		&i.LastInboundAt,
		&i.LastOutboundAt,
		&i.LastInboundModality,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const conversationFindByID = `-- name: ConversationFindByID :one
SELECT id, tenant_id, channel_identity_id, channel::text AS channel, state::text AS state,
       bot_enabled, last_inbound_at, last_outbound_at, last_inbound_modality::text AS last_inbound_modality,
       created_at, updated_at
FROM conversation
WHERE tenant_id = $1 AND id = $2
`

type ConversationFindByIDParams struct {
	TenantID string
	ID       string
}

type ConversationFindByIDRow struct {
	ID                  string
	TenantID            string
	ChannelIdentityID   string
	Channel             string
	State               string
	BotEnabled          bool
	LastInboundAt       sql.NullTime
	LastOutboundAt      sql.NullTime
	LastInboundModality string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) ConversationFindByID(ctx context.Context, arg ConversationFindByIDParams) (ConversationFindByIDRow, error) {
	row := q.db.QueryRowContext(ctx, conversationFindByID, arg.TenantID, arg.ID)
	var i ConversationFindByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelIdentityID,
		&i.Channel,
		&i.State,
		&i.BotEnabled,
		&i.LastInboundAt,
		&i.LastOutboundAt,
		&i.LastInboundModality,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const conversationGetByPhone = `-- name: ConversationGetByPhone :one
SELECT conv.id::text AS id, conv.channel::text AS channel
FROM conversation conv
JOIN channel_identity ci ON ci.id = conv.channel_identity_id
WHERE conv.tenant_id = $1
  AND regexp_replace(ci.external_id, '\D', '', 'g') = $2
ORDER BY conv.last_inbound_at DESC NULLS LAST
LIMIT 1
`

type ConversationGetByPhoneParams struct {
	TenantID   string
	ExternalID string
}

type ConversationGetByPhoneRow struct {
	ID      string
	Channel string
}

func (q *Queries) ConversationGetByPhone(ctx context.Context, arg ConversationGetByPhoneParams) (ConversationGetByPhoneRow, error) {
	row := q.db.QueryRowContext(ctx, conversationGetByPhone, arg.TenantID, arg.ExternalID)
	var i ConversationGetByPhoneRow
	err := row.Scan(&i.ID, &i.Channel)
	return i, err
}

const conversationGetForSend = `-- name: ConversationGetForSend :one
SELECT ci.external_id AS phone, conv.channel::text AS channel
FROM conversation conv
JOIN channel_identity ci ON ci.id = conv.channel_identity_id
WHERE conv.tenant_id = $1 AND conv.id = $2
`

type ConversationGetForSendParams struct {
	TenantID string
	ID       string
}

type ConversationGetForSendRow struct {
	Phone   string
	Channel string
}

func (q *Queries) ConversationGetForSend(ctx context.Context, arg ConversationGetForSendParams) (ConversationGetForSendRow, error) {
	row := q.db.QueryRowContext(ctx, conversationGetForSend, arg.TenantID, arg.ID)
	var i ConversationGetForSendRow
	err := row.Scan(&i.Phone, &i.Channel)
	return i, err
}

const conversationSave = `-- name: ConversationSave :exec
UPDATE conversation
SET state                 = $1::conversation_state,
    last_inbound_at       = $2,
    last_outbound_at      = $3,
    last_inbound_modality = $4::reply_modality,
    updated_at            = now()
WHERE tenant_id = $5 AND id = $6
`

type ConversationSaveParams struct {
	Column1        ConversationState
	LastInboundAt  sql.NullTime
	LastOutboundAt sql.NullTime
	Column4        ReplyModality
	TenantID       string
	ID             string
}

func (q *Queries) ConversationSave(ctx context.Context, arg ConversationSaveParams) error {
	_, err := q.db.ExecContext(ctx, conversationSave,
		arg.Column1,
		arg.LastInboundAt,
		arg.LastOutboundAt,
		arg.Column4,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const conversationSetBotEnabled = `-- name: ConversationSetBotEnabled :exec
UPDATE conversation SET bot_enabled = $1, updated_at = now()
WHERE tenant_id = $2 AND id = $3
`

type ConversationSetBotEnabledParams struct {
	BotEnabled bool
	TenantID   string
	ID         string
}

func (q *Queries) ConversationSetBotEnabled(ctx context.Context, arg ConversationSetBotEnabledParams) error {
	_, err := q.db.ExecContext(ctx, conversationSetBotEnabled, arg.BotEnabled, arg.TenantID, arg.ID)
	return err
}

const conversationSetState = `-- name: ConversationSetState :exec
UPDATE conversation SET state = $1::conversation_state, updated_at = now()
WHERE tenant_id = $2 AND id = $3
`

type ConversationSetStateParams struct {
	Column1  ConversationState
	TenantID string
	ID       string
}

func (q *Queries) ConversationSetState(ctx context.Context, arg ConversationSetStateParams) error {
	_, err := q.db.ExecContext(ctx, conversationSetState, arg.Column1, arg.TenantID, arg.ID)
	return err
}
