// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leads.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const leadCreate = `-- name: LeadCreate :one
INSERT INTO lead (tenant_id, contact_id, status)
VALUES ($1, $2, 'novo')
ON CONFLICT (tenant_id, contact_id) DO UPDATE SET status = lead.status
RETURNING id, created_at
`

type LeadCreateParams struct {
	TenantID  string
	ContactID string
}

type LeadCreateRow struct {
	ID        string
	CreatedAt time.Time
}

func (q *Queries) LeadCreate(ctx context.Context, arg LeadCreateParams) (LeadCreateRow, error) {
	row := q.db.QueryRowContext(ctx, leadCreate, arg.TenantID, arg.ContactID)
	var i LeadCreateRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const leadCreateWithOrigin = `-- name: LeadCreateWithOrigin :exec
INSERT INTO lead (tenant_id, contact_id, status, origin)
VALUES ($1, $2, 'novo', $3)
ON CONFLICT (tenant_id, contact_id) DO NOTHING
`

type LeadCreateWithOriginParams struct {
	TenantID  string
	ContactID string
	Origin    string
}

func (q *Queries) LeadCreateWithOrigin(ctx context.Context, arg LeadCreateWithOriginParams) error {
	_, err := q.db.ExecContext(ctx, leadCreateWithOrigin, arg.TenantID, arg.ContactID, arg.Origin)
	return err
}

const leadDelete = `-- name: LeadDelete :execrows
DELETE FROM lead WHERE tenant_id = $1 AND id = $2
`

type LeadDeleteParams struct {
	TenantID string
	ID       string
}

func (q *Queries) LeadDelete(ctx context.Context, arg LeadDeleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, leadDelete, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const leadPatchStatus = `-- name: LeadPatchStatus :execrows
UPDATE lead
SET status     = COALESCE($3, status),
    owner      = COALESCE($4, owner),
    interest   = COALESCE($5, interest),
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
`

type LeadPatchStatusParams struct {
	TenantID string
	ID       string
	Status   string
	Owner    sql.NullString
	Interest sql.NullString
}

func (q *Queries) LeadPatchStatus(ctx context.Context, arg LeadPatchStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, leadPatchStatus,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.Owner,
		arg.Interest,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
