// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const processingLogInsert = `-- name: ProcessingLogInsert :exec
INSERT INTO bot_processing_log
  (tenant_id, kind, conversation_id, contact_phone, contact_name, inbound_text,
   answered, answered_from_kb, handoff, cited_entry_ids, bubbles, tool_calls, processing_ms, error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type ProcessingLogInsertParams struct {
	TenantID       string
	Kind           string
	ConversationID uuid.NullUUID
	ContactPhone   string
	ContactName    string
	InboundText    string
	Answered       sql.NullBool
	AnsweredFromKb sql.NullBool
	Handoff        sql.NullBool
	CitedEntryIds  pqtype.NullRawMessage
	Bubbles        pqtype.NullRawMessage
	ToolCalls      pqtype.NullRawMessage
	ProcessingMs   int
	Error          sql.NullString
}

func (q *Queries) ProcessingLogInsert(ctx context.Context, arg ProcessingLogInsertParams) error {
	_, err := q.db.ExecContext(ctx, processingLogInsert,
		arg.TenantID,
		arg.Kind,
		arg.ConversationID,
		arg.ContactPhone,
		arg.ContactName,
		arg.InboundText,
		arg.Answered,
		arg.AnsweredFromKb,
		arg.Handoff,
		arg.CitedEntryIds,
		arg.Bubbles,
		arg.ToolCalls,
		arg.ProcessingMs,
		arg.Error,
	)
	return err
}

const processingLogList = `-- name: ProcessingLogList :many
SELECT id::text                         AS id,
       COALESCE(kind, 'message')        AS kind,
       tenant_id,
       COALESCE(conversation_id::text, '') AS conversation_id,
       contact_phone,
       contact_name,
       inbound_text,
       answered,
       answered_from_kb,
       handoff,
       cited_entry_ids::text            AS cited_entry_ids,
       bubbles::text                    AS bubbles,
       COALESCE(tool_calls::text, 'null') AS tool_calls,
       processing_ms,
       COALESCE(error, '')              AS error,
       created_at
FROM bot_processing_log
WHERE tenant_id = $1 AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type ProcessingLogListParams struct {
	TenantID  string
	CreatedAt time.Time
	Limit     int
}

type ProcessingLogListRow struct {
	ID             string
	Kind           string
	TenantID       string
	ConversationID interface{}
	ContactPhone   string
	ContactName    string
	InboundText    string
	Answered       sql.NullBool
	AnsweredFromKb sql.NullBool
	Handoff        sql.NullBool
	CitedEntryIds  string
	Bubbles        string
	ToolCalls      interface{}
	ProcessingMs   int
	Error          string
	CreatedAt      time.Time
}

func (q *Queries) ProcessingLogList(ctx context.Context, arg ProcessingLogListParams) ([]ProcessingLogListRow, error) {
	rows, err := q.db.QueryContext(ctx, processingLogList, arg.TenantID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProcessingLogListRow
	for rows.Next() {
		var i ProcessingLogListRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.TenantID,
			&i.ConversationID,
			&i.ContactPhone,
			&i.ContactName,
			&i.InboundText,
			&i.Answered,
			&i.AnsweredFromKb,
			&i.Handoff,
			&i.CitedEntryIds,
			&i.Bubbles,
			&i.ToolCalls,
			&i.ProcessingMs,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
