// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const conversationGetRecentTurns = `-- name: ConversationGetRecentTurns :many
SELECT role, text FROM (
    SELECT 'user'                                  AS role,
           COALESCE(im.content->>'Text', '[mídia]') AS text,
           im.received_at                           AS ts
    FROM inbound_message im
    WHERE im.conversation_id = $1

    UNION ALL

    SELECT 'assistant'         AS role,
           om.content->>'Text' AS text,
           om.created_at       AS ts
    FROM outbound_message om
    WHERE om.conversation_id = $1
      AND om.content->>'Text' IS NOT NULL
) sub
ORDER BY ts DESC
LIMIT $2
`

type ConversationGetRecentTurnsParams struct {
	ConversationID string
	Limit          int
}

type ConversationGetRecentTurnsRow struct {
	Role string
	Text interface{}
}

func (q *Queries) ConversationGetRecentTurns(ctx context.Context, arg ConversationGetRecentTurnsParams) ([]ConversationGetRecentTurnsRow, error) {
	rows, err := q.db.QueryContext(ctx, conversationGetRecentTurns, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationGetRecentTurnsRow
	for rows.Next() {
		var i ConversationGetRecentTurnsRow
		if err := rows.Scan(&i.Role, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const inboundMessageRecord = `-- name: InboundMessageRecord :execrows
INSERT INTO inbound_message (tenant_id, conversation_id, provider_message_id, content, received_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (tenant_id, provider_message_id) DO NOTHING
`

type InboundMessageRecordParams struct {
	TenantID          string
	ConversationID    string
	ProviderMessageID string
	Content           json.RawMessage
}

func (q *Queries) InboundMessageRecord(ctx context.Context, arg InboundMessageRecordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, inboundMessageRecord,
		arg.TenantID,
		arg.ConversationID,
		arg.ProviderMessageID,
		arg.Content,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const outboundMessageInsertForSend = `-- name: OutboundMessageInsertForSend :exec
INSERT INTO outbound_message
    (tenant_id, conversation_id, provider_message_id, idempotency_key, intent_category, content, status, sent_at)
VALUES ($1, $2, $3, $4, 'FREE_FORM'::outbound_intent, $5, 'sent', now())
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
`

type OutboundMessageInsertForSendParams struct {
	TenantID          string
	ConversationID    string
	ProviderMessageID sql.NullString
	IdempotencyKey    string
	Content           pqtype.NullRawMessage
}

func (q *Queries) OutboundMessageInsertForSend(ctx context.Context, arg OutboundMessageInsertForSendParams) error {
	_, err := q.db.ExecContext(ctx, outboundMessageInsertForSend,
		arg.TenantID,
		arg.ConversationID,
		arg.ProviderMessageID,
		arg.IdempotencyKey,
		arg.Content,
	)
	return err
}

const outboundMessageRecord = `-- name: OutboundMessageRecord :exec
INSERT INTO outbound_message
  (tenant_id, conversation_id, provider_message_id, idempotency_key, intent_category, content, status, sent_at, reasoning)
VALUES ($1, $2, $3, $4, 'FREE_FORM'::outbound_intent, $5, 'sent', now(), $6)
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
`

type OutboundMessageRecordParams struct {
	TenantID          string
	ConversationID    string
	ProviderMessageID sql.NullString
	IdempotencyKey    string
	Content           pqtype.NullRawMessage
	Reasoning         pqtype.NullRawMessage
}

func (q *Queries) OutboundMessageRecord(ctx context.Context, arg OutboundMessageRecordParams) error {
	_, err := q.db.ExecContext(ctx, outboundMessageRecord,
		arg.TenantID,
		arg.ConversationID,
		arg.ProviderMessageID,
		arg.IdempotencyKey,
		arg.Content,
		arg.Reasoning,
	)
	return err
}

const webhookSetNextRetryAt = `-- name: WebhookSetNextRetryAt :exec
UPDATE webhook_events
SET next_retry_at = $1, processing_status = 'failed'
WHERE provider_event_id = $2
`

type WebhookSetNextRetryAtParams struct {
	NextRetryAt     sql.NullTime
	ProviderEventID sql.NullString
}

func (q *Queries) WebhookSetNextRetryAt(ctx context.Context, arg WebhookSetNextRetryAtParams) error {
	_, err := q.db.ExecContext(ctx, webhookSetNextRetryAt, arg.NextRetryAt, arg.ProviderEventID)
	return err
}
