// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Channel string

const (
	ChannelWhatsapp  Channel = "whatsapp"
	ChannelEvolution Channel = "evolution"
)

func (e *Channel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Channel(s)
	case string:
		*e = Channel(s)
	default:
		return fmt.Errorf("unsupported scan type for Channel: %T", src)
	}
	return nil
}

type NullChannel struct {
	Channel Channel
	Valid   bool // Valid is true if Channel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannel) Scan(value interface{}) error {
	if value == nil {
		ns.Channel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Channel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Channel), nil
}

type ConversationState string

const (
	ConversationStateNEW                      ConversationState = "NEW"
	ConversationStateENGAGED                  ConversationState = "ENGAGED"
	ConversationStateAWAITINGREPLY            ConversationState = "AWAITING_REPLY"
	ConversationStateFOLLOWUPPENDING          ConversationState = "FOLLOWUP_PENDING"
	ConversationStateCONCLUDEDPOSITIVE        ConversationState = "CONCLUDED_POSITIVE"
	ConversationStateCONCLUDEDNEGATIVE        ConversationState = "CONCLUDED_NEGATIVE"
	ConversationStateCONCLUDEDNOANSWER        ConversationState = "CONCLUDED_NO_ANSWER"
	ConversationStateAWAITINGTOOLCONFIRMATION ConversationState = "AWAITING_TOOL_CONFIRMATION"
	ConversationStateAWAITINGHUMANAPPROVAL    ConversationState = "AWAITING_HUMAN_APPROVAL"
	ConversationStateHANDOFF                  ConversationState = "HANDOFF"
	ConversationStateDORMANT                  ConversationState = "DORMANT"
	ConversationStateREACTIVATIONSCHEDULED    ConversationState = "REACTIVATION_SCHEDULED"
)

func (e *ConversationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationState(s)
	case string:
		*e = ConversationState(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationState: %T", src)
	}
	return nil
}

type NullConversationState struct {
	ConversationState ConversationState
	Valid             bool // Valid is true if ConversationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationState) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationState), nil
}

type MessageDeliveryStatus string

const (
	MessageDeliveryStatusPending   MessageDeliveryStatus = "pending"
	MessageDeliveryStatusSent      MessageDeliveryStatus = "sent"
	MessageDeliveryStatusDelivered MessageDeliveryStatus = "delivered"
	MessageDeliveryStatusRead      MessageDeliveryStatus = "read"
	MessageDeliveryStatusFailed    MessageDeliveryStatus = "failed"
	MessageDeliveryStatusDeleted   MessageDeliveryStatus = "deleted"
)

func (e *MessageDeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageDeliveryStatus(s)
	case string:
		*e = MessageDeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageDeliveryStatus: %T", src)
	}
	return nil
}

type NullMessageDeliveryStatus struct {
	MessageDeliveryStatus MessageDeliveryStatus
	Valid                 bool // Valid is true if MessageDeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessageDeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageDeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageDeliveryStatus), nil
}

type OutboundIntent string

const (
	OutboundIntentFREEFORM               OutboundIntent = "FREE_FORM"
	OutboundIntentSTRUCTUREDREENGAGEMENT OutboundIntent = "STRUCTURED_REENGAGEMENT"
	OutboundIntentTRANSACTIONALUPDATE    OutboundIntent = "TRANSACTIONAL_UPDATE"
)

func (e *OutboundIntent) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboundIntent(s)
	case string:
		*e = OutboundIntent(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboundIntent: %T", src)
	}
	return nil
}

type NullOutboundIntent struct {
	OutboundIntent OutboundIntent
	Valid          bool // Valid is true if OutboundIntent is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboundIntent) Scan(value interface{}) error {
	if value == nil {
		ns.OutboundIntent, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboundIntent.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboundIntent) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboundIntent), nil
}

type ReplyModality string

const (
	ReplyModalityText  ReplyModality = "text"
	ReplyModalityAudio ReplyModality = "audio"
)

func (e *ReplyModality) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReplyModality(s)
	case string:
		*e = ReplyModality(s)
	default:
		return fmt.Errorf("unsupported scan type for ReplyModality: %T", src)
	}
	return nil
}

type NullReplyModality struct {
	ReplyModality ReplyModality
	Valid         bool // Valid is true if ReplyModality is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReplyModality) Scan(value interface{}) error {
	if value == nil {
		ns.ReplyModality, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReplyModality.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReplyModality) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReplyModality), nil
}

type ScheduledStatus string

const (
	ScheduledStatusPending    ScheduledStatus = "pending"
	ScheduledStatusProcessing ScheduledStatus = "processing"
	ScheduledStatusFired      ScheduledStatus = "fired"
	ScheduledStatusCancelled  ScheduledStatus = "cancelled"
	ScheduledStatusFailed     ScheduledStatus = "failed"
	ScheduledStatusExhausted  ScheduledStatus = "exhausted"
	ScheduledStatusSkipped    ScheduledStatus = "skipped"
)

func (e *ScheduledStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduledStatus(s)
	case string:
		*e = ScheduledStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduledStatus: %T", src)
	}
	return nil
}

type NullScheduledStatus struct {
	ScheduledStatus ScheduledStatus
	Valid           bool // Valid is true if ScheduledStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduledStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduledStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduledStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduledStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduledStatus), nil
}

type WebhookProcessingStatus string

const (
	WebhookProcessingStatusPending    WebhookProcessingStatus = "pending"
	WebhookProcessingStatusProcessing WebhookProcessingStatus = "processing"
	WebhookProcessingStatusDone       WebhookProcessingStatus = "done"
	WebhookProcessingStatusFailed     WebhookProcessingStatus = "failed"
)

func (e *WebhookProcessingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookProcessingStatus(s)
	case string:
		*e = WebhookProcessingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookProcessingStatus: %T", src)
	}
	return nil
}

type NullWebhookProcessingStatus struct {
	WebhookProcessingStatus WebhookProcessingStatus
	Valid                   bool // Valid is true if WebhookProcessingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookProcessingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookProcessingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookProcessingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookProcessingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookProcessingStatus), nil
}

type BotProcessingLog struct {
	ID             string
	TenantID       string
	Kind           string
	ConversationID uuid.NullUUID
	ContactPhone   string
	ContactName    string
	InboundText    string
	Answered       sql.NullBool
	AnsweredFromKb sql.NullBool
	Handoff        sql.NullBool
	CitedEntryIds  pqtype.NullRawMessage
	Bubbles        pqtype.NullRawMessage
	ToolCalls      pqtype.NullRawMessage
	ProcessingMs   int
	Error          sql.NullString
	CreatedAt      time.Time
}

type ChannelIdentity struct {
	ID            string
	TenantID      string
	ContactID     string
	Channel       Channel
	ExternalID    string
	DisplayHandle sql.NullString
	RawProfile    json.RawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Contact struct {
	ID                 string
	TenantID           string
	DisplayName        sql.NullString
	CommunicationStyle sql.NullString
	StructuredFacts    json.RawMessage
	GlobalSuppression  bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Conversation struct {
	ID                     string
	TenantID               string
	ChannelIdentityID      string
	Channel                Channel
	State                  ConversationState
	LastInboundAt          sql.NullTime
	LastOutboundAt         sql.NullTime
	LastInboundModality    NullReplyModality
	ChatwootConversationID sql.NullInt64
	BotEnabled             bool
	PromptTemplateVersion  sql.NullString
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type DomainEvent struct {
	ID          string
	TenantID    string
	EventType   string
	AggregateID string
	Payload     json.RawMessage
	OccurredAt  time.Time
	ProcessedAt sql.NullTime
	Attempts    int
	LastError   sql.NullString
	CreatedAt   time.Time
}

type InboundMessage struct {
	ID                string
	TenantID          string
	ConversationID    string
	ProviderMessageID string
	Content           json.RawMessage
	ReceivedAt        time.Time
	CreatedAt         time.Time
}

type Lead struct {
	ID        string
	TenantID  string
	ContactID string
	Status    string
	Interest  sql.NullString
	Owner     sql.NullString
	Email     sql.NullString
	Origin    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type LeadSummary struct {
	ID        string
	TenantID  string
	ContactID string
	Summary   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OutboundMessage struct {
	ID                string
	TenantID          string
	ConversationID    string
	ProviderMessageID sql.NullString
	IdempotencyKey    string
	Status            MessageDeliveryStatus
	IntentCategory    OutboundIntent
	Content           pqtype.NullRawMessage
	TemplatePayload   pqtype.NullRawMessage
	Error             pqtype.NullRawMessage
	SentAt            sql.NullTime
	Reasoning         pqtype.NullRawMessage
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type PendingBooking struct {
	ID             string
	TenantID       string
	ConversationID string
	ClientPhone    string
	ClientName     string
	StudentName    string
	Kind           string
	Course         string
	ProposedDay    string
	ProposedDate   string
	ProposedTime   string
	ProposedPeriod string
	Age            sql.NullInt32
	Notes          string
	Channel        string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PendingQuestion struct {
	ID             string
	TenantID       string
	ConversationID string
	ClientPhone    string
	ClientName     string
	Question       string
	Status         string
	Draft          sql.NullString
	Channel        string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ScheduledContact struct {
	ID              string
	TenantID        string
	ContactID       string
	ConversationID  uuid.NullUUID
	FireAt          time.Time
	Status          ScheduledStatus
	Payload         json.RawMessage
	Attempts        int
	LastError       sql.NullString
	MaxAttempts     int
	LastAttemptedAt sql.NullTime
	SentAt          sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Tenant struct {
	ID        string
	Name      string
	Slug      string
	Timezone  string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TenantConfig struct {
	ID                          string
	TenantID                    string
	BotName                     string
	BotGender                   string
	MinInitialMs                int
	MaxInitialMs                int
	MinActiveMs                 int
	MaxActiveMs                 int
	InactivityResetMinutes      int
	DebounceMs                  int
	QuietHours                  json.RawMessage
	StrategicHours              []int
	Persona                     json.RawMessage
	KbContent                   json.RawMessage
	SystemPrompt                string
	AdminSystemPrompt           string
	BotEnabledByDefault         bool
	BotAllowedNumbers           json.RawMessage
	AdminWhatsappNumber         string
	AdminWhatsappNumbers        json.RawMessage
	EvolutionBotReplyEnabled    bool
	EvolutionLeadCaptureEnabled bool
	EvolutionCaptureDisabled    json.RawMessage
	NotifPhone                  string
	NotifInstance               string
	NotifEnabled                bool
	NotifOnSuccess              bool
	NotifOnContainerDown        bool
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
}

type WebhookEvent struct {
	ID                string
	TenantID          string
	Provider          string
	ProviderEventID   sql.NullString
	RawPayload        json.RawMessage
	RawBody           []byte
	SignatureVerified bool
	ProcessingStatus  WebhookProcessingStatus
	ReceivedAt        time.Time
	ProcessedAt       sql.NullTime
	LastError         sql.NullString
	Attempts          int
	NextRetryAt       sql.NullTime
	CreatedAt         time.Time
}
