// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const domainEventDrain = `-- name: DomainEventDrain :many
SELECT id, tenant_id, aggregate_id, event_type, payload, occurred_at
FROM domain_events
WHERE processed_at IS NULL
ORDER BY occurred_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type DomainEventDrainRow struct {
	ID          string
	TenantID    string
	AggregateID string
	EventType   string
	Payload     json.RawMessage
	OccurredAt  time.Time
}

func (q *Queries) DomainEventDrain(ctx context.Context, limit int) ([]DomainEventDrainRow, error) {
	rows, err := q.db.QueryContext(ctx, domainEventDrain, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainEventDrainRow
	for rows.Next() {
		var i DomainEventDrainRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainEventEmit = `-- name: DomainEventEmit :exec
INSERT INTO domain_events (tenant_id, event_type, aggregate_id, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5)
`

type DomainEventEmitParams struct {
	TenantID    string
	EventType   string
	AggregateID string
	Payload     json.RawMessage
	OccurredAt  time.Time
}

func (q *Queries) DomainEventEmit(ctx context.Context, arg DomainEventEmitParams) error {
	_, err := q.db.ExecContext(ctx, domainEventEmit,
		arg.TenantID,
		arg.EventType,
		arg.AggregateID,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const domainEventMarkFailed = `-- name: DomainEventMarkFailed :exec
UPDATE domain_events
SET attempts   = attempts + 1,
    last_error = $1
WHERE id = $2
`

type DomainEventMarkFailedParams struct {
	LastError sql.NullString
	ID        string
}

func (q *Queries) DomainEventMarkFailed(ctx context.Context, arg DomainEventMarkFailedParams) error {
	_, err := q.db.ExecContext(ctx, domainEventMarkFailed, arg.LastError, arg.ID)
	return err
}

const domainEventMarkProcessed = `-- name: DomainEventMarkProcessed :exec
UPDATE domain_events SET processed_at = now() WHERE id = $1
`

func (q *Queries) DomainEventMarkProcessed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, domainEventMarkProcessed, id)
	return err
}

const outboundMessageClaim = `-- name: OutboundMessageClaim :execrows
UPDATE outbound_message
SET status     = 'sent',
    sent_at    = now(),
    updated_at = now()
WHERE tenant_id = $1 AND idempotency_key = $2 AND status = 'pending'
`

type OutboundMessageClaimParams struct {
	TenantID       string
	IdempotencyKey string
}

func (q *Queries) OutboundMessageClaim(ctx context.Context, arg OutboundMessageClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, outboundMessageClaim, arg.TenantID, arg.IdempotencyKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const outboundMessageInsert = `-- name: OutboundMessageInsert :execrows
INSERT INTO outbound_message
  (tenant_id, conversation_id, idempotency_key, intent_category, content, template_payload)
VALUES ($1, $2, $3, $4::outbound_intent, $5, $6)
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
`

type OutboundMessageInsertParams struct {
	TenantID        string
	ConversationID  string
	IdempotencyKey  string
	Column4         OutboundIntent
	Content         pqtype.NullRawMessage
	TemplatePayload pqtype.NullRawMessage
}

func (q *Queries) OutboundMessageInsert(ctx context.Context, arg OutboundMessageInsertParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, outboundMessageInsert,
		arg.TenantID,
		arg.ConversationID,
		arg.IdempotencyKey,
		arg.Column4,
		arg.Content,
		arg.TemplatePayload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const webhookEventFindDuplicate = `-- name: WebhookEventFindDuplicate :one
SELECT id FROM webhook_events
WHERE tenant_id = $1 AND provider = $2 AND provider_event_id = $3
`

type WebhookEventFindDuplicateParams struct {
	TenantID        string
	Provider        string
	ProviderEventID sql.NullString
}

func (q *Queries) WebhookEventFindDuplicate(ctx context.Context, arg WebhookEventFindDuplicateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, webhookEventFindDuplicate, arg.TenantID, arg.Provider, arg.ProviderEventID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const webhookEventGetByID = `-- name: WebhookEventGetByID :one
SELECT id, tenant_id, provider, provider_event_id, raw_payload,
       processing_status::text AS processing_status,
       attempts, next_retry_at, last_error,
       processed_at, received_at
FROM webhook_events
WHERE id = $1
`

type WebhookEventGetByIDRow struct {
	ID               string
	TenantID         string
	Provider         string
	ProviderEventID  sql.NullString
	RawPayload       json.RawMessage
	ProcessingStatus string
	Attempts         int
	NextRetryAt      sql.NullTime
	LastError        sql.NullString
	ProcessedAt      sql.NullTime
	ReceivedAt       time.Time
}

func (q *Queries) WebhookEventGetByID(ctx context.Context, id string) (WebhookEventGetByIDRow, error) {
	row := q.db.QueryRowContext(ctx, webhookEventGetByID, id)
	var i WebhookEventGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.ProviderEventID,
		&i.RawPayload,
		&i.ProcessingStatus,
		&i.Attempts,
		&i.NextRetryAt,
		&i.LastError,
		&i.ProcessedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const webhookEventMarkDone = `-- name: WebhookEventMarkDone :exec
UPDATE webhook_events
SET processing_status = 'done', processed_at = now()
WHERE id = $1
`

func (q *Queries) WebhookEventMarkDone(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, webhookEventMarkDone, id)
	return err
}

const webhookEventMarkFailed = `-- name: WebhookEventMarkFailed :exec
UPDATE webhook_events
SET processing_status = 'failed',
    last_error        = left($1, 500),
    attempts          = attempts + 1,
    next_retry_at     = now() + (power(2, attempts) * interval '1 minute')
WHERE id = $2
`

type WebhookEventMarkFailedParams struct {
	Left string
	ID   string
}

func (q *Queries) WebhookEventMarkFailed(ctx context.Context, arg WebhookEventMarkFailedParams) error {
	_, err := q.db.ExecContext(ctx, webhookEventMarkFailed, arg.Left, arg.ID)
	return err
}

const webhookEventPendingRetries = `-- name: WebhookEventPendingRetries :many
SELECT id, tenant_id, provider, provider_event_id, raw_payload,
       processing_status::text AS processing_status,
       attempts, next_retry_at, last_error,
       processed_at, received_at
FROM webhook_events
WHERE processing_status = 'failed'
  AND (next_retry_at IS NULL OR next_retry_at <= now())
ORDER BY next_retry_at NULLS FIRST
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type WebhookEventPendingRetriesRow struct {
	ID               string
	TenantID         string
	Provider         string
	ProviderEventID  sql.NullString
	RawPayload       json.RawMessage
	ProcessingStatus string
	Attempts         int
	NextRetryAt      sql.NullTime
	LastError        sql.NullString
	ProcessedAt      sql.NullTime
	ReceivedAt       time.Time
}

func (q *Queries) WebhookEventPendingRetries(ctx context.Context, limit int) ([]WebhookEventPendingRetriesRow, error) {
	rows, err := q.db.QueryContext(ctx, webhookEventPendingRetries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEventPendingRetriesRow
	for rows.Next() {
		var i WebhookEventPendingRetriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Provider,
			&i.ProviderEventID,
			&i.RawPayload,
			&i.ProcessingStatus,
			&i.Attempts,
			&i.NextRetryAt,
			&i.LastError,
			&i.ProcessedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const webhookEventRecord = `-- name: WebhookEventRecord :one
INSERT INTO webhook_events (tenant_id, provider, provider_event_id, raw_payload, raw_body)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, provider, provider_event_id) DO NOTHING
RETURNING id
`

type WebhookEventRecordParams struct {
	TenantID        string
	Provider        string
	ProviderEventID sql.NullString
	RawPayload      json.RawMessage
	RawBody         []byte
}

func (q *Queries) WebhookEventRecord(ctx context.Context, arg WebhookEventRecordParams) (string, error) {
	row := q.db.QueryRowContext(ctx, webhookEventRecord,
		arg.TenantID,
		arg.Provider,
		arg.ProviderEventID,
		arg.RawPayload,
		arg.RawBody,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
