// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduled.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const scheduledContactCancelFollowUps = `-- name: ScheduledContactCancelFollowUps :exec
UPDATE scheduled_contacts
SET status     = 'cancelled',
    updated_at = now()
WHERE tenant_id      = $1
  AND conversation_id = $2
  AND status          = 'pending'
  AND payload->>'kind' = 'follow_up'
`

type ScheduledContactCancelFollowUpsParams struct {
	TenantID       string
	ConversationID uuid.NullUUID
}

func (q *Queries) ScheduledContactCancelFollowUps(ctx context.Context, arg ScheduledContactCancelFollowUpsParams) error {
	_, err := q.db.ExecContext(ctx, scheduledContactCancelFollowUps, arg.TenantID, arg.ConversationID)
	return err
}

const scheduledContactMarkFailed = `-- name: ScheduledContactMarkFailed :exec
UPDATE scheduled_contacts
SET status            = 'failed',
    last_error        = $1,
    attempts          = attempts + 1,
    last_attempted_at = now(),
    updated_at        = now()
WHERE id = $2
`

type ScheduledContactMarkFailedParams struct {
	LastError sql.NullString
	ID        string
}

func (q *Queries) ScheduledContactMarkFailed(ctx context.Context, arg ScheduledContactMarkFailedParams) error {
	_, err := q.db.ExecContext(ctx, scheduledContactMarkFailed, arg.LastError, arg.ID)
	return err
}

const scheduledContactMarkSent = `-- name: ScheduledContactMarkSent :exec
UPDATE scheduled_contacts
SET status     = 'fired',
    sent_at    = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ScheduledContactMarkSent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, scheduledContactMarkSent, id)
	return err
}

const scheduledContactPendingFollowUps = `-- name: ScheduledContactPendingFollowUps :many
SELECT id, tenant_id, contact_id, conversation_id,
       payload->>'kind'  AS kind,
       status::text      AS status,
       fire_at,
       attempts,
       payload,
       created_at
FROM scheduled_contacts
WHERE payload->>'kind' = 'follow_up'
  AND status = 'pending'
  AND fire_at <= now()
ORDER BY fire_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ScheduledContactPendingFollowUpsRow struct {
	ID             string
	TenantID       string
	ContactID      string
	ConversationID uuid.NullUUID
	Kind           interface{}
	Status         string
	FireAt         time.Time
	Attempts       int
	Payload        json.RawMessage
	CreatedAt      time.Time
}

func (q *Queries) ScheduledContactPendingFollowUps(ctx context.Context, limit int) ([]ScheduledContactPendingFollowUpsRow, error) {
	rows, err := q.db.QueryContext(ctx, scheduledContactPendingFollowUps, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledContactPendingFollowUpsRow
	for rows.Next() {
		var i ScheduledContactPendingFollowUpsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContactID,
			&i.ConversationID,
			&i.Kind,
			&i.Status,
			&i.FireAt,
			&i.Attempts,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduledContactScheduleFollowUp = `-- name: ScheduledContactScheduleFollowUp :exec
INSERT INTO scheduled_contacts (tenant_id, contact_id, conversation_id, fire_at, status, payload)
VALUES ($1, $2, $3, $4, 'pending', '{"kind":"follow_up"}'::jsonb)
ON CONFLICT DO NOTHING
`

type ScheduledContactScheduleFollowUpParams struct {
	TenantID       string
	ContactID      string
	ConversationID uuid.NullUUID
	FireAt         time.Time
}

func (q *Queries) ScheduledContactScheduleFollowUp(ctx context.Context, arg ScheduledContactScheduleFollowUpParams) error {
	_, err := q.db.ExecContext(ctx, scheduledContactScheduleFollowUp,
		arg.TenantID,
		arg.ContactID,
		arg.ConversationID,
		arg.FireAt,
	)
	return err
}

const scheduledContactScheduleReactivation = `-- name: ScheduledContactScheduleReactivation :exec
INSERT INTO scheduled_contacts (tenant_id, contact_id, conversation_id, fire_at, status, payload)
VALUES ($1, $2, $3, $4::date, 'pending', '{"kind":"reactivation"}'::jsonb)
ON CONFLICT DO NOTHING
`

type ScheduledContactScheduleReactivationParams struct {
	TenantID       string
	ContactID      string
	ConversationID uuid.NullUUID
	Column4        time.Time
}

func (q *Queries) ScheduledContactScheduleReactivation(ctx context.Context, arg ScheduledContactScheduleReactivationParams) error {
	_, err := q.db.ExecContext(ctx, scheduledContactScheduleReactivation,
		arg.TenantID,
		arg.ContactID,
		arg.ConversationID,
		arg.Column4,
	)
	return err
}
