// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: turmas.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const listaTurmasRetrato = `-- name: ListaTurmasRetrato :many
SELECT turma_id, nome, curso, horarios, inicio::text AS inicio, fim_previsto::text AS fim_previsto,
       alunos, capacidade, vagas, capturado_em, sumiu_em
FROM bot_turma_retrato
WHERE tenant_id = $1
ORDER BY turma_id
`

type ListaTurmasRetratoRow struct {
	TurmaID     int64
	Nome        string
	Curso       string
	Horarios    json.RawMessage
	Inicio      string
	FimPrevisto string
	Alunos      int
	Capacidade  int
	Vagas       int
	CapturadoEm time.Time
	SumiuEm     sql.NullTime
}

func (q *Queries) ListaTurmasRetrato(ctx context.Context, tenantID string) ([]ListaTurmasRetratoRow, error) {
	rows, err := q.db.QueryContext(ctx, listaTurmasRetrato, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListaTurmasRetratoRow
	for rows.Next() {
		var i ListaTurmasRetratoRow
		if err := rows.Scan(
			&i.TurmaID,
			&i.Nome,
			&i.Curso,
			&i.Horarios,
			&i.Inicio,
			&i.FimPrevisto,
			&i.Alunos,
			&i.Capacidade,
			&i.Vagas,
			&i.CapturadoEm,
			&i.SumiuEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcaTurmasSumidas = `-- name: MarcaTurmasSumidas :exec
UPDATE bot_turma_retrato SET sumiu_em = $1::timestamptz
WHERE tenant_id = $2 AND sumiu_em IS NULL
  AND NOT (turma_id = ANY(string_to_array($3::text, ',')::bigint[]))
`

type MarcaTurmasSumidasParams struct {
	Agora     time.Time
	TenantID  string
	Presentes string
}

// presentes: ids separados por vírgula (” = nenhuma veio). Texto em vez de
// array para o código gerado (database/sql) não depender de lib/pq.
func (q *Queries) MarcaTurmasSumidas(ctx context.Context, arg MarcaTurmasSumidasParams) error {
	_, err := q.db.ExecContext(ctx, marcaTurmasSumidas, arg.Agora, arg.TenantID, arg.Presentes)
	return err
}

const upsertTurmaRetrato = `-- name: UpsertTurmaRetrato :exec

INSERT INTO bot_turma_retrato (tenant_id, turma_id, nome, curso, horarios, inicio, fim_previsto, alunos, capacidade, vagas, capturado_em, sumiu_em)
VALUES ($1, $2, $3, $4, $5, $6::date, $7::date,
        $8, $9, $10, $11, NULL)
ON CONFLICT (tenant_id, turma_id) DO UPDATE SET
  nome = EXCLUDED.nome, curso = EXCLUDED.curso, horarios = EXCLUDED.horarios,
  inicio = EXCLUDED.inicio, fim_previsto = EXCLUDED.fim_previsto,
  alunos = EXCLUDED.alunos, capacidade = EXCLUDED.capacidade, vagas = EXCLUDED.vagas,
  capturado_em = EXCLUDED.capturado_em, sumiu_em = NULL
`

type UpsertTurmaRetratoParams struct {
	TenantID    string
	TurmaID     int64
	Nome        string
	Curso       string
	Horarios    json.RawMessage
	Inicio      time.Time
	FimPrevisto time.Time
	Alunos      int
	Capacidade  int
	Vagas       int
	CapturadoEm time.Time
}

// Retrato das turmas (migration 0046). Ver turmas.go.
func (q *Queries) UpsertTurmaRetrato(ctx context.Context, arg UpsertTurmaRetratoParams) error {
	_, err := q.db.ExecContext(ctx, upsertTurmaRetrato,
		arg.TenantID,
		arg.TurmaID,
		arg.Nome,
		arg.Curso,
		arg.Horarios,
		arg.Inicio,
		arg.FimPrevisto,
		arg.Alunos,
		arg.Capacidade,
		arg.Vagas,
		arg.CapturadoEm,
	)
	return err
}
