// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agenda.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAgendaEvento = `-- name: DeleteAgendaEvento :execrows
DELETE FROM agenda_eventos WHERE id=$1::uuid
`

func (q *Queries) DeleteAgendaEvento(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgendaEvento, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgendaFeriadoMunicipal = `-- name: DeleteAgendaFeriadoMunicipal :execrows
DELETE FROM agenda_feriados_municipais WHERE id=$1
`

func (q *Queries) DeleteAgendaFeriadoMunicipal(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgendaFeriadoMunicipal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgendaEvento = `-- name: GetAgendaEvento :one
SELECT id::text, tipo, titulo, aluno_ou_grupo,
  professor_ou_responsavel_id,
  COALESCE((SELECT name FROM users WHERE id = professor_ou_responsavel_id), '')::text AS professor_ou_responsavel_nome,
  conteudo, jogo, qtd_pessoas, computadores_usados,
  data_inicio::text, hora_inicio::text, hora_fim::text,
  recorrencia, dia_semana, COALESCE(data_fim_recorrencia::text, '')::text AS data_fim_recorrencia,
  status_preparo, notas,
  created_by, COALESCE((SELECT name FROM users WHERE id = created_by), '')::text AS created_by_nome,
  created_at, updated_at
FROM agenda_eventos WHERE id = $1::uuid
`

type GetAgendaEventoRow struct {
	ID                         string
	Tipo                       string
	Titulo                     string
	AlunoOuGrupo               *string
	ProfessorOuResponsavelID   pgtype.Int4
	ProfessorOuResponsavelNome string
	Conteudo                   *string
	Jogo                       *string
	QtdPessoas                 pgtype.Int4
	ComputadoresUsados         int32
	DataInicio                 string
	HoraInicio                 string
	HoraFim                    string
	Recorrencia                string
	DiaSemana                  *int16
	DataFimRecorrencia         string
	StatusPreparo              *string
	Notas                      string
	CreatedBy                  pgtype.Int4
	CreatedByNome              string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

func (q *Queries) GetAgendaEvento(ctx context.Context, dollar_1 pgtype.UUID) (GetAgendaEventoRow, error) {
	row := q.db.QueryRow(ctx, getAgendaEvento, dollar_1)
	var i GetAgendaEventoRow
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Titulo,
		&i.AlunoOuGrupo,
		&i.ProfessorOuResponsavelID,
		&i.ProfessorOuResponsavelNome,
		&i.Conteudo,
		&i.Jogo,
		&i.QtdPessoas,
		&i.ComputadoresUsados,
		&i.DataInicio,
		&i.HoraInicio,
		&i.HoraFim,
		&i.Recorrencia,
		&i.DiaSemana,
		&i.DataFimRecorrencia,
		&i.StatusPreparo,
		&i.Notas,
		&i.CreatedBy,
		&i.CreatedByNome,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgendaEvento = `-- name: InsertAgendaEvento :one
INSERT INTO agenda_eventos (
  tipo, titulo, aluno_ou_grupo, professor_ou_responsavel_id, conteudo, jogo,
  qtd_pessoas, computadores_usados, data_inicio, hora_inicio, hora_fim,
  recorrencia, dia_semana, data_fim_recorrencia, status_preparo, notas, created_by
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8,
  $9::date, $10::time, $11::time,
  $12, $13, $14::date,
  $15, $16, $17
)
RETURNING id::text, tipo, titulo, aluno_ou_grupo,
  professor_ou_responsavel_id,
  COALESCE((SELECT name FROM users WHERE id = professor_ou_responsavel_id), '')::text AS professor_ou_responsavel_nome,
  conteudo, jogo, qtd_pessoas, computadores_usados,
  data_inicio::text, hora_inicio::text, hora_fim::text,
  recorrencia, dia_semana, COALESCE(data_fim_recorrencia::text, '')::text AS data_fim_recorrencia,
  status_preparo, notas,
  created_by, COALESCE((SELECT name FROM users WHERE id = created_by), '')::text AS created_by_nome,
  created_at, updated_at
`

type InsertAgendaEventoParams struct {
	Tipo                     string
	Titulo                   string
	AlunoOuGrupo             *string
	ProfessorOuResponsavelID pgtype.Int4
	Conteudo                 *string
	Jogo                     *string
	QtdPessoas               pgtype.Int4
	ComputadoresUsados       int32
	DataInicio               pgtype.Date
	HoraInicio               pgtype.Time
	HoraFim                  pgtype.Time
	Recorrencia              string
	DiaSemana                *int16
	DataFimRecorrencia       pgtype.Date
	StatusPreparo            *string
	Notas                    string
	CreatedBy                pgtype.Int4
}

type InsertAgendaEventoRow struct {
	ID                         string
	Tipo                       string
	Titulo                     string
	AlunoOuGrupo               *string
	ProfessorOuResponsavelID   pgtype.Int4
	ProfessorOuResponsavelNome string
	Conteudo                   *string
	Jogo                       *string
	QtdPessoas                 pgtype.Int4
	ComputadoresUsados         int32
	DataInicio                 string
	HoraInicio                 string
	HoraFim                    string
	Recorrencia                string
	DiaSemana                  *int16
	DataFimRecorrencia         string
	StatusPreparo              *string
	Notas                      string
	CreatedBy                  pgtype.Int4
	CreatedByNome              string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

func (q *Queries) InsertAgendaEvento(ctx context.Context, arg InsertAgendaEventoParams) (InsertAgendaEventoRow, error) {
	row := q.db.QueryRow(ctx, insertAgendaEvento,
		arg.Tipo,
		arg.Titulo,
		arg.AlunoOuGrupo,
		arg.ProfessorOuResponsavelID,
		arg.Conteudo,
		arg.Jogo,
		arg.QtdPessoas,
		arg.ComputadoresUsados,
		arg.DataInicio,
		arg.HoraInicio,
		arg.HoraFim,
		arg.Recorrencia,
		arg.DiaSemana,
		arg.DataFimRecorrencia,
		arg.StatusPreparo,
		arg.Notas,
		arg.CreatedBy,
	)
	var i InsertAgendaEventoRow
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Titulo,
		&i.AlunoOuGrupo,
		&i.ProfessorOuResponsavelID,
		&i.ProfessorOuResponsavelNome,
		&i.Conteudo,
		&i.Jogo,
		&i.QtdPessoas,
		&i.ComputadoresUsados,
		&i.DataInicio,
		&i.HoraInicio,
		&i.HoraFim,
		&i.Recorrencia,
		&i.DiaSemana,
		&i.DataFimRecorrencia,
		&i.StatusPreparo,
		&i.Notas,
		&i.CreatedBy,
		&i.CreatedByNome,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgendaEventoConfirmacao = `-- name: InsertAgendaEventoConfirmacao :exec
INSERT INTO agenda_evento_confirmacoes (evento_id, user_id, conflitos_com_ids)
VALUES ($1::uuid, $2, $3)
`

type InsertAgendaEventoConfirmacaoParams struct {
	EventoID        pgtype.UUID
	UserID          pgtype.Int4
	ConflitosComIds []string
}

func (q *Queries) InsertAgendaEventoConfirmacao(ctx context.Context, arg InsertAgendaEventoConfirmacaoParams) error {
	_, err := q.db.Exec(ctx, insertAgendaEventoConfirmacao, arg.EventoID, arg.UserID, arg.ConflitosComIds)
	return err
}

const insertAgendaFeriadoMunicipal = `-- name: InsertAgendaFeriadoMunicipal :one
INSERT INTO agenda_feriados_municipais (data, nome) VALUES ($1::date, $2)
RETURNING id, data::text, nome, created_at
`

type InsertAgendaFeriadoMunicipalParams struct {
	Data pgtype.Date
	Nome string
}

type InsertAgendaFeriadoMunicipalRow struct {
	ID        int32
	Data      string
	Nome      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertAgendaFeriadoMunicipal(ctx context.Context, arg InsertAgendaFeriadoMunicipalParams) (InsertAgendaFeriadoMunicipalRow, error) {
	row := q.db.QueryRow(ctx, insertAgendaFeriadoMunicipal, arg.Data, arg.Nome)
	var i InsertAgendaFeriadoMunicipalRow
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.Nome,
		&i.CreatedAt,
	)
	return i, err
}

const listAgendaEventos = `-- name: ListAgendaEventos :many

SELECT id::text, tipo, titulo, aluno_ou_grupo,
  professor_ou_responsavel_id,
  COALESCE((SELECT name FROM users WHERE id = professor_ou_responsavel_id), '')::text AS professor_ou_responsavel_nome,
  conteudo, jogo, qtd_pessoas, computadores_usados,
  data_inicio::text, hora_inicio::text, hora_fim::text,
  recorrencia, dia_semana, COALESCE(data_fim_recorrencia::text, '')::text AS data_fim_recorrencia,
  status_preparo, notas,
  created_by, COALESCE((SELECT name FROM users WHERE id = created_by), '')::text AS created_by_nome,
  created_at, updated_at
FROM agenda_eventos
ORDER BY data_inicio, hora_inicio
`

type ListAgendaEventosRow struct {
	ID                         string
	Tipo                       string
	Titulo                     string
	AlunoOuGrupo               *string
	ProfessorOuResponsavelID   pgtype.Int4
	ProfessorOuResponsavelNome string
	Conteudo                   *string
	Jogo                       *string
	QtdPessoas                 pgtype.Int4
	ComputadoresUsados         int32
	DataInicio                 string
	HoraInicio                 string
	HoraFim                    string
	Recorrencia                string
	DiaSemana                  *int16
	DataFimRecorrencia         string
	StatusPreparo              *string
	Notas                      string
	CreatedBy                  pgtype.Int4
	CreatedByNome              string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

// Queries de Agenda (eventos + confirmações de conflito + feriados municipais)
func (q *Queries) ListAgendaEventos(ctx context.Context) ([]ListAgendaEventosRow, error) {
	rows, err := q.db.Query(ctx, listAgendaEventos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgendaEventosRow{}
	for rows.Next() {
		var i ListAgendaEventosRow
		if err := rows.Scan(
			&i.ID,
			&i.Tipo,
			&i.Titulo,
			&i.AlunoOuGrupo,
			&i.ProfessorOuResponsavelID,
			&i.ProfessorOuResponsavelNome,
			&i.Conteudo,
			&i.Jogo,
			&i.QtdPessoas,
			&i.ComputadoresUsados,
			&i.DataInicio,
			&i.HoraInicio,
			&i.HoraFim,
			&i.Recorrencia,
			&i.DiaSemana,
			&i.DataFimRecorrencia,
			&i.StatusPreparo,
			&i.Notas,
			&i.CreatedBy,
			&i.CreatedByNome,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgendaFeriadosMunicipais = `-- name: ListAgendaFeriadosMunicipais :many
SELECT id, data::text, nome, created_at FROM agenda_feriados_municipais ORDER BY data
`

type ListAgendaFeriadosMunicipaisRow struct {
	ID        int32
	Data      string
	Nome      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListAgendaFeriadosMunicipais(ctx context.Context) ([]ListAgendaFeriadosMunicipaisRow, error) {
	rows, err := q.db.Query(ctx, listAgendaFeriadosMunicipais)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgendaFeriadosMunicipaisRow{}
	for rows.Next() {
		var i ListAgendaFeriadosMunicipaisRow
		if err := rows.Scan(
			&i.ID,
			&i.Data,
			&i.Nome,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgendaFeriadosMunicipaisAno = `-- name: ListAgendaFeriadosMunicipaisAno :many
SELECT id, data::text, nome, created_at FROM agenda_feriados_municipais
WHERE EXTRACT(YEAR FROM data) = $1::int ORDER BY data
`

type ListAgendaFeriadosMunicipaisAnoRow struct {
	ID        int32
	Data      string
	Nome      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListAgendaFeriadosMunicipaisAno(ctx context.Context, ano int32) ([]ListAgendaFeriadosMunicipaisAnoRow, error) {
	rows, err := q.db.Query(ctx, listAgendaFeriadosMunicipaisAno, ano)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgendaFeriadosMunicipaisAnoRow{}
	for rows.Next() {
		var i ListAgendaFeriadosMunicipaisAnoRow
		if err := rows.Scan(
			&i.ID,
			&i.Data,
			&i.Nome,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgendaEvento = `-- name: UpdateAgendaEvento :one
UPDATE agenda_eventos SET
  tipo=$1, titulo=$2, aluno_ou_grupo=$3,
  professor_ou_responsavel_id=$4, conteudo=$5, jogo=$6,
  qtd_pessoas=$7, computadores_usados=$8,
  data_inicio=$9::date, hora_inicio=$10::time, hora_fim=$11::time,
  recorrencia=$12, dia_semana=$13, data_fim_recorrencia=$14::date,
  status_preparo=$15, notas=$16, updated_at=now()
WHERE id=$17::uuid
RETURNING id::text, tipo, titulo, aluno_ou_grupo,
  professor_ou_responsavel_id,
  COALESCE((SELECT name FROM users WHERE id = professor_ou_responsavel_id), '')::text AS professor_ou_responsavel_nome,
  conteudo, jogo, qtd_pessoas, computadores_usados,
  data_inicio::text, hora_inicio::text, hora_fim::text,
  recorrencia, dia_semana, COALESCE(data_fim_recorrencia::text, '')::text AS data_fim_recorrencia,
  status_preparo, notas,
  created_by, COALESCE((SELECT name FROM users WHERE id = created_by), '')::text AS created_by_nome,
  created_at, updated_at
`

type UpdateAgendaEventoParams struct {
	Tipo                     string
	Titulo                   string
	AlunoOuGrupo             *string
	ProfessorOuResponsavelID pgtype.Int4
	Conteudo                 *string
	Jogo                     *string
	QtdPessoas               pgtype.Int4
	ComputadoresUsados       int32
	DataInicio               pgtype.Date
	HoraInicio               pgtype.Time
	HoraFim                  pgtype.Time
	Recorrencia              string
	DiaSemana                *int16
	DataFimRecorrencia       pgtype.Date
	StatusPreparo            *string
	Notas                    string
	ID                       pgtype.UUID
}

type UpdateAgendaEventoRow struct {
	ID                         string
	Tipo                       string
	Titulo                     string
	AlunoOuGrupo               *string
	ProfessorOuResponsavelID   pgtype.Int4
	ProfessorOuResponsavelNome string
	Conteudo                   *string
	Jogo                       *string
	QtdPessoas                 pgtype.Int4
	ComputadoresUsados         int32
	DataInicio                 string
	HoraInicio                 string
	HoraFim                    string
	Recorrencia                string
	DiaSemana                  *int16
	DataFimRecorrencia         string
	StatusPreparo              *string
	Notas                      string
	CreatedBy                  pgtype.Int4
	CreatedByNome              string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

func (q *Queries) UpdateAgendaEvento(ctx context.Context, arg UpdateAgendaEventoParams) (UpdateAgendaEventoRow, error) {
	row := q.db.QueryRow(ctx, updateAgendaEvento,
		arg.Tipo,
		arg.Titulo,
		arg.AlunoOuGrupo,
		arg.ProfessorOuResponsavelID,
		arg.Conteudo,
		arg.Jogo,
		arg.QtdPessoas,
		arg.ComputadoresUsados,
		arg.DataInicio,
		arg.HoraInicio,
		arg.HoraFim,
		arg.Recorrencia,
		arg.DiaSemana,
		arg.DataFimRecorrencia,
		arg.StatusPreparo,
		arg.Notas,
		arg.ID,
	)
	var i UpdateAgendaEventoRow
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Titulo,
		&i.AlunoOuGrupo,
		&i.ProfessorOuResponsavelID,
		&i.ProfessorOuResponsavelNome,
		&i.Conteudo,
		&i.Jogo,
		&i.QtdPessoas,
		&i.ComputadoresUsados,
		&i.DataInicio,
		&i.HoraInicio,
		&i.HoraFim,
		&i.Recorrencia,
		&i.DiaSemana,
		&i.DataFimRecorrencia,
		&i.StatusPreparo,
		&i.Notas,
		&i.CreatedBy,
		&i.CreatedByNome,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
