// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     int64
	UserID int32
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAPIKey = `-- name: InsertAPIKey :one

INSERT INTO api_keys (user_id, name, key_prefix, key_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type InsertAPIKeyParams struct {
	UserID    int32
	Name      string
	KeyPrefix string
	KeyHash   string
	ExpiresAt pgtype.Timestamptz
}

type InsertAPIKeyRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

// Queries de API Keys (Personal Access Tokens)
func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (InsertAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.ExpiresAt,
	)
	var i InsertAPIKeyRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_prefix, last_used_at, expires_at, created_at
FROM api_keys WHERE user_id = $1 ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID         int64
	Name       string
	KeyPrefix  string
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListAPIKeys(ctx context.Context, userID int32) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateAndTouchAPIKey = `-- name: ValidateAndTouchAPIKey :one
UPDATE api_keys SET last_used_at = now()
WHERE key_hash = $1
  AND (expires_at IS NULL OR expires_at > now())
  AND EXISTS (
    SELECT 1 FROM users u
    WHERE u.id = api_keys.user_id
      AND u.suspended_at IS NULL
      AND NOT u.login_disabled
  )
RETURNING user_id
`

func (q *Queries) ValidateAndTouchAPIKey(ctx context.Context, keyHash string) (int32, error) {
	row := q.db.QueryRow(ctx, validateAndTouchAPIKey, keyHash)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}
