// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apirouter.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAPIRouterKeysByProvider = `-- name: CountAPIRouterKeysByProvider :many
SELECT provider_id, status, count(*) AS total FROM api_router_keys GROUP BY provider_id, status
`

type CountAPIRouterKeysByProviderRow struct {
	ProviderID int64
	Status     string
	Total      int64
}

func (q *Queries) CountAPIRouterKeysByProvider(ctx context.Context) ([]CountAPIRouterKeysByProviderRow, error) {
	rows, err := q.db.Query(ctx, countAPIRouterKeysByProvider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAPIRouterKeysByProviderRow{}
	for rows.Next() {
		var i CountAPIRouterKeysByProviderRow
		if err := rows.Scan(&i.ProviderID, &i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAPIRouterKey = `-- name: DeleteAPIRouterKey :execrows
DELETE FROM api_router_keys WHERE id = $1 AND provider_id = $2
`

type DeleteAPIRouterKeyParams struct {
	ID         int64
	ProviderID int64
}

func (q *Queries) DeleteAPIRouterKey(ctx context.Context, arg DeleteAPIRouterKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIRouterKey, arg.ID, arg.ProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAPIRouterProvider = `-- name: DeleteAPIRouterProvider :execrows
DELETE FROM api_router_providers WHERE id = $1
`

func (q *Queries) DeleteAPIRouterProvider(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIRouterProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIRouterKey = `-- name: GetAPIRouterKey :one
SELECT id, provider_id, label, secret_enc, secret_tail, status, priority, failure_count, last_used_at, last_error_at, last_error_code, created_at, updated_at
FROM api_router_keys WHERE id = $1 AND provider_id = $2
`

type GetAPIRouterKeyParams struct {
	ID         int64
	ProviderID int64
}

func (q *Queries) GetAPIRouterKey(ctx context.Context, arg GetAPIRouterKeyParams) (ApiRouterKey, error) {
	row := q.db.QueryRow(ctx, getAPIRouterKey, arg.ID, arg.ProviderID)
	var i ApiRouterKey
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Label,
		&i.SecretEnc,
		&i.SecretTail,
		&i.Status,
		&i.Priority,
		&i.FailureCount,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIRouterProvider = `-- name: GetAPIRouterProvider :one
SELECT id, name, base_url, auth_header, auth_scheme, unauthorized_codes, no_credit_codes, test_path, test_method, chat_adapter, created_at, updated_at
FROM api_router_providers WHERE id = $1
`

func (q *Queries) GetAPIRouterProvider(ctx context.Context, id int64) (ApiRouterProvider, error) {
	row := q.db.QueryRow(ctx, getAPIRouterProvider, id)
	var i ApiRouterProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthHeader,
		&i.AuthScheme,
		&i.UnauthorizedCodes,
		&i.NoCreditCodes,
		&i.TestPath,
		&i.TestMethod,
		&i.ChatAdapter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAPIRouterKey = `-- name: InsertAPIRouterKey :one
INSERT INTO api_router_keys (provider_id, label, secret_enc, secret_tail, priority)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, provider_id, label, secret_enc, secret_tail, status, priority, failure_count, last_used_at, last_error_at, last_error_code, created_at, updated_at
`

type InsertAPIRouterKeyParams struct {
	ProviderID int64
	Label      string
	SecretEnc  string
	SecretTail string
	Priority   int32
}

func (q *Queries) InsertAPIRouterKey(ctx context.Context, arg InsertAPIRouterKeyParams) (ApiRouterKey, error) {
	row := q.db.QueryRow(ctx, insertAPIRouterKey,
		arg.ProviderID,
		arg.Label,
		arg.SecretEnc,
		arg.SecretTail,
		arg.Priority,
	)
	var i ApiRouterKey
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Label,
		&i.SecretEnc,
		&i.SecretTail,
		&i.Status,
		&i.Priority,
		&i.FailureCount,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAPIRouterProvider = `-- name: InsertAPIRouterProvider :one
INSERT INTO api_router_providers (name, base_url, auth_header, auth_scheme, unauthorized_codes, no_credit_codes, test_path, test_method, chat_adapter)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, base_url, auth_header, auth_scheme, unauthorized_codes, no_credit_codes, test_path, test_method, chat_adapter, created_at, updated_at
`

type InsertAPIRouterProviderParams struct {
	Name              string
	BaseUrl           string
	AuthHeader        string
	AuthScheme        string
	UnauthorizedCodes []int32
	NoCreditCodes     []int32
	TestPath          string
	TestMethod        string
	ChatAdapter       string
}

func (q *Queries) InsertAPIRouterProvider(ctx context.Context, arg InsertAPIRouterProviderParams) (ApiRouterProvider, error) {
	row := q.db.QueryRow(ctx, insertAPIRouterProvider,
		arg.Name,
		arg.BaseUrl,
		arg.AuthHeader,
		arg.AuthScheme,
		arg.UnauthorizedCodes,
		arg.NoCreditCodes,
		arg.TestPath,
		arg.TestMethod,
		arg.ChatAdapter,
	)
	var i ApiRouterProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthHeader,
		&i.AuthScheme,
		&i.UnauthorizedCodes,
		&i.NoCreditCodes,
		&i.TestPath,
		&i.TestMethod,
		&i.ChatAdapter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIRouterKeys = `-- name: ListAPIRouterKeys :many
SELECT id, provider_id, label, secret_enc, secret_tail, status, priority, failure_count, last_used_at, last_error_at, last_error_code, created_at, updated_at
FROM api_router_keys WHERE provider_id = $1 ORDER BY priority ASC, id ASC
`

func (q *Queries) ListAPIRouterKeys(ctx context.Context, providerID int64) ([]ApiRouterKey, error) {
	rows, err := q.db.Query(ctx, listAPIRouterKeys, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiRouterKey{}
	for rows.Next() {
		var i ApiRouterKey
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Label,
			&i.SecretEnc,
			&i.SecretTail,
			&i.Status,
			&i.Priority,
			&i.FailureCount,
			&i.LastUsedAt,
			&i.LastErrorAt,
			&i.LastErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIRouterProviders = `-- name: ListAPIRouterProviders :many

SELECT id, name, base_url, auth_header, auth_scheme, unauthorized_codes, no_credit_codes, test_path, test_method, chat_adapter, created_at, updated_at
FROM api_router_providers ORDER BY name ASC
`

// Queries do roteador de chaves de API (failover automático em 401/sem-créditos)
func (q *Queries) ListAPIRouterProviders(ctx context.Context) ([]ApiRouterProvider, error) {
	rows, err := q.db.Query(ctx, listAPIRouterProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiRouterProvider{}
	for rows.Next() {
		var i ApiRouterProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.AuthHeader,
			&i.AuthScheme,
			&i.UnauthorizedCodes,
			&i.NoCreditCodes,
			&i.TestPath,
			&i.TestMethod,
			&i.ChatAdapter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAPIRouterKeys = `-- name: ListActiveAPIRouterKeys :many
SELECT id, provider_id, label, secret_enc, secret_tail, status, priority, failure_count, last_used_at, last_error_at, last_error_code, created_at, updated_at
FROM api_router_keys WHERE provider_id = $1 AND status = 'active' ORDER BY priority ASC, id ASC
`

func (q *Queries) ListActiveAPIRouterKeys(ctx context.Context, providerID int64) ([]ApiRouterKey, error) {
	rows, err := q.db.Query(ctx, listActiveAPIRouterKeys, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiRouterKey{}
	for rows.Next() {
		var i ApiRouterKey
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Label,
			&i.SecretEnc,
			&i.SecretTail,
			&i.Status,
			&i.Priority,
			&i.FailureCount,
			&i.LastUsedAt,
			&i.LastErrorAt,
			&i.LastErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAPIRouterKeyFailure = `-- name: RecordAPIRouterKeyFailure :exec
UPDATE api_router_keys SET
  status = $2, failure_count = failure_count + 1,
  last_error_at = now(), last_error_code = $3, last_used_at = now(), updated_at = now()
WHERE id = $1
`

type RecordAPIRouterKeyFailureParams struct {
	ID            int64
	Status        string
	LastErrorCode pgtype.Int4
}

func (q *Queries) RecordAPIRouterKeyFailure(ctx context.Context, arg RecordAPIRouterKeyFailureParams) error {
	_, err := q.db.Exec(ctx, recordAPIRouterKeyFailure, arg.ID, arg.Status, arg.LastErrorCode)
	return err
}

const recordAPIRouterKeySuccess = `-- name: RecordAPIRouterKeySuccess :exec
UPDATE api_router_keys SET status = 'active', failure_count = 0, last_used_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) RecordAPIRouterKeySuccess(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, recordAPIRouterKeySuccess, id)
	return err
}

const setAPIRouterKeyStatus = `-- name: SetAPIRouterKeyStatus :one
UPDATE api_router_keys SET
  status = $3,
  failure_count = CASE WHEN $3 = 'active' THEN 0 ELSE failure_count END,
  updated_at = now()
WHERE id = $1 AND provider_id = $2
RETURNING id, provider_id, label, secret_enc, secret_tail, status, priority, failure_count, last_used_at, last_error_at, last_error_code, created_at, updated_at
`

type SetAPIRouterKeyStatusParams struct {
	ID         int64
	ProviderID int64
	Status     string
}

func (q *Queries) SetAPIRouterKeyStatus(ctx context.Context, arg SetAPIRouterKeyStatusParams) (ApiRouterKey, error) {
	row := q.db.QueryRow(ctx, setAPIRouterKeyStatus, arg.ID, arg.ProviderID, arg.Status)
	var i ApiRouterKey
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Label,
		&i.SecretEnc,
		&i.SecretTail,
		&i.Status,
		&i.Priority,
		&i.FailureCount,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAPIRouterProviderChatAdapter = `-- name: SetAPIRouterProviderChatAdapter :one
UPDATE api_router_providers SET chat_adapter = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, base_url, auth_header, auth_scheme, unauthorized_codes, no_credit_codes, test_path, test_method, chat_adapter, created_at, updated_at
`

type SetAPIRouterProviderChatAdapterParams struct {
	ID          int64
	ChatAdapter string
}

func (q *Queries) SetAPIRouterProviderChatAdapter(ctx context.Context, arg SetAPIRouterProviderChatAdapterParams) (ApiRouterProvider, error) {
	row := q.db.QueryRow(ctx, setAPIRouterProviderChatAdapter, arg.ID, arg.ChatAdapter)
	var i ApiRouterProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthHeader,
		&i.AuthScheme,
		&i.UnauthorizedCodes,
		&i.NoCreditCodes,
		&i.TestPath,
		&i.TestMethod,
		&i.ChatAdapter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAPIRouterKeyMeta = `-- name: UpdateAPIRouterKeyMeta :one
UPDATE api_router_keys SET label = $3, priority = $4, updated_at = now()
WHERE id = $1 AND provider_id = $2
RETURNING id, provider_id, label, secret_enc, secret_tail, status, priority, failure_count, last_used_at, last_error_at, last_error_code, created_at, updated_at
`

type UpdateAPIRouterKeyMetaParams struct {
	ID         int64
	ProviderID int64
	Label      string
	Priority   int32
}

func (q *Queries) UpdateAPIRouterKeyMeta(ctx context.Context, arg UpdateAPIRouterKeyMetaParams) (ApiRouterKey, error) {
	row := q.db.QueryRow(ctx, updateAPIRouterKeyMeta,
		arg.ID,
		arg.ProviderID,
		arg.Label,
		arg.Priority,
	)
	var i ApiRouterKey
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Label,
		&i.SecretEnc,
		&i.SecretTail,
		&i.Status,
		&i.Priority,
		&i.FailureCount,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAPIRouterProvider = `-- name: UpdateAPIRouterProvider :one
UPDATE api_router_providers SET
  name = $2, base_url = $3, auth_header = $4, auth_scheme = $5,
  unauthorized_codes = $6, no_credit_codes = $7, test_path = $8, test_method = $9,
  chat_adapter = $10, updated_at = now()
WHERE id = $1
RETURNING id, name, base_url, auth_header, auth_scheme, unauthorized_codes, no_credit_codes, test_path, test_method, chat_adapter, created_at, updated_at
`

type UpdateAPIRouterProviderParams struct {
	ID                int64
	Name              string
	BaseUrl           string
	AuthHeader        string
	AuthScheme        string
	UnauthorizedCodes []int32
	NoCreditCodes     []int32
	TestPath          string
	TestMethod        string
	ChatAdapter       string
}

func (q *Queries) UpdateAPIRouterProvider(ctx context.Context, arg UpdateAPIRouterProviderParams) (ApiRouterProvider, error) {
	row := q.db.QueryRow(ctx, updateAPIRouterProvider,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.AuthHeader,
		arg.AuthScheme,
		arg.UnauthorizedCodes,
		arg.NoCreditCodes,
		arg.TestPath,
		arg.TestMethod,
		arg.ChatAdapter,
	)
	var i ApiRouterProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthHeader,
		&i.AuthScheme,
		&i.UnauthorizedCodes,
		&i.NoCreditCodes,
		&i.TestPath,
		&i.TestMethod,
		&i.ChatAdapter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
