// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id::text
`

type CreateSessionParams struct {
	UserID           int32
	RefreshTokenHash string
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.RefreshTokenHash, arg.ExpiresAt)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUser, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const expireUserAPIKeys = `-- name: ExpireUserAPIKeys :exec
UPDATE api_keys SET expires_at = now()
WHERE user_id = $1 AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) ExpireUserAPIKeys(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, expireUserAPIKeys, userID)
	return err
}

const getAccountSummaries = `-- name: GetAccountSummaries :many
SELECT s.id::text, u.name, u.email, u.avatar_url
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.id = ANY($1::uuid[]) AND s.expires_at > now() AND u.suspended_at IS NULL
`

type GetAccountSummariesRow struct {
	SID       string
	Name      string
	Email     string
	AvatarUrl *string
}

func (q *Queries) GetAccountSummaries(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetAccountSummariesRow, error) {
	rows, err := q.db.Query(ctx, getAccountSummaries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountSummariesRow{}
	for rows.Next() {
		var i GetAccountSummariesRow
		if err := rows.Scan(
			&i.SID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomRolePermissions = `-- name: GetCustomRolePermissions :one
SELECT permissions FROM custom_roles WHERE id = $1
`

func (q *Queries) GetCustomRolePermissions(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCustomRolePermissions, id)
	var permissions []byte
	err := row.Scan(&permissions)
	return permissions, err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id::text, user_id, expires_at FROM sessions WHERE refresh_token_hash = $1
`

type GetSessionByHashRow struct {
	ID        string
	UserID    int32
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetSessionByHash(ctx context.Context, refreshTokenHash string) (GetSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, refreshTokenHash)
	var i GetSessionByHashRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.email, u.username, u.name, u.password_hash, u.avatar_url, u.role, u.custom_role_id::text, u.mfa_enabled, u.totp_secret, u.suspended_at, u.created_at, u.preferences, u.quota_bytes, u.email_verified_at, u.mfa_method, u.login_disabled
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.id = $1::uuid AND s.expires_at > now()
`

type GetSessionUserRow struct {
	ID              int32
	Email           string
	Username        *string
	Name            string
	PasswordHash    *string
	AvatarUrl       *string
	Role            int16
	UCustomRoleID   string
	MfaEnabled      bool
	TotpSecret      *string
	SuspendedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Preferences     []byte
	QuotaBytes      int64
	EmailVerifiedAt pgtype.Timestamptz
	MfaMethod       string
	LoginDisabled   bool
}

func (q *Queries) GetSessionUser(ctx context.Context, dollar_1 pgtype.UUID) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, dollar_1)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.UCustomRoleID,
		&i.MfaEnabled,
		&i.TotpSecret,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.Preferences,
		&i.QuotaBytes,
		&i.EmailVerifiedAt,
		&i.MfaMethod,
		&i.LoginDisabled,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, name, password_hash, avatar_url, role, custom_role_id::text, mfa_enabled, totp_secret, suspended_at, created_at, preferences, quota_bytes, email_verified_at, mfa_method, login_disabled
FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID              int32
	Email           string
	Username        *string
	Name            string
	PasswordHash    *string
	AvatarUrl       *string
	Role            int16
	CustomRoleID    string
	MfaEnabled      bool
	TotpSecret      *string
	SuspendedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Preferences     []byte
	QuotaBytes      int64
	EmailVerifiedAt pgtype.Timestamptz
	MfaMethod       string
	LoginDisabled   bool
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.CustomRoleID,
		&i.MfaEnabled,
		&i.TotpSecret,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.Preferences,
		&i.QuotaBytes,
		&i.EmailVerifiedAt,
		&i.MfaMethod,
		&i.LoginDisabled,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, username, name, password_hash, avatar_url, role, custom_role_id::text, mfa_enabled, totp_secret, suspended_at, created_at, preferences, quota_bytes, email_verified_at, mfa_method, login_disabled
FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID              int32
	Email           string
	Username        *string
	Name            string
	PasswordHash    *string
	AvatarUrl       *string
	Role            int16
	CustomRoleID    string
	MfaEnabled      bool
	TotpSecret      *string
	SuspendedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Preferences     []byte
	QuotaBytes      int64
	EmailVerifiedAt pgtype.Timestamptz
	MfaMethod       string
	LoginDisabled   bool
}

// Queries de autenticação: usuários e sessões
func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.CustomRoleID,
		&i.MfaEnabled,
		&i.TotpSecret,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.Preferences,
		&i.QuotaBytes,
		&i.EmailVerifiedAt,
		&i.MfaMethod,
		&i.LoginDisabled,
	)
	return i, err
}

const getUserByIdentifier = `-- name: GetUserByIdentifier :one
SELECT id, email, username, name, password_hash, avatar_url, role, custom_role_id::text, mfa_enabled, totp_secret, suspended_at, created_at, preferences, quota_bytes, email_verified_at, mfa_method, login_disabled
FROM users WHERE email = $1 OR username = $1
`

type GetUserByIdentifierRow struct {
	ID              int32
	Email           string
	Username        *string
	Name            string
	PasswordHash    *string
	AvatarUrl       *string
	Role            int16
	CustomRoleID    string
	MfaEnabled      bool
	TotpSecret      *string
	SuspendedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Preferences     []byte
	QuotaBytes      int64
	EmailVerifiedAt pgtype.Timestamptz
	MfaMethod       string
	LoginDisabled   bool
}

func (q *Queries) GetUserByIdentifier(ctx context.Context, email string) (GetUserByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, getUserByIdentifier, email)
	var i GetUserByIdentifierRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.CustomRoleID,
		&i.MfaEnabled,
		&i.TotpSecret,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.Preferences,
		&i.QuotaBytes,
		&i.EmailVerifiedAt,
		&i.MfaMethod,
		&i.LoginDisabled,
	)
	return i, err
}

const insertSharedMailbox = `-- name: InsertSharedMailbox :one
INSERT INTO users (email, name, role, login_disabled)
VALUES ($1, $2, $3, true)
RETURNING id, email, username, name, password_hash, avatar_url, role, custom_role_id::text, mfa_enabled, totp_secret, suspended_at, created_at, preferences, quota_bytes, email_verified_at, mfa_method, login_disabled
`

type InsertSharedMailboxParams struct {
	Email string
	Name  string
	Role  int16
}

type InsertSharedMailboxRow struct {
	ID              int32
	Email           string
	Username        *string
	Name            string
	PasswordHash    *string
	AvatarUrl       *string
	Role            int16
	CustomRoleID    string
	MfaEnabled      bool
	TotpSecret      *string
	SuspendedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Preferences     []byte
	QuotaBytes      int64
	EmailVerifiedAt pgtype.Timestamptz
	MfaMethod       string
	LoginDisabled   bool
}

func (q *Queries) InsertSharedMailbox(ctx context.Context, arg InsertSharedMailboxParams) (InsertSharedMailboxRow, error) {
	row := q.db.QueryRow(ctx, insertSharedMailbox, arg.Email, arg.Name, arg.Role)
	var i InsertSharedMailboxRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.CustomRoleID,
		&i.MfaEnabled,
		&i.TotpSecret,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.Preferences,
		&i.QuotaBytes,
		&i.EmailVerifiedAt,
		&i.MfaMethod,
		&i.LoginDisabled,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, username, name, password_hash, avatar_url, role, custom_role_id::text, mfa_enabled, totp_secret, suspended_at, created_at, preferences, quota_bytes, email_verified_at, mfa_method, login_disabled
`

type InsertUserParams struct {
	Email        string
	Name         string
	PasswordHash *string
}

type InsertUserRow struct {
	ID              int32
	Email           string
	Username        *string
	Name            string
	PasswordHash    *string
	AvatarUrl       *string
	Role            int16
	CustomRoleID    string
	MfaEnabled      bool
	TotpSecret      *string
	SuspendedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Preferences     []byte
	QuotaBytes      int64
	EmailVerifiedAt pgtype.Timestamptz
	MfaMethod       string
	LoginDisabled   bool
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Email, arg.Name, arg.PasswordHash)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.CustomRoleID,
		&i.MfaEnabled,
		&i.TotpSecret,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.Preferences,
		&i.QuotaBytes,
		&i.EmailVerifiedAt,
		&i.MfaMethod,
		&i.LoginDisabled,
	)
	return i, err
}

const insertUserWithRole = `-- name: InsertUserWithRole :one
INSERT INTO users (email, name, role)
VALUES ($1, $2, $3)
RETURNING id, email, username, name, password_hash, avatar_url, role, custom_role_id::text, mfa_enabled, totp_secret, suspended_at, created_at, preferences, quota_bytes, email_verified_at, mfa_method, login_disabled
`

type InsertUserWithRoleParams struct {
	Email string
	Name  string
	Role  int16
}

type InsertUserWithRoleRow struct {
	ID              int32
	Email           string
	Username        *string
	Name            string
	PasswordHash    *string
	AvatarUrl       *string
	Role            int16
	CustomRoleID    string
	MfaEnabled      bool
	TotpSecret      *string
	SuspendedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Preferences     []byte
	QuotaBytes      int64
	EmailVerifiedAt pgtype.Timestamptz
	MfaMethod       string
	LoginDisabled   bool
}

func (q *Queries) InsertUserWithRole(ctx context.Context, arg InsertUserWithRoleParams) (InsertUserWithRoleRow, error) {
	row := q.db.QueryRow(ctx, insertUserWithRole, arg.Email, arg.Name, arg.Role)
	var i InsertUserWithRoleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.CustomRoleID,
		&i.MfaEnabled,
		&i.TotpSecret,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.Preferences,
		&i.QuotaBytes,
		&i.EmailVerifiedAt,
		&i.MfaMethod,
		&i.LoginDisabled,
	)
	return i, err
}

const linkOAuth = `-- name: LinkOAuth :exec
INSERT INTO oauth_accounts (user_id, provider, provider_id)
VALUES ($1, $2, $3)
ON CONFLICT (provider, provider_id) DO NOTHING
`

type LinkOAuthParams struct {
	UserID     int32
	Provider   string
	ProviderID string
}

func (q *Queries) LinkOAuth(ctx context.Context, arg LinkOAuthParams) error {
	_, err := q.db.Exec(ctx, linkOAuth, arg.UserID, arg.Provider, arg.ProviderID)
	return err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, email, username, name, password_hash, avatar_url, role, custom_role_id::text, mfa_enabled, totp_secret, suspended_at, created_at, preferences, quota_bytes, email_verified_at, mfa_method, login_disabled
FROM users ORDER BY created_at DESC
`

type ListAllUsersRow struct {
	ID              int32
	Email           string
	Username        *string
	Name            string
	PasswordHash    *string
	AvatarUrl       *string
	Role            int16
	CustomRoleID    string
	MfaEnabled      bool
	TotpSecret      *string
	SuspendedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Preferences     []byte
	QuotaBytes      int64
	EmailVerifiedAt pgtype.Timestamptz
	MfaMethod       string
	LoginDisabled   bool
}

func (q *Queries) ListAllUsers(ctx context.Context) ([]ListAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllUsersRow{}
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Name,
			&i.PasswordHash,
			&i.AvatarUrl,
			&i.Role,
			&i.CustomRoleID,
			&i.MfaEnabled,
			&i.TotpSecret,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.Preferences,
			&i.QuotaBytes,
			&i.EmailVerifiedAt,
			&i.MfaMethod,
			&i.LoginDisabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByDomain = `-- name: ListUsersByDomain :many
SELECT id, email, username, name, password_hash, avatar_url, role, custom_role_id::text, mfa_enabled, totp_secret, suspended_at, created_at, preferences, quota_bytes, email_verified_at, mfa_method, login_disabled
FROM users WHERE email LIKE '%@' || $1 ORDER BY created_at DESC
`

type ListUsersByDomainRow struct {
	ID              int32
	Email           string
	Username        *string
	Name            string
	PasswordHash    *string
	AvatarUrl       *string
	Role            int16
	CustomRoleID    string
	MfaEnabled      bool
	TotpSecret      *string
	SuspendedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Preferences     []byte
	QuotaBytes      int64
	EmailVerifiedAt pgtype.Timestamptz
	MfaMethod       string
	LoginDisabled   bool
}

func (q *Queries) ListUsersByDomain(ctx context.Context, dollar_1 *string) ([]ListUsersByDomainRow, error) {
	rows, err := q.db.Query(ctx, listUsersByDomain, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByDomainRow{}
	for rows.Next() {
		var i ListUsersByDomainRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Name,
			&i.PasswordHash,
			&i.AvatarUrl,
			&i.Role,
			&i.CustomRoleID,
			&i.MfaEnabled,
			&i.TotpSecret,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.Preferences,
			&i.QuotaBytes,
			&i.EmailVerifiedAt,
			&i.MfaMethod,
			&i.LoginDisabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified_at = now() WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const setMFA = `-- name: SetMFA :exec
UPDATE users SET mfa_enabled = $1, totp_secret = $2 WHERE id = $3
`

type SetMFAParams struct {
	MfaEnabled bool
	TotpSecret *string
	ID         int32
}

func (q *Queries) SetMFA(ctx context.Context, arg SetMFAParams) error {
	_, err := q.db.Exec(ctx, setMFA, arg.MfaEnabled, arg.TotpSecret, arg.ID)
	return err
}

const setMFAEnabled = `-- name: SetMFAEnabled :exec
UPDATE users SET mfa_enabled = true, mfa_method = $1 WHERE id = $2
`

type SetMFAEnabledParams struct {
	MfaMethod string
	ID        int32
}

func (q *Queries) SetMFAEnabled(ctx context.Context, arg SetMFAEnabledParams) error {
	_, err := q.db.Exec(ctx, setMFAEnabled, arg.MfaMethod, arg.ID)
	return err
}

const setMFAMethod = `-- name: SetMFAMethod :exec
UPDATE users SET mfa_method = $1 WHERE id = $2
`

type SetMFAMethodParams struct {
	MfaMethod string
	ID        int32
}

func (q *Queries) SetMFAMethod(ctx context.Context, arg SetMFAMethodParams) error {
	_, err := q.db.Exec(ctx, setMFAMethod, arg.MfaMethod, arg.ID)
	return err
}

const suspendUser = `-- name: SuspendUser :exec
UPDATE users SET suspended_at = now() WHERE id = $1
`

func (q *Queries) SuspendUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, suspendUser, id)
	return err
}

const unsuspendUser = `-- name: UnsuspendUser :exec
UPDATE users SET suspended_at = NULL WHERE id = $1
`

func (q *Queries) UnsuspendUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, unsuspendUser, id)
	return err
}

const updateAvatarURL = `-- name: UpdateAvatarURL :exec
UPDATE users SET avatar_url = $1 WHERE id = $2
`

type UpdateAvatarURLParams struct {
	AvatarUrl *string
	ID        int32
}

func (q *Queries) UpdateAvatarURL(ctx context.Context, arg UpdateAvatarURLParams) error {
	_, err := q.db.Exec(ctx, updateAvatarURL, arg.AvatarUrl, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type UpdatePasswordParams struct {
	PasswordHash *string
	ID           int32
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserAdmin = `-- name: UpdateUserAdmin :one
UPDATE users SET
  name           = COALESCE($2, name),
  role           = COALESCE($3, role),
  quota_bytes    = COALESCE($4, quota_bytes),
  custom_role_id = CASE
                     WHEN $3 = 4 THEN $5::uuid
                     WHEN $3 IS NOT NULL AND $3 != 4 THEN NULL
                     ELSE custom_role_id
                   END
WHERE id = $1
RETURNING id, email, username, name, password_hash, avatar_url, role, custom_role_id::text, mfa_enabled, totp_secret, suspended_at, created_at, preferences, quota_bytes, email_verified_at, mfa_method, login_disabled
`

type UpdateUserAdminParams struct {
	ID         int32
	Name       string
	Role       int16
	QuotaBytes int64
	Column5    pgtype.UUID
}

type UpdateUserAdminRow struct {
	ID              int32
	Email           string
	Username        *string
	Name            string
	PasswordHash    *string
	AvatarUrl       *string
	Role            int16
	CustomRoleID    string
	MfaEnabled      bool
	TotpSecret      *string
	SuspendedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	Preferences     []byte
	QuotaBytes      int64
	EmailVerifiedAt pgtype.Timestamptz
	MfaMethod       string
	LoginDisabled   bool
}

func (q *Queries) UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (UpdateUserAdminRow, error) {
	row := q.db.QueryRow(ctx, updateUserAdmin,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.QuotaBytes,
		arg.Column5,
	)
	var i UpdateUserAdminRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.CustomRoleID,
		&i.MfaEnabled,
		&i.TotpSecret,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.Preferences,
		&i.QuotaBytes,
		&i.EmailVerifiedAt,
		&i.MfaMethod,
		&i.LoginDisabled,
	)
	return i, err
}

const upsertPreferences = `-- name: UpsertPreferences :one
UPDATE users SET preferences = preferences || $1::jsonb WHERE id = $2
RETURNING preferences
`

type UpsertPreferencesParams struct {
	Column1 []byte
	ID      int32
}

func (q *Queries) UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, upsertPreferences, arg.Column1, arg.ID)
	var preferences []byte
	err := row.Scan(&preferences)
	return preferences, err
}
