// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: avisos.sql

package db

import (
	"context"
)

const getUserAvisos = `-- name: GetUserAvisos :one

SELECT email, aviso_email, aviso_telefone
FROM users WHERE id = $1
`

type GetUserAvisosRow struct {
	Email         string
	AvisoEmail    *string
	AvisoTelefone *string
}

// Contatos de aviso da conta (avisos.go).
func (q *Queries) GetUserAvisos(ctx context.Context, id int32) (GetUserAvisosRow, error) {
	row := q.db.QueryRow(ctx, getUserAvisos, id)
	var i GetUserAvisosRow
	err := row.Scan(&i.Email, &i.AvisoEmail, &i.AvisoTelefone)
	return i, err
}

const updateUserAvisos = `-- name: UpdateUserAvisos :one
UPDATE users SET
  aviso_email    = CASE WHEN $1::bool    THEN $2::text    ELSE aviso_email END,
  aviso_telefone = CASE WHEN $3::bool THEN $4::text ELSE aviso_telefone END,
  updated_at     = now()
WHERE id = $5
RETURNING email, aviso_email, aviso_telefone
`

type UpdateUserAvisosParams struct {
	SetEmail      bool
	AvisoEmail    *string
	SetTelefone   bool
	AvisoTelefone *string
	ID            int32
}

type UpdateUserAvisosRow struct {
	Email         string
	AvisoEmail    *string
	AvisoTelefone *string
}

// set_* = false preserva a coluna; true grava o valor (NULL volta ao padrão).
func (q *Queries) UpdateUserAvisos(ctx context.Context, arg UpdateUserAvisosParams) (UpdateUserAvisosRow, error) {
	row := q.db.QueryRow(ctx, updateUserAvisos,
		arg.SetEmail,
		arg.AvisoEmail,
		arg.SetTelefone,
		arg.AvisoTelefone,
		arg.ID,
	)
	var i UpdateUserAvisosRow
	err := row.Scan(&i.Email, &i.AvisoEmail, &i.AvisoTelefone)
	return i, err
}
