// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards WHERE id = $1::uuid
`

func (q *Queries) DeleteBoard(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoard, dollar_1)
	return err
}

const deleteBoardMember = `-- name: DeleteBoardMember :exec
DELETE FROM board_members WHERE board_id = $1::uuid AND user_id = $2
`

type DeleteBoardMemberParams struct {
	Column1 pgtype.UUID
	UserID  int32
}

func (q *Queries) DeleteBoardMember(ctx context.Context, arg DeleteBoardMemberParams) error {
	_, err := q.db.Exec(ctx, deleteBoardMember, arg.Column1, arg.UserID)
	return err
}

const getBoardForUser = `-- name: GetBoardForUser :one
SELECT b.id::text, b.owner_id, u.name, b.title,
  CASE WHEN b.owner_id = $2 THEN 'owner' ELSE m.role END,
  EXISTS (SELECT 1 FROM board_members WHERE board_id = b.id),
  b.scene_version, b.created_at, b.updated_at, b.scene
FROM boards b
JOIN users u ON u.id = b.owner_id
LEFT JOIN board_members m ON m.board_id = b.id AND m.user_id = $2
WHERE b.id = $1::uuid AND (b.owner_id = $2 OR m.user_id IS NOT NULL)
`

type GetBoardForUserParams struct {
	Column1 pgtype.UUID
	OwnerID int32
}

type GetBoardForUserRow struct {
	BID          string
	OwnerID      int32
	Name         string
	Title        string
	Column5      interface{}
	Exists       bool
	SceneVersion int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Scene        []byte
}

func (q *Queries) GetBoardForUser(ctx context.Context, arg GetBoardForUserParams) (GetBoardForUserRow, error) {
	row := q.db.QueryRow(ctx, getBoardForUser, arg.Column1, arg.OwnerID)
	var i GetBoardForUserRow
	err := row.Scan(
		&i.BID,
		&i.OwnerID,
		&i.Name,
		&i.Title,
		&i.Column5,
		&i.Exists,
		&i.SceneVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scene,
	)
	return i, err
}

const getBoardRoleForUser = `-- name: GetBoardRoleForUser :one
SELECT CASE WHEN b.owner_id = $2 THEN 'owner' ELSE m.role END
FROM boards b
LEFT JOIN board_members m ON m.board_id = b.id AND m.user_id = $2
WHERE b.id = $1::uuid AND (b.owner_id = $2 OR m.user_id IS NOT NULL)
`

type GetBoardRoleForUserParams struct {
	Column1 pgtype.UUID
	OwnerID int32
}

func (q *Queries) GetBoardRoleForUser(ctx context.Context, arg GetBoardRoleForUserParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getBoardRoleForUser, arg.Column1, arg.OwnerID)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const insertBoard = `-- name: InsertBoard :one
INSERT INTO boards (owner_id, title)
VALUES ($1, $2)
RETURNING id::text, owner_id, title, scene_version, created_at, updated_at
`

type InsertBoardParams struct {
	OwnerID int32
	Title   string
}

type InsertBoardRow struct {
	ID           string
	OwnerID      int32
	Title        string
	SceneVersion int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertBoard(ctx context.Context, arg InsertBoardParams) (InsertBoardRow, error) {
	row := q.db.QueryRow(ctx, insertBoard, arg.OwnerID, arg.Title)
	var i InsertBoardRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.SceneVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoardMembers = `-- name: ListBoardMembers :many
SELECT m.user_id, u.name, u.email, m.role, m.added_at
FROM board_members m JOIN users u ON u.id = m.user_id
WHERE m.board_id = $1::uuid
ORDER BY m.added_at
`

type ListBoardMembersRow struct {
	UserID  int32
	Name    string
	Email   string
	Role    string
	AddedAt pgtype.Timestamptz
}

func (q *Queries) ListBoardMembers(ctx context.Context, dollar_1 pgtype.UUID) ([]ListBoardMembersRow, error) {
	rows, err := q.db.Query(ctx, listBoardMembers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardMembersRow{}
	for rows.Next() {
		var i ListBoardMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardsForUser = `-- name: ListBoardsForUser :many

SELECT b.id::text, b.owner_id, u.name, b.title,
  CASE WHEN b.owner_id = $1 THEN 'owner' ELSE m.role END,
  EXISTS (SELECT 1 FROM board_members WHERE board_id = b.id),
  b.scene_version, b.created_at, b.updated_at
FROM boards b
JOIN users u ON u.id = b.owner_id
LEFT JOIN board_members m ON m.board_id = b.id AND m.user_id = $1
WHERE b.owner_id = $1 OR m.user_id IS NOT NULL
ORDER BY b.updated_at DESC
`

type ListBoardsForUserRow struct {
	BID          string
	OwnerID      int32
	Name         string
	Title        string
	Column5      interface{}
	Exists       bool
	SceneVersion int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Queries de Boards (quadros Excalidraw)
func (q *Queries) ListBoardsForUser(ctx context.Context, ownerID int32) ([]ListBoardsForUserRow, error) {
	rows, err := q.db.Query(ctx, listBoardsForUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardsForUserRow{}
	for rows.Next() {
		var i ListBoardsForUserRow
		if err := rows.Scan(
			&i.BID,
			&i.OwnerID,
			&i.Name,
			&i.Title,
			&i.Column5,
			&i.Exists,
			&i.SceneVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoardScene = `-- name: UpdateBoardScene :one
UPDATE boards SET
  scene         = $2::jsonb,
  scene_version = scene_version + 1,
  title         = COALESCE($4, title),
  updated_at    = now()
WHERE id = $1::uuid AND scene_version = $3
RETURNING scene_version
`

type UpdateBoardSceneParams struct {
	Column1      pgtype.UUID
	Column2      []byte
	SceneVersion int32
	Title        string
}

func (q *Queries) UpdateBoardScene(ctx context.Context, arg UpdateBoardSceneParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateBoardScene,
		arg.Column1,
		arg.Column2,
		arg.SceneVersion,
		arg.Title,
	)
	var scene_version int32
	err := row.Scan(&scene_version)
	return scene_version, err
}

const updateBoardTitle = `-- name: UpdateBoardTitle :one
UPDATE boards SET title = $2, updated_at = now()
WHERE id = $1::uuid
RETURNING scene_version
`

type UpdateBoardTitleParams struct {
	Column1 pgtype.UUID
	Title   string
}

func (q *Queries) UpdateBoardTitle(ctx context.Context, arg UpdateBoardTitleParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateBoardTitle, arg.Column1, arg.Title)
	var scene_version int32
	err := row.Scan(&scene_version)
	return scene_version, err
}

const upsertBoardMember = `-- name: UpsertBoardMember :exec
INSERT INTO board_members (board_id, user_id, role)
VALUES ($1::uuid, $2, $3)
ON CONFLICT (board_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertBoardMemberParams struct {
	Column1 pgtype.UUID
	UserID  int32
	Role    string
}

func (q *Queries) UpsertBoardMember(ctx context.Context, arg UpsertBoardMemberParams) error {
	_, err := q.db.Exec(ctx, upsertBoardMember, arg.Column1, arg.UserID, arg.Role)
	return err
}
