// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downloads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDownload = `-- name: CreateDownload :one

INSERT INTO downloads (name, description, category, version, kind, object_key, external_url, filename, content_type, size_bytes, uploaded_by, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, description, category, version, kind, object_key, external_url, filename, content_type, size_bytes, pinned, uploaded_by, created_at, updated_at, image_url
`

type CreateDownloadParams struct {
	Name        string
	Description string
	Category    string
	Version     string
	Kind        string
	ObjectKey   pgtype.Text
	ExternalUrl pgtype.Text
	Filename    string
	ContentType string
	SizeBytes   pgtype.Int8
	UploadedBy  pgtype.Int4
	ImageUrl    pgtype.Text
}

// Queries do catálogo de downloads (Santos Hub — app Tauri dos PCs da empresa)
func (q *Queries) CreateDownload(ctx context.Context, arg CreateDownloadParams) (Download, error) {
	row := q.db.QueryRow(ctx, createDownload,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Version,
		arg.Kind,
		arg.ObjectKey,
		arg.ExternalUrl,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.UploadedBy,
		arg.ImageUrl,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Version,
		&i.Kind,
		&i.ObjectKey,
		&i.ExternalUrl,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Pinned,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const deleteDownload = `-- name: DeleteDownload :execrows
DELETE FROM downloads WHERE id = $1
`

func (q *Queries) DeleteDownload(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDownload, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDownload = `-- name: GetDownload :one
SELECT id, name, description, category, version, kind, object_key, external_url, filename, content_type, size_bytes, pinned, uploaded_by, created_at, updated_at, image_url
FROM downloads WHERE id = $1
`

func (q *Queries) GetDownload(ctx context.Context, id int64) (Download, error) {
	row := q.db.QueryRow(ctx, getDownload, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Version,
		&i.Kind,
		&i.ObjectKey,
		&i.ExternalUrl,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Pinned,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const listDownloads = `-- name: ListDownloads :many
SELECT id, name, description, category, version, kind, object_key, external_url, filename, content_type, size_bytes, pinned, uploaded_by, created_at, updated_at, image_url
FROM downloads
ORDER BY pinned DESC, created_at DESC
`

func (q *Queries) ListDownloads(ctx context.Context) ([]Download, error) {
	rows, err := q.db.Query(ctx, listDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Version,
			&i.Kind,
			&i.ObjectKey,
			&i.ExternalUrl,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Pinned,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownload = `-- name: UpdateDownload :one
UPDATE downloads
SET name = $2, description = $3, category = $4, version = $5, pinned = $6, image_url = $7, updated_at = now()
WHERE id = $1
RETURNING id, name, description, category, version, kind, object_key, external_url, filename, content_type, size_bytes, pinned, uploaded_by, created_at, updated_at, image_url
`

type UpdateDownloadParams struct {
	ID          int64
	Name        string
	Description string
	Category    string
	Version     string
	Pinned      bool
	ImageUrl    pgtype.Text
}

func (q *Queries) UpdateDownload(ctx context.Context, arg UpdateDownloadParams) (Download, error) {
	row := q.db.QueryRow(ctx, updateDownload,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Version,
		arg.Pinned,
		arg.ImageUrl,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Version,
		&i.Kind,
		&i.ObjectKey,
		&i.ExternalUrl,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Pinned,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}
