// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ip_bans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteIPBan = `-- name: DeleteIPBan :execrows
DELETE FROM ip_bans WHERE id = $1
`

func (q *Queries) DeleteIPBan(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIPBan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIPBan = `-- name: GetIPBan :one
SELECT id, ip, reason, banned_by, expires_at, created_at
FROM ip_bans WHERE id = $1
`

func (q *Queries) GetIPBan(ctx context.Context, id int64) (IpBan, error) {
	row := q.db.QueryRow(ctx, getIPBan, id)
	var i IpBan
	err := row.Scan(
		&i.ID,
		&i.Ip,
		&i.Reason,
		&i.BannedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveBans = `-- name: ListActiveBans :many
SELECT id, ip, reason, banned_by, expires_at, created_at
FROM ip_bans
WHERE expires_at IS NULL OR expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveBans(ctx context.Context) ([]IpBan, error) {
	rows, err := q.db.Query(ctx, listActiveBans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IpBan{}
	for rows.Next() {
		var i IpBan
		if err := rows.Scan(
			&i.ID,
			&i.Ip,
			&i.Reason,
			&i.BannedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIPBan = `-- name: UpsertIPBan :one

INSERT INTO ip_bans (ip, reason, banned_by, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (ip) DO UPDATE
SET reason     = EXCLUDED.reason,
    banned_by  = EXCLUDED.banned_by,
    expires_at = EXCLUDED.expires_at,
    created_at = now()
RETURNING id, ip, reason, banned_by, expires_at, created_at
`

type UpsertIPBanParams struct {
	Ip        string
	Reason    *string
	BannedBy  pgtype.Int4
	ExpiresAt pgtype.Timestamptz
}

// Queries de IP Bans (admin CRUD)
func (q *Queries) UpsertIPBan(ctx context.Context, arg UpsertIPBanParams) (IpBan, error) {
	row := q.db.QueryRow(ctx, upsertIPBan,
		arg.Ip,
		arg.Reason,
		arg.BannedBy,
		arg.ExpiresAt,
	)
	var i IpBan
	err := row.Scan(
		&i.ID,
		&i.Ip,
		&i.Reason,
		&i.BannedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
