// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lab_commands.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextLabDeviceCommand = `-- name: ClaimNextLabDeviceCommand :one
UPDATE hour_lab_device_commands c SET delivered_at = now()
WHERE c.id = (
  SELECT q.id FROM hour_lab_device_commands q
  JOIN hour_lab_devices d ON d.id = q.device_id
  WHERE d.device_uuid = $1 AND q.kind = 'command' AND q.delivered_at IS NULL
  ORDER BY q.created_at
  LIMIT 1
  FOR UPDATE OF q SKIP LOCKED
)
RETURNING c.id::text, c.text
`

type ClaimNextLabDeviceCommandRow struct {
	CID  string
	Text string
}

func (q *Queries) ClaimNextLabDeviceCommand(ctx context.Context, deviceUuid string) (ClaimNextLabDeviceCommandRow, error) {
	row := q.db.QueryRow(ctx, claimNextLabDeviceCommand, deviceUuid)
	var i ClaimNextLabDeviceCommandRow
	err := row.Scan(&i.CID, &i.Text)
	return i, err
}

const enqueueLabDeviceCommand = `-- name: EnqueueLabDeviceCommand :one

INSERT INTO hour_lab_device_commands (device_id, user_id, source, kind, text)
VALUES ($1::uuid, $2, $3, 'command', $4)
RETURNING id::text
`

type EnqueueLabDeviceCommandParams struct {
	DeviceID pgtype.UUID
	UserID   pgtype.Int4
	Source   string
	Text     string
}

// Fila/auditoria de ações remotas nos PCs do laboratório.
func (q *Queries) EnqueueLabDeviceCommand(ctx context.Context, arg EnqueueLabDeviceCommandParams) (string, error) {
	row := q.db.QueryRow(ctx, enqueueLabDeviceCommand,
		arg.DeviceID,
		arg.UserID,
		arg.Source,
		arg.Text,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getLabDeviceCommand = `-- name: GetLabDeviceCommand :one
SELECT c.id::text, c.kind, c.source, c.text, c.result, c.user_id,
       COALESCE(u.name, '')::text AS user_name, c.created_at, c.delivered_at, c.result_at
FROM hour_lab_device_commands c LEFT JOIN users u ON u.id = c.user_id
WHERE c.device_id = $1::uuid AND c.id = $2::uuid
`

type GetLabDeviceCommandParams struct {
	DeviceID pgtype.UUID
	ID       pgtype.UUID
}

type GetLabDeviceCommandRow struct {
	CID         string
	Kind        string
	Source      string
	Text        string
	Result      *string
	UserID      pgtype.Int4
	UserName    string
	CreatedAt   pgtype.Timestamptz
	DeliveredAt pgtype.Timestamptz
	ResultAt    pgtype.Timestamptz
}

func (q *Queries) GetLabDeviceCommand(ctx context.Context, arg GetLabDeviceCommandParams) (GetLabDeviceCommandRow, error) {
	row := q.db.QueryRow(ctx, getLabDeviceCommand, arg.DeviceID, arg.ID)
	var i GetLabDeviceCommandRow
	err := row.Scan(
		&i.CID,
		&i.Kind,
		&i.Source,
		&i.Text,
		&i.Result,
		&i.UserID,
		&i.UserName,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.ResultAt,
	)
	return i, err
}

const insertLabDeviceAudit = `-- name: InsertLabDeviceAudit :exec
INSERT INTO hour_lab_device_commands (device_id, user_id, source, kind, text, delivered_at)
VALUES ($1::uuid, $2, $3, $4, $5, now())
`

type InsertLabDeviceAuditParams struct {
	DeviceID pgtype.UUID
	UserID   pgtype.Int4
	Source   string
	Kind     string
	Text     string
}

func (q *Queries) InsertLabDeviceAudit(ctx context.Context, arg InsertLabDeviceAuditParams) error {
	_, err := q.db.Exec(ctx, insertLabDeviceAudit,
		arg.DeviceID,
		arg.UserID,
		arg.Source,
		arg.Kind,
		arg.Text,
	)
	return err
}

const listLabDeviceCommands = `-- name: ListLabDeviceCommands :many
SELECT c.id::text, c.kind, c.source, c.text, c.result, c.user_id,
       COALESCE(u.name, '')::text AS user_name, c.created_at, c.delivered_at, c.result_at
FROM hour_lab_device_commands c LEFT JOIN users u ON u.id = c.user_id
WHERE c.device_id = $1::uuid
ORDER BY c.created_at DESC
LIMIT $2
`

type ListLabDeviceCommandsParams struct {
	DeviceID pgtype.UUID
	Lim      int32
}

type ListLabDeviceCommandsRow struct {
	CID         string
	Kind        string
	Source      string
	Text        string
	Result      *string
	UserID      pgtype.Int4
	UserName    string
	CreatedAt   pgtype.Timestamptz
	DeliveredAt pgtype.Timestamptz
	ResultAt    pgtype.Timestamptz
}

func (q *Queries) ListLabDeviceCommands(ctx context.Context, arg ListLabDeviceCommandsParams) ([]ListLabDeviceCommandsRow, error) {
	rows, err := q.db.Query(ctx, listLabDeviceCommands, arg.DeviceID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabDeviceCommandsRow{}
	for rows.Next() {
		var i ListLabDeviceCommandsRow
		if err := rows.Scan(
			&i.CID,
			&i.Kind,
			&i.Source,
			&i.Text,
			&i.Result,
			&i.UserID,
			&i.UserName,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.ResultAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mirrorLabDeviceLegacyCommand = `-- name: MirrorLabDeviceLegacyCommand :exec
UPDATE hour_lab_devices
SET command_id = $1::uuid, command_text = $2, command_sent_at = now(),
    command_result = NULL, command_result_at = NULL
WHERE id = $3::uuid
`

type MirrorLabDeviceLegacyCommandParams struct {
	CommandID pgtype.UUID
	Text      *string
	DeviceID  pgtype.UUID
}

// Espelho nas colunas antigas até o front migrar pro /commands (Plano 2).
func (q *Queries) MirrorLabDeviceLegacyCommand(ctx context.Context, arg MirrorLabDeviceLegacyCommandParams) error {
	_, err := q.db.Exec(ctx, mirrorLabDeviceLegacyCommand, arg.CommandID, arg.Text, arg.DeviceID)
	return err
}

const storeLabDeviceCommandQueueResult = `-- name: StoreLabDeviceCommandQueueResult :execrows
UPDATE hour_lab_device_commands c SET result = $1, result_at = now()
FROM hour_lab_devices d
WHERE d.id = c.device_id AND d.device_uuid = $2
  AND c.id = $3::uuid AND c.result_at IS NULL
`

type StoreLabDeviceCommandQueueResultParams struct {
	Result     *string
	DeviceUuid string
	CommandID  pgtype.UUID
}

func (q *Queries) StoreLabDeviceCommandQueueResult(ctx context.Context, arg StoreLabDeviceCommandQueueResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, storeLabDeviceCommandQueueResult, arg.Result, arg.DeviceUuid, arg.CommandID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
