// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa.sql

package db

import (
	"context"
)

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :execrows
UPDATE recovery_codes SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type ConsumeRecoveryCodeParams struct {
	UserID   int32
	CodeHash string
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRecoveryCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const insertRecoveryCodes = `-- name: InsertRecoveryCodes :exec

INSERT INTO recovery_codes (user_id, code_hash)
SELECT $1, unnest($2::text[])
`

type InsertRecoveryCodesParams struct {
	UserID  int32
	Column2 []string
}

// Queries de MFA: recovery codes
func (q *Queries) InsertRecoveryCodes(ctx context.Context, arg InsertRecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCodes, arg.UserID, arg.Column2)
	return err
}
