// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model3d.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModel3DFile = `-- name: CreateModel3DFile :one

INSERT INTO model3d_file (filename, object_key, ext, content_type, size_bytes, uploaded_by, folder)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, filename, object_key, ext, content_type, size_bytes, uploaded_by, created_at, folder, pinned
`

type CreateModel3DFileParams struct {
	Filename    string
	ObjectKey   string
	Ext         string
	ContentType string
	SizeBytes   int64
	UploadedBy  pgtype.Int4
	Folder      string
}

// Queries de modelos 3D (biblioteca admin-only no dashboard)
func (q *Queries) CreateModel3DFile(ctx context.Context, arg CreateModel3DFileParams) (Model3dFile, error) {
	row := q.db.QueryRow(ctx, createModel3DFile,
		arg.Filename,
		arg.ObjectKey,
		arg.Ext,
		arg.ContentType,
		arg.SizeBytes,
		arg.UploadedBy,
		arg.Folder,
	)
	var i Model3dFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ObjectKey,
		&i.Ext,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.Folder,
		&i.Pinned,
	)
	return i, err
}

const deleteModel3DFile = `-- name: DeleteModel3DFile :execrows
DELETE FROM model3d_file WHERE id = $1
`

func (q *Queries) DeleteModel3DFile(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteModel3DFile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getModel3DFile = `-- name: GetModel3DFile :one
SELECT id, filename, object_key, ext, content_type, size_bytes, uploaded_by, created_at, folder, pinned
FROM model3d_file WHERE id = $1
`

func (q *Queries) GetModel3DFile(ctx context.Context, id int64) (Model3dFile, error) {
	row := q.db.QueryRow(ctx, getModel3DFile, id)
	var i Model3dFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ObjectKey,
		&i.Ext,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.Folder,
		&i.Pinned,
	)
	return i, err
}

const listModel3DFiles = `-- name: ListModel3DFiles :many
SELECT id, filename, object_key, ext, content_type, size_bytes, uploaded_by, created_at, folder, pinned
FROM model3d_file
ORDER BY pinned DESC, created_at DESC
`

func (q *Queries) ListModel3DFiles(ctx context.Context) ([]Model3dFile, error) {
	rows, err := q.db.Query(ctx, listModel3DFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model3dFile{}
	for rows.Next() {
		var i Model3dFile
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.ObjectKey,
			&i.Ext,
			&i.ContentType,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.Folder,
			&i.Pinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModel3DFile = `-- name: UpdateModel3DFile :one
UPDATE model3d_file
SET filename = $2, folder = $3, pinned = $4
WHERE id = $1
RETURNING id, filename, object_key, ext, content_type, size_bytes, uploaded_by, created_at, folder, pinned
`

type UpdateModel3DFileParams struct {
	ID       int64
	Filename string
	Folder   string
	Pinned   bool
}

func (q *Queries) UpdateModel3DFile(ctx context.Context, arg UpdateModel3DFileParams) (Model3dFile, error) {
	row := q.db.QueryRow(ctx, updateModel3DFile,
		arg.ID,
		arg.Filename,
		arg.Folder,
		arg.Pinned,
	)
	var i Model3dFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ObjectKey,
		&i.Ext,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.Folder,
		&i.Pinned,
	)
	return i, err
}
