// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         int64
	UserID     int32
	Name       string
	KeyPrefix  string
	KeyHash    string
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Board struct {
	ID           pgtype.UUID
	OwnerID      int32
	Title        string
	Scene        []byte
	SceneVersion int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type BoardMember struct {
	BoardID pgtype.UUID
	UserID  int32
	Role    string
	AddedAt pgtype.Timestamptz
}

type CustomRole struct {
	ID          pgtype.UUID
	Name        string
	Description *string
	Permissions []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type OauthAccount struct {
	ID         int32
	UserID     int32
	Provider   string
	ProviderID string
	CreatedAt  pgtype.Timestamptz
}

type OauthClient struct {
	ID           pgtype.UUID
	ClientID     string
	Name         string
	RedirectUris []string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

type RecoveryCode struct {
	ID        int64
	UserID    int32
	CodeHash  string
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID               pgtype.UUID
	UserID           int32
	RefreshTokenHash string
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
}

type SocialPost struct {
	ID                 pgtype.UUID
	Title              string
	Caption            string
	Platform           string
	Pilar              string
	Status             string
	ScheduledAt        pgtype.Timestamptz
	MediaUrl           string
	ReferenceUrl       string
	Formato            string
	Objetivo           string
	Programa           string
	Receita            string
	PlataformasDestino []string
	CopyArte           []byte
	Hashtags           []string
	ConceitoVisual     string
	Paleta             []byte
	PromptIa           string
	Specs              []byte
	MasterUrl          string
	Mandatorios        string
	CreatedBy          pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type SocialPostNote struct {
	ID        int64
	PostID    pgtype.UUID
	AuthorID  pgtype.Int4
	Content   string
	CreatedAt pgtype.Timestamptz
}

type SocialPostStatusHistory struct {
	ID        int64
	PostID    pgtype.UUID
	ChangedBy pgtype.Int8
	OldStatus string
	NewStatus string
	ChangedAt pgtype.Timestamptz
}

type User struct {
	ID              int32
	Email           string
	Username        *string
	Name            string
	PasswordHash    *string
	AvatarUrl       *string
	Role            int16
	CustomRoleID    pgtype.UUID
	SuspendedAt     pgtype.Timestamptz
	MfaEnabled      bool
	TotpSecret      *string
	Preferences     []byte
	QuotaBytes      int64
	EmailVerifiedAt pgtype.Timestamptz
	MfaMethod       string
	LoginDisabled   bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
