// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOAuthClient = `-- name: DeleteOAuthClient :execrows
DELETE FROM oauth_clients WHERE id = $1::uuid
`

func (q *Queries) DeleteOAuthClient(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOAuthClient, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOAuthClientByClientID = `-- name: GetOAuthClientByClientID :one

SELECT id::text, client_id, name, redirect_uris, is_active, created_at
FROM oauth_clients WHERE client_id = $1
`

type GetOAuthClientByClientIDRow struct {
	ID           string
	ClientID     string
	Name         string
	RedirectUris []string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

// Queries de OAuth Clients (aplicações "Entrar com Santos Tech")
func (q *Queries) GetOAuthClientByClientID(ctx context.Context, clientID string) (GetOAuthClientByClientIDRow, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByClientID, clientID)
	var i GetOAuthClientByClientIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.RedirectUris,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertOAuthClient = `-- name: InsertOAuthClient :one
INSERT INTO oauth_clients (client_id, name, redirect_uris)
VALUES ($1, $2, $3)
RETURNING id::text, client_id, name, redirect_uris, is_active, created_at
`

type InsertOAuthClientParams struct {
	ClientID     string
	Name         string
	RedirectUris []string
}

type InsertOAuthClientRow struct {
	ID           string
	ClientID     string
	Name         string
	RedirectUris []string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertOAuthClient(ctx context.Context, arg InsertOAuthClientParams) (InsertOAuthClientRow, error) {
	row := q.db.QueryRow(ctx, insertOAuthClient, arg.ClientID, arg.Name, arg.RedirectUris)
	var i InsertOAuthClientRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.RedirectUris,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthClients = `-- name: ListOAuthClients :many
SELECT id::text, client_id, name, redirect_uris, is_active, created_at
FROM oauth_clients ORDER BY created_at DESC
`

type ListOAuthClientsRow struct {
	ID           string
	ClientID     string
	Name         string
	RedirectUris []string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListOAuthClients(ctx context.Context) ([]ListOAuthClientsRow, error) {
	rows, err := q.db.Query(ctx, listOAuthClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOAuthClientsRow{}
	for rows.Next() {
		var i ListOAuthClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.RedirectUris,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOAuthClient = `-- name: UpdateOAuthClient :one
UPDATE oauth_clients SET
  name          = COALESCE($2, name),
  redirect_uris = COALESCE($3, redirect_uris),
  is_active     = COALESCE($4, is_active)
WHERE id = $1::uuid
RETURNING id::text, client_id, name, redirect_uris, is_active, created_at
`

type UpdateOAuthClientParams struct {
	Column1      pgtype.UUID
	Name         string
	RedirectUris []string
	IsActive     bool
}

type UpdateOAuthClientRow struct {
	ID           string
	ClientID     string
	Name         string
	RedirectUris []string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateOAuthClient(ctx context.Context, arg UpdateOAuthClientParams) (UpdateOAuthClientRow, error) {
	row := q.db.QueryRow(ctx, updateOAuthClient,
		arg.Column1,
		arg.Name,
		arg.RedirectUris,
		arg.IsActive,
	)
	var i UpdateOAuthClientRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.RedirectUris,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
