// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_subscriptions.sql

package db

import (
	"context"
)

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :execrows
DELETE FROM push_subscriptions WHERE endpoint = $1 AND user_id = $2
`

type DeletePushSubscriptionByEndpointParams struct {
	Endpoint string
	UserID   int32
}

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, arg DeletePushSubscriptionByEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, arg.Endpoint, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPushSubscriptionsByUser = `-- name: ListPushSubscriptionsByUser :many
SELECT id, user_id, endpoint, p256dh, auth, user_agent, created_at
FROM push_subscriptions WHERE user_id = $1
`

func (q *Queries) ListPushSubscriptionsByUser(ctx context.Context, userID int32) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one

INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth, user_agent)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (endpoint) DO UPDATE
SET user_id    = EXCLUDED.user_id,
    p256dh     = EXCLUDED.p256dh,
    auth       = EXCLUDED.auth,
    user_agent = EXCLUDED.user_agent
RETURNING id, user_id, endpoint, p256dh, auth, user_agent, created_at
`

type UpsertPushSubscriptionParams struct {
	UserID    int32
	Endpoint  string
	P256dh    string
	Auth      string
	UserAgent *string
}

// Queries de Web Push (subscriptions de navegador por usuário)
func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserAgent,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}
