// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSocialPost = `-- name: DeleteSocialPost :execrows
DELETE FROM social_posts WHERE id = $1::uuid
`

func (q *Queries) DeleteSocialPost(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSocialPost, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSocialPost = `-- name: GetSocialPost :one
SELECT id::text, title, caption, platform, pilar, status,
  scheduled_at, media_url, reference_url,
  formato, objetivo, programa, receita, plataformas_destino, copy_arte, hashtags,
  conceito_visual, paleta, prompt_ia, specs, master_url, mandatorios,
  created_by, created_at, updated_at
FROM social_posts WHERE id = $1::uuid
`

type GetSocialPostRow struct {
	ID                 string
	Title              string
	Caption            string
	Platform           string
	Pilar              string
	Status             string
	ScheduledAt        pgtype.Timestamptz
	MediaUrl           string
	ReferenceUrl       string
	Formato            string
	Objetivo           string
	Programa           string
	Receita            string
	PlataformasDestino []string
	CopyArte           []byte
	Hashtags           []string
	ConceitoVisual     string
	Paleta             []byte
	PromptIa           string
	Specs              []byte
	MasterUrl          string
	Mandatorios        string
	CreatedBy          pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) GetSocialPost(ctx context.Context, dollar_1 pgtype.UUID) (GetSocialPostRow, error) {
	row := q.db.QueryRow(ctx, getSocialPost, dollar_1)
	var i GetSocialPostRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Caption,
		&i.Platform,
		&i.Pilar,
		&i.Status,
		&i.ScheduledAt,
		&i.MediaUrl,
		&i.ReferenceUrl,
		&i.Formato,
		&i.Objetivo,
		&i.Programa,
		&i.Receita,
		&i.PlataformasDestino,
		&i.CopyArte,
		&i.Hashtags,
		&i.ConceitoVisual,
		&i.Paleta,
		&i.PromptIa,
		&i.Specs,
		&i.MasterUrl,
		&i.Mandatorios,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSocialPost = `-- name: InsertSocialPost :one
INSERT INTO social_posts (
  title, caption, platform, pilar, status, scheduled_at, media_url, reference_url,
  formato, objetivo, programa, receita, plataformas_destino, copy_arte, hashtags,
  conceito_visual, paleta, prompt_ia, specs, master_url, mandatorios, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
RETURNING id::text, title, caption, platform, pilar, status,
  scheduled_at, media_url, reference_url,
  formato, objetivo, programa, receita, plataformas_destino, copy_arte, hashtags,
  conceito_visual, paleta, prompt_ia, specs, master_url, mandatorios,
  created_by, created_at, updated_at
`

type InsertSocialPostParams struct {
	Title              string
	Caption            string
	Platform           string
	Pilar              string
	Status             string
	ScheduledAt        pgtype.Timestamptz
	MediaUrl           string
	ReferenceUrl       string
	Formato            string
	Objetivo           string
	Programa           string
	Receita            string
	PlataformasDestino []string
	CopyArte           []byte
	Hashtags           []string
	ConceitoVisual     string
	Paleta             []byte
	PromptIa           string
	Specs              []byte
	MasterUrl          string
	Mandatorios        string
	CreatedBy          pgtype.Int4
}

type InsertSocialPostRow struct {
	ID                 string
	Title              string
	Caption            string
	Platform           string
	Pilar              string
	Status             string
	ScheduledAt        pgtype.Timestamptz
	MediaUrl           string
	ReferenceUrl       string
	Formato            string
	Objetivo           string
	Programa           string
	Receita            string
	PlataformasDestino []string
	CopyArte           []byte
	Hashtags           []string
	ConceitoVisual     string
	Paleta             []byte
	PromptIa           string
	Specs              []byte
	MasterUrl          string
	Mandatorios        string
	CreatedBy          pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) InsertSocialPost(ctx context.Context, arg InsertSocialPostParams) (InsertSocialPostRow, error) {
	row := q.db.QueryRow(ctx, insertSocialPost,
		arg.Title,
		arg.Caption,
		arg.Platform,
		arg.Pilar,
		arg.Status,
		arg.ScheduledAt,
		arg.MediaUrl,
		arg.ReferenceUrl,
		arg.Formato,
		arg.Objetivo,
		arg.Programa,
		arg.Receita,
		arg.PlataformasDestino,
		arg.CopyArte,
		arg.Hashtags,
		arg.ConceitoVisual,
		arg.Paleta,
		arg.PromptIa,
		arg.Specs,
		arg.MasterUrl,
		arg.Mandatorios,
		arg.CreatedBy,
	)
	var i InsertSocialPostRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Caption,
		&i.Platform,
		&i.Pilar,
		&i.Status,
		&i.ScheduledAt,
		&i.MediaUrl,
		&i.ReferenceUrl,
		&i.Formato,
		&i.Objetivo,
		&i.Programa,
		&i.Receita,
		&i.PlataformasDestino,
		&i.CopyArte,
		&i.Hashtags,
		&i.ConceitoVisual,
		&i.Paleta,
		&i.PromptIa,
		&i.Specs,
		&i.MasterUrl,
		&i.Mandatorios,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSocialPostNote = `-- name: InsertSocialPostNote :one
INSERT INTO social_post_notes (post_id, author_id, content)
VALUES ($1::uuid, $2, $3)
RETURNING id, post_id::text, author_id,
  (SELECT COALESCE(name, '') FROM users WHERE id = author_id),
  content, created_at
`

type InsertSocialPostNoteParams struct {
	Column1  pgtype.UUID
	AuthorID pgtype.Int4
	Content  string
}

type InsertSocialPostNoteRow struct {
	ID        int64
	PostID    string
	AuthorID  pgtype.Int4
	Name      string
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertSocialPostNote(ctx context.Context, arg InsertSocialPostNoteParams) (InsertSocialPostNoteRow, error) {
	row := q.db.QueryRow(ctx, insertSocialPostNote, arg.Column1, arg.AuthorID, arg.Content)
	var i InsertSocialPostNoteRow
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const insertSocialPostStatusHistory = `-- name: InsertSocialPostStatusHistory :exec
INSERT INTO social_post_status_history (post_id, changed_by, old_status, new_status)
VALUES ($1::uuid, $2, $3, $4)
`

type InsertSocialPostStatusHistoryParams struct {
	Column1   pgtype.UUID
	ChangedBy pgtype.Int8
	OldStatus string
	NewStatus string
}

func (q *Queries) InsertSocialPostStatusHistory(ctx context.Context, arg InsertSocialPostStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, insertSocialPostStatusHistory,
		arg.Column1,
		arg.ChangedBy,
		arg.OldStatus,
		arg.NewStatus,
	)
	return err
}

const listSocialPostNotes = `-- name: ListSocialPostNotes :many
SELECT n.id, n.post_id::text, n.author_id, COALESCE(u.name, ''), n.content, n.created_at
FROM social_post_notes n
LEFT JOIN users u ON u.id = n.author_id
WHERE n.post_id = $1::uuid
ORDER BY n.created_at
`

type ListSocialPostNotesRow struct {
	ID        int64
	NPostID   string
	AuthorID  pgtype.Int4
	Name      string
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListSocialPostNotes(ctx context.Context, dollar_1 pgtype.UUID) ([]ListSocialPostNotesRow, error) {
	rows, err := q.db.Query(ctx, listSocialPostNotes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSocialPostNotesRow{}
	for rows.Next() {
		var i ListSocialPostNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.NPostID,
			&i.AuthorID,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialPostStatusHistory = `-- name: ListSocialPostStatusHistory :many
SELECT h.id, h.post_id::text, h.changed_by, COALESCE(u.name, ''), h.old_status, h.new_status, h.changed_at
FROM social_post_status_history h
LEFT JOIN users u ON u.id = h.changed_by
WHERE h.post_id = $1::uuid
ORDER BY h.changed_at DESC
`

type ListSocialPostStatusHistoryRow struct {
	ID        int64
	HPostID   string
	ChangedBy pgtype.Int8
	Name      string
	OldStatus string
	NewStatus string
	ChangedAt pgtype.Timestamptz
}

func (q *Queries) ListSocialPostStatusHistory(ctx context.Context, dollar_1 pgtype.UUID) ([]ListSocialPostStatusHistoryRow, error) {
	rows, err := q.db.Query(ctx, listSocialPostStatusHistory, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSocialPostStatusHistoryRow{}
	for rows.Next() {
		var i ListSocialPostStatusHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.HPostID,
			&i.ChangedBy,
			&i.Name,
			&i.OldStatus,
			&i.NewStatus,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialPosts = `-- name: ListSocialPosts :many

SELECT id::text, title, caption, platform, pilar, status,
  scheduled_at, media_url, reference_url,
  formato, objetivo, programa, receita, plataformas_destino, copy_arte, hashtags,
  conceito_visual, paleta, prompt_ia, specs, master_url, mandatorios,
  created_by, created_at, updated_at
FROM social_posts
ORDER BY COALESCE(scheduled_at, created_at) DESC
`

type ListSocialPostsRow struct {
	ID                 string
	Title              string
	Caption            string
	Platform           string
	Pilar              string
	Status             string
	ScheduledAt        pgtype.Timestamptz
	MediaUrl           string
	ReferenceUrl       string
	Formato            string
	Objetivo           string
	Programa           string
	Receita            string
	PlataformasDestino []string
	CopyArte           []byte
	Hashtags           []string
	ConceitoVisual     string
	Paleta             []byte
	PromptIa           string
	Specs              []byte
	MasterUrl          string
	Mandatorios        string
	CreatedBy          pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// Queries de Social Posts
func (q *Queries) ListSocialPosts(ctx context.Context) ([]ListSocialPostsRow, error) {
	rows, err := q.db.Query(ctx, listSocialPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSocialPostsRow{}
	for rows.Next() {
		var i ListSocialPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Caption,
			&i.Platform,
			&i.Pilar,
			&i.Status,
			&i.ScheduledAt,
			&i.MediaUrl,
			&i.ReferenceUrl,
			&i.Formato,
			&i.Objetivo,
			&i.Programa,
			&i.Receita,
			&i.PlataformasDestino,
			&i.CopyArte,
			&i.Hashtags,
			&i.ConceitoVisual,
			&i.Paleta,
			&i.PromptIa,
			&i.Specs,
			&i.MasterUrl,
			&i.Mandatorios,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSocialPost = `-- name: UpdateSocialPost :one
UPDATE social_posts SET
  title = $2, caption = $3, platform = $4, pilar = $5, status = $6,
  scheduled_at = $7, media_url = $8, reference_url = $9,
  formato = $10, objetivo = $11, programa = $12, receita = $13,
  plataformas_destino = $14, copy_arte = $15, hashtags = $16,
  conceito_visual = $17, paleta = $18, prompt_ia = $19, specs = $20,
  master_url = $21, mandatorios = $22, updated_at = now()
WHERE id = $1::uuid
RETURNING id::text, title, caption, platform, pilar, status,
  scheduled_at, media_url, reference_url,
  formato, objetivo, programa, receita, plataformas_destino, copy_arte, hashtags,
  conceito_visual, paleta, prompt_ia, specs, master_url, mandatorios,
  created_by, created_at, updated_at
`

type UpdateSocialPostParams struct {
	Column1            pgtype.UUID
	Title              string
	Caption            string
	Platform           string
	Pilar              string
	Status             string
	ScheduledAt        pgtype.Timestamptz
	MediaUrl           string
	ReferenceUrl       string
	Formato            string
	Objetivo           string
	Programa           string
	Receita            string
	PlataformasDestino []string
	CopyArte           []byte
	Hashtags           []string
	ConceitoVisual     string
	Paleta             []byte
	PromptIa           string
	Specs              []byte
	MasterUrl          string
	Mandatorios        string
}

type UpdateSocialPostRow struct {
	ID                 string
	Title              string
	Caption            string
	Platform           string
	Pilar              string
	Status             string
	ScheduledAt        pgtype.Timestamptz
	MediaUrl           string
	ReferenceUrl       string
	Formato            string
	Objetivo           string
	Programa           string
	Receita            string
	PlataformasDestino []string
	CopyArte           []byte
	Hashtags           []string
	ConceitoVisual     string
	Paleta             []byte
	PromptIa           string
	Specs              []byte
	MasterUrl          string
	Mandatorios        string
	CreatedBy          pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) UpdateSocialPost(ctx context.Context, arg UpdateSocialPostParams) (UpdateSocialPostRow, error) {
	row := q.db.QueryRow(ctx, updateSocialPost,
		arg.Column1,
		arg.Title,
		arg.Caption,
		arg.Platform,
		arg.Pilar,
		arg.Status,
		arg.ScheduledAt,
		arg.MediaUrl,
		arg.ReferenceUrl,
		arg.Formato,
		arg.Objetivo,
		arg.Programa,
		arg.Receita,
		arg.PlataformasDestino,
		arg.CopyArte,
		arg.Hashtags,
		arg.ConceitoVisual,
		arg.Paleta,
		arg.PromptIa,
		arg.Specs,
		arg.MasterUrl,
		arg.Mandatorios,
	)
	var i UpdateSocialPostRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Caption,
		&i.Platform,
		&i.Pilar,
		&i.Status,
		&i.ScheduledAt,
		&i.MediaUrl,
		&i.ReferenceUrl,
		&i.Formato,
		&i.Objetivo,
		&i.Programa,
		&i.Receita,
		&i.PlataformasDestino,
		&i.CopyArte,
		&i.Hashtags,
		&i.ConceitoVisual,
		&i.Paleta,
		&i.PromptIa,
		&i.Specs,
		&i.MasterUrl,
		&i.Mandatorios,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSocialPostStatus = `-- name: UpdateSocialPostStatus :one
UPDATE social_posts SET status = $2, updated_at = now()
WHERE id = $1::uuid
RETURNING id::text, title, caption, platform, pilar, status,
  scheduled_at, media_url, reference_url,
  formato, objetivo, programa, receita, plataformas_destino, copy_arte, hashtags,
  conceito_visual, paleta, prompt_ia, specs, master_url, mandatorios,
  created_by, created_at, updated_at
`

type UpdateSocialPostStatusParams struct {
	Column1 pgtype.UUID
	Status  string
}

type UpdateSocialPostStatusRow struct {
	ID                 string
	Title              string
	Caption            string
	Platform           string
	Pilar              string
	Status             string
	ScheduledAt        pgtype.Timestamptz
	MediaUrl           string
	ReferenceUrl       string
	Formato            string
	Objetivo           string
	Programa           string
	Receita            string
	PlataformasDestino []string
	CopyArte           []byte
	Hashtags           []string
	ConceitoVisual     string
	Paleta             []byte
	PromptIa           string
	Specs              []byte
	MasterUrl          string
	Mandatorios        string
	CreatedBy          pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) UpdateSocialPostStatus(ctx context.Context, arg UpdateSocialPostStatusParams) (UpdateSocialPostStatusRow, error) {
	row := q.db.QueryRow(ctx, updateSocialPostStatus, arg.Column1, arg.Status)
	var i UpdateSocialPostStatusRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Caption,
		&i.Platform,
		&i.Pilar,
		&i.Status,
		&i.ScheduledAt,
		&i.MediaUrl,
		&i.ReferenceUrl,
		&i.Formato,
		&i.Objetivo,
		&i.Programa,
		&i.Receita,
		&i.PlataformasDestino,
		&i.CopyArte,
		&i.Hashtags,
		&i.ConceitoVisual,
		&i.Paleta,
		&i.PromptIa,
		&i.Specs,
		&i.MasterUrl,
		&i.Mandatorios,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
