// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersWithCustomRole = `-- name: CountUsersWithCustomRole :one
SELECT COUNT(*) FROM users WHERE custom_role_id = $1::uuid
`

func (q *Queries) CountUsersWithCustomRole(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersWithCustomRole, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomRole = `-- name: CreateCustomRole :one
INSERT INTO custom_roles (name, description, permissions)
VALUES ($1, $2, $3::jsonb)
RETURNING id::text, name, description, permissions, created_at, updated_at
`

type CreateCustomRoleParams struct {
	Name        string
	Description *string
	Column3     []byte
}

type CreateCustomRoleRow struct {
	ID          string
	Name        string
	Description *string
	Permissions []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateCustomRole(ctx context.Context, arg CreateCustomRoleParams) (CreateCustomRoleRow, error) {
	row := q.db.QueryRow(ctx, createCustomRole, arg.Name, arg.Description, arg.Column3)
	var i CreateCustomRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomRole = `-- name: DeleteCustomRole :execrows
DELETE FROM custom_roles WHERE id = $1::uuid
`

func (q *Queries) DeleteCustomRole(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomRole, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomRole = `-- name: GetCustomRole :one
SELECT id::text, name, description, permissions, created_at, updated_at
FROM custom_roles WHERE id = $1::uuid
`

type GetCustomRoleRow struct {
	ID          string
	Name        string
	Description *string
	Permissions []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetCustomRole(ctx context.Context, dollar_1 pgtype.UUID) (GetCustomRoleRow, error) {
	row := q.db.QueryRow(ctx, getCustomRole, dollar_1)
	var i GetCustomRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomRoles = `-- name: ListCustomRoles :many

SELECT id::text, name, description, permissions, created_at, updated_at
FROM custom_roles ORDER BY created_at DESC
`

type ListCustomRolesRow struct {
	ID          string
	Name        string
	Description *string
	Permissions []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// Queries de Custom Roles (admin CRUD)
func (q *Queries) ListCustomRoles(ctx context.Context) ([]ListCustomRolesRow, error) {
	rows, err := q.db.Query(ctx, listCustomRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomRolesRow{}
	for rows.Next() {
		var i ListCustomRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomRole = `-- name: UpdateCustomRole :one
UPDATE custom_roles
SET name = $2, description = $3, permissions = $4::jsonb, updated_at = now()
WHERE id = $1::uuid
RETURNING id::text, name, description, permissions, created_at, updated_at
`

type UpdateCustomRoleParams struct {
	Column1     pgtype.UUID
	Name        string
	Description *string
	Column4     []byte
}

type UpdateCustomRoleRow struct {
	ID          string
	Name        string
	Description *string
	Permissions []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateCustomRole(ctx context.Context, arg UpdateCustomRoleParams) (UpdateCustomRoleRow, error) {
	row := q.db.QueryRow(ctx, updateCustomRole,
		arg.Column1,
		arg.Name,
		arg.Description,
		arg.Column4,
	)
	var i UpdateCustomRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
