// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: charges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCharge = `-- name: GetCharge :one
SELECT id, kind, subscription_id, student_id, amount_cents, due_date::text, reference_month,
       status, provider, COALESCE(provider_charge_id, ''), correlation_id,
       COALESCE(br_code, ''), COALESCE(qr_code, ''), paid_at, created_at
FROM pay_charges
WHERE id = $1
`

type GetChargeRow struct {
	ID               int64
	Kind             string
	SubscriptionID   *int64
	StudentID        *int64
	AmountCents      int64
	DueDate          string
	ReferenceMonth   *string
	Status           string
	Provider         string
	ProviderChargeID string
	CorrelationID    string
	BrCode           string
	QrCode           string
	PaidAt           pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetCharge(ctx context.Context, id int64) (GetChargeRow, error) {
	row := q.db.QueryRow(ctx, getCharge, id)
	var i GetChargeRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SubscriptionID,
		&i.StudentID,
		&i.AmountCents,
		&i.DueDate,
		&i.ReferenceMonth,
		&i.Status,
		&i.Provider,
		&i.ProviderChargeID,
		&i.CorrelationID,
		&i.BrCode,
		&i.QrCode,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getChargeByPublicToken = `-- name: GetChargeByPublicToken :one

SELECT id, kind, student_id, customer_id, amount_cents, due_date::text, status,
       COALESCE(br_code, ''), COALESCE(qr_code, ''), correlation_id, paid_at, created_at
FROM pay_charges
WHERE public_token = $1
`

type GetChargeByPublicTokenRow struct {
	ID            int64
	Kind          string
	StudentID     *int64
	CustomerID    *int64
	AmountCents   int64
	DueDate       string
	Status        string
	BrCode        string
	QrCode        string
	CorrelationID string
	PaidAt        pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

// ListCharges filtra opcionalmente por status e student_id.
// SQL dinâmico via condicionais inline ($1=” ignora filtro de status, $2=0 ignora filtro de aluno).
// Não migrado para sqlc — ver store.go ListCharges.
func (q *Queries) GetChargeByPublicToken(ctx context.Context, publicToken *string) (GetChargeByPublicTokenRow, error) {
	row := q.db.QueryRow(ctx, getChargeByPublicToken, publicToken)
	var i GetChargeByPublicTokenRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.StudentID,
		&i.CustomerID,
		&i.AmountCents,
		&i.DueDate,
		&i.Status,
		&i.BrCode,
		&i.QrCode,
		&i.CorrelationID,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCharge = `-- name: InsertCharge :one
INSERT INTO pay_charges
  (kind, subscription_id, student_id, customer_id, amount_cents, due_date, reference_month,
   provider, provider_charge_id, correlation_id, public_token, payer_tax_id, br_code, qr_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, status, created_at
`

type InsertChargeParams struct {
	Kind             string
	SubscriptionID   *int64
	StudentID        *int64
	CustomerID       *int64
	AmountCents      int64
	DueDate          pgtype.Date
	ReferenceMonth   *string
	Provider         string
	ProviderChargeID *string
	CorrelationID    string
	PublicToken      *string
	PayerTaxID       *string
	BrCode           *string
	QrCode           *string
}

type InsertChargeRow struct {
	ID        int64
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertCharge(ctx context.Context, arg InsertChargeParams) (InsertChargeRow, error) {
	row := q.db.QueryRow(ctx, insertCharge,
		arg.Kind,
		arg.SubscriptionID,
		arg.StudentID,
		arg.CustomerID,
		arg.AmountCents,
		arg.DueDate,
		arg.ReferenceMonth,
		arg.Provider,
		arg.ProviderChargeID,
		arg.CorrelationID,
		arg.PublicToken,
		arg.PayerTaxID,
		arg.BrCode,
		arg.QrCode,
	)
	var i InsertChargeRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const listChargesByCustomer = `-- name: ListChargesByCustomer :many
SELECT id, kind, amount_cents, due_date::text, status,
       COALESCE(br_code, ''), correlation_id, paid_at, created_at
FROM pay_charges
WHERE customer_id = $1
ORDER BY created_at DESC
`

type ListChargesByCustomerRow struct {
	ID            int64
	Kind          string
	AmountCents   int64
	DueDate       string
	Status        string
	BrCode        string
	CorrelationID string
	PaidAt        pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListChargesByCustomer(ctx context.Context, customerID *int64) ([]ListChargesByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listChargesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChargesByCustomerRow
	for rows.Next() {
		var i ListChargesByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.AmountCents,
			&i.DueDate,
			&i.Status,
			&i.BrCode,
			&i.CorrelationID,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChargeExpired = `-- name: MarkChargeExpired :exec
UPDATE pay_charges
SET status = 'expired'
WHERE correlation_id = $1 AND status = 'pending'
`

func (q *Queries) MarkChargeExpired(ctx context.Context, correlationID string) error {
	_, err := q.db.Exec(ctx, markChargeExpired, correlationID)
	return err
}

const markChargePaid = `-- name: MarkChargePaid :exec
UPDATE pay_charges
SET status = 'paid', paid_at = now()
WHERE correlation_id = $1 AND status = 'pending'
`

func (q *Queries) MarkChargePaid(ctx context.Context, correlationID string) error {
	_, err := q.db.Exec(ctx, markChargePaid, correlationID)
	return err
}

const payerEmailByCharge = `-- name: PayerEmailByCharge :one
SELECT COALESCE(NULLIF(st.name, ''),  cu.name, '') AS name,
       COALESCE(NULLIF(st.email, ''), cu.email, '') AS email
FROM pay_charges c
LEFT JOIN pay_students  st ON st.id = c.student_id
LEFT JOIN pay_customers cu ON cu.id = c.customer_id
WHERE c.id = $1
`

type PayerEmailByChargeRow struct {
	Name  string
	Email string
}

func (q *Queries) PayerEmailByCharge(ctx context.Context, id int64) (PayerEmailByChargeRow, error) {
	row := q.db.QueryRow(ctx, payerEmailByCharge, id)
	var i PayerEmailByChargeRow
	err := row.Scan(&i.Name, &i.Email)
	return i, err
}

const publicTokenByCorrelation = `-- name: PublicTokenByCorrelation :one
SELECT public_token
FROM pay_charges
WHERE correlation_id = $1
`

func (q *Queries) PublicTokenByCorrelation(ctx context.Context, correlationID string) (*string, error) {
	row := q.db.QueryRow(ctx, publicTokenByCorrelation, correlationID)
	var public_token *string
	err := row.Scan(&public_token)
	return public_token, err
}
