// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: charges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelChargeByToken = `-- name: CancelChargeByToken :one
UPDATE pay_charges
SET status = 'canceled'
WHERE public_token = $1 AND status = 'pending'
RETURNING correlation_id, COALESCE(provider_charge_id, '') AS provider_charge_id, method
`

type CancelChargeByTokenRow struct {
	CorrelationID    string
	ProviderChargeID string
	Method           string
}

// Cancela uma cobrança pendente pelo token público (botão na tela de pagamento).
// Só afeta pendentes; já paga/cancelada/inexistente → sem linha (ErrNoRows).
func (q *Queries) CancelChargeByToken(ctx context.Context, publicToken *string) (CancelChargeByTokenRow, error) {
	row := q.db.QueryRow(ctx, cancelChargeByToken, publicToken)
	var i CancelChargeByTokenRow
	err := row.Scan(&i.CorrelationID, &i.ProviderChargeID, &i.Method)
	return i, err
}

const expireOverdueCharges = `-- name: ExpireOverdueCharges :execrows
UPDATE pay_charges
SET status = 'expired'
WHERE status = 'pending'
  AND method = 'pix'
  AND (due_date + interval '23 hours') < now()
`

// Marca como expiradas as cobranças PIX pendentes cujo QR já passou da validade
// (vencimento + 23h, igual à expiração enviada à Efí em createAndPersistCharge).
//
// O filtro method = 'pix' é obrigatório: a janela de 23h é a do QR do PIX e não vale
// para os outros meios. Sem ele, cartão (que nasce com due_date = hoje) expirava em
// ~23h e boleto liquidado em D+1 já chegava expirado.
func (q *Queries) ExpireOverdueCharges(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireOverdueCharges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCharge = `-- name: GetCharge :one
SELECT id, kind, subscription_id, student_id, amount_cents, due_date::text, reference_month,
       status, provider, COALESCE(provider_charge_id, ''), correlation_id,
       method, COALESCE(br_code, ''), COALESCE(qr_code, ''),
       COALESCE(pdf_url, ''), COALESCE(barcode, ''), paid_at, created_at
FROM pay_charges
WHERE id = $1
`

type GetChargeRow struct {
	ID               int64
	Kind             string
	SubscriptionID   *int64
	StudentID        *int64
	AmountCents      int64
	DueDate          string
	ReferenceMonth   *string
	Status           string
	Provider         string
	ProviderChargeID string
	CorrelationID    string
	Method           string
	BrCode           string
	QrCode           string
	PdfUrl           string
	Barcode          string
	PaidAt           pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetCharge(ctx context.Context, id int64) (GetChargeRow, error) {
	row := q.db.QueryRow(ctx, getCharge, id)
	var i GetChargeRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SubscriptionID,
		&i.StudentID,
		&i.AmountCents,
		&i.DueDate,
		&i.ReferenceMonth,
		&i.Status,
		&i.Provider,
		&i.ProviderChargeID,
		&i.CorrelationID,
		&i.Method,
		&i.BrCode,
		&i.QrCode,
		&i.PdfUrl,
		&i.Barcode,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getChargeByPublicToken = `-- name: GetChargeByPublicToken :one

SELECT id, kind, student_id, customer_id, amount_cents, due_date::text, status,
       method, COALESCE(br_code, ''), COALESCE(qr_code, ''),
       COALESCE(pdf_url, ''), COALESCE(barcode, ''),
       COALESCE(provider_charge_id, ''), correlation_id, paid_at, created_at
FROM pay_charges
WHERE public_token = $1
`

type GetChargeByPublicTokenRow struct {
	ID               int64
	Kind             string
	StudentID        *int64
	CustomerID       *int64
	AmountCents      int64
	DueDate          string
	Status           string
	Method           string
	BrCode           string
	QrCode           string
	PdfUrl           string
	Barcode          string
	ProviderChargeID string
	CorrelationID    string
	PaidAt           pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

// ListCharges filtra opcionalmente por status e student_id.
// SQL dinâmico via condicionais inline ($1=” ignora filtro de status, $2=0 ignora filtro de aluno).
// Não migrado para sqlc — ver store.go ListCharges.
func (q *Queries) GetChargeByPublicToken(ctx context.Context, publicToken *string) (GetChargeByPublicTokenRow, error) {
	row := q.db.QueryRow(ctx, getChargeByPublicToken, publicToken)
	var i GetChargeByPublicTokenRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.StudentID,
		&i.CustomerID,
		&i.AmountCents,
		&i.DueDate,
		&i.Status,
		&i.Method,
		&i.BrCode,
		&i.QrCode,
		&i.PdfUrl,
		&i.Barcode,
		&i.ProviderChargeID,
		&i.CorrelationID,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCharge = `-- name: InsertCharge :one
INSERT INTO pay_charges
  (kind, subscription_id, student_id, customer_id, amount_cents, due_date, reference_month,
   provider, provider_charge_id, correlation_id, public_token, payer_tax_id, method,
   br_code, qr_code, pdf_url, barcode)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, status, created_at
`

type InsertChargeParams struct {
	Kind             string
	SubscriptionID   *int64
	StudentID        *int64
	CustomerID       *int64
	AmountCents      int64
	DueDate          pgtype.Date
	ReferenceMonth   *string
	Provider         string
	ProviderChargeID *string
	CorrelationID    string
	PublicToken      *string
	PayerTaxID       *string
	Method           string
	BrCode           *string
	QrCode           *string
	PdfUrl           *string
	Barcode          *string
}

type InsertChargeRow struct {
	ID        int64
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertCharge(ctx context.Context, arg InsertChargeParams) (InsertChargeRow, error) {
	row := q.db.QueryRow(ctx, insertCharge,
		arg.Kind,
		arg.SubscriptionID,
		arg.StudentID,
		arg.CustomerID,
		arg.AmountCents,
		arg.DueDate,
		arg.ReferenceMonth,
		arg.Provider,
		arg.ProviderChargeID,
		arg.CorrelationID,
		arg.PublicToken,
		arg.PayerTaxID,
		arg.Method,
		arg.BrCode,
		arg.QrCode,
		arg.PdfUrl,
		arg.Barcode,
	)
	var i InsertChargeRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const insertRecurrenceCharge = `-- name: InsertRecurrenceCharge :one
INSERT INTO pay_charges
  (kind, recurrence_id, customer_id, amount_cents, due_date, reference_month,
   provider, provider_charge_id, correlation_id, payer_tax_id, br_code, qr_code, public_token)
VALUES ('recorrente', $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, status, created_at
`

type InsertRecurrenceChargeParams struct {
	RecurrenceID     *int64
	CustomerID       *int64
	AmountCents      int64
	DueDate          pgtype.Date
	ReferenceMonth   *string
	Provider         string
	ProviderChargeID *string
	CorrelationID    string
	PayerTaxID       *string
	BrCode           *string
	QrCode           *string
	PublicToken      *string
}

type InsertRecurrenceChargeRow struct {
	ID        int64
	Status    string
	CreatedAt pgtype.Timestamptz
}

// Cobrança de um ciclo de PIX Automático (kind='recorrente'), vinculada à recorrência.
// O txid da cobr da Efí vai em provider_charge_id; reference_month garante a anti-duplicidade.
// public_token só é preenchido na 1ª cobr da Jornada 3 (checkout recorrente, tela
// /pay/{token}); nos ciclos seguintes (débito automático) vai NULL.
func (q *Queries) InsertRecurrenceCharge(ctx context.Context, arg InsertRecurrenceChargeParams) (InsertRecurrenceChargeRow, error) {
	row := q.db.QueryRow(ctx, insertRecurrenceCharge,
		arg.RecurrenceID,
		arg.CustomerID,
		arg.AmountCents,
		arg.DueDate,
		arg.ReferenceMonth,
		arg.Provider,
		arg.ProviderChargeID,
		arg.CorrelationID,
		arg.PayerTaxID,
		arg.BrCode,
		arg.QrCode,
		arg.PublicToken,
	)
	var i InsertRecurrenceChargeRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const listChargeItemsByCustomer = `-- name: ListChargeItemsByCustomer :many
SELECT ci.charge_id, ci.product_id, ci.name, ci.price_cents, ci.quantity
FROM pay_charge_items ci
JOIN pay_charges c ON c.id = ci.charge_id
WHERE c.customer_id = $1
ORDER BY ci.charge_id
`

type ListChargeItemsByCustomerRow struct {
	ChargeID   int64
	ProductID  *int64
	Name       string
	PriceCents int64
	Quantity   int32
}

// Itens de todas as cobranças de um cliente (para montar o detalhe das compras).
func (q *Queries) ListChargeItemsByCustomer(ctx context.Context, customerID *int64) ([]ListChargeItemsByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listChargeItemsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChargeItemsByCustomerRow
	for rows.Next() {
		var i ListChargeItemsByCustomerRow
		if err := rows.Scan(
			&i.ChargeID,
			&i.ProductID,
			&i.Name,
			&i.PriceCents,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChargeItemsByTaxID = `-- name: ListChargeItemsByTaxID :many
SELECT ci.charge_id, ci.product_id, ci.name, ci.price_cents, ci.quantity
FROM pay_charge_items ci
JOIN pay_charges c ON c.id = ci.charge_id
JOIN pay_customers cu ON cu.id = c.customer_id
WHERE cu.tax_id = $1
ORDER BY ci.charge_id
`

type ListChargeItemsByTaxIDRow struct {
	ChargeID   int64
	ProductID  *int64
	Name       string
	PriceCents int64
	Quantity   int32
}

// Itens das cobranças de todas as contas com um mesmo CPF.
func (q *Queries) ListChargeItemsByTaxID(ctx context.Context, taxID string) ([]ListChargeItemsByTaxIDRow, error) {
	rows, err := q.db.Query(ctx, listChargeItemsByTaxID, taxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChargeItemsByTaxIDRow
	for rows.Next() {
		var i ListChargeItemsByTaxIDRow
		if err := rows.Scan(
			&i.ChargeID,
			&i.ProductID,
			&i.Name,
			&i.PriceCents,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChargesByCustomer = `-- name: ListChargesByCustomer :many
SELECT id, kind, amount_cents, due_date::text, status,
       COALESCE(br_code, ''), correlation_id, paid_at, created_at
FROM pay_charges
WHERE customer_id = $1
ORDER BY created_at DESC
`

type ListChargesByCustomerRow struct {
	ID            int64
	Kind          string
	AmountCents   int64
	DueDate       string
	Status        string
	BrCode        string
	CorrelationID string
	PaidAt        pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListChargesByCustomer(ctx context.Context, customerID *int64) ([]ListChargesByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listChargesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChargesByCustomerRow
	for rows.Next() {
		var i ListChargesByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.AmountCents,
			&i.DueDate,
			&i.Status,
			&i.BrCode,
			&i.CorrelationID,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChargesByRecurrence = `-- name: ListChargesByRecurrence :many
SELECT id, kind, amount_cents, due_date::text, reference_month, status,
       COALESCE(br_code, ''), correlation_id, paid_at, created_at
FROM pay_charges
WHERE recurrence_id = $1
ORDER BY created_at DESC
`

type ListChargesByRecurrenceRow struct {
	ID             int64
	Kind           string
	AmountCents    int64
	DueDate        string
	ReferenceMonth *string
	Status         string
	BrCode         string
	CorrelationID  string
	PaidAt         pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

// Ciclos (cobranças) de uma recorrência de PIX Automático, mais recentes primeiro.
func (q *Queries) ListChargesByRecurrence(ctx context.Context, recurrenceID *int64) ([]ListChargesByRecurrenceRow, error) {
	rows, err := q.db.Query(ctx, listChargesByRecurrence, recurrenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChargesByRecurrenceRow
	for rows.Next() {
		var i ListChargesByRecurrenceRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.AmountCents,
			&i.DueDate,
			&i.ReferenceMonth,
			&i.Status,
			&i.BrCode,
			&i.CorrelationID,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChargesByTaxID = `-- name: ListChargesByTaxID :many
SELECT c.id, c.kind, c.amount_cents, c.due_date::text, c.status,
       COALESCE(c.br_code, ''), c.correlation_id, c.paid_at, c.created_at
FROM pay_charges c
JOIN pay_customers cu ON cu.id = c.customer_id
WHERE cu.tax_id = $1
ORDER BY c.created_at DESC
`

type ListChargesByTaxIDRow struct {
	ID            int64
	Kind          string
	AmountCents   int64
	CDueDate      string
	Status        string
	BrCode        string
	CorrelationID string
	PaidAt        pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

// Cobranças de TODAS as contas com um mesmo CPF (detalhe consolidado por pessoa).
func (q *Queries) ListChargesByTaxID(ctx context.Context, taxID string) ([]ListChargesByTaxIDRow, error) {
	rows, err := q.db.Query(ctx, listChargesByTaxID, taxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChargesByTaxIDRow
	for rows.Next() {
		var i ListChargesByTaxIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.AmountCents,
			&i.CDueDate,
			&i.Status,
			&i.BrCode,
			&i.CorrelationID,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChargeExpired = `-- name: MarkChargeExpired :exec
UPDATE pay_charges
SET status = 'expired'
WHERE correlation_id = $1 AND status = 'pending'
`

func (q *Queries) MarkChargeExpired(ctx context.Context, correlationID string) error {
	_, err := q.db.Exec(ctx, markChargeExpired, correlationID)
	return err
}

const markChargePaid = `-- name: MarkChargePaid :exec
UPDATE pay_charges
SET status = 'paid', paid_at = now()
WHERE correlation_id = $1 AND status IN ('pending', 'expired')
`

// Aceita 'expired' além de 'pending': o pagamento vem CONFIRMADO pelo gateway, e uma
// cobrança que o job de expiração já fechou (ou que foi paga no limite da janela) não
// pode ficar sem baixa — o dinheiro está na Efí de qualquer jeito.
func (q *Queries) MarkChargePaid(ctx context.Context, correlationID string) error {
	_, err := q.db.Exec(ctx, markChargePaid, correlationID)
	return err
}

const markChargePaidByProviderID = `-- name: MarkChargePaidByProviderID :execrows
UPDATE pay_charges
SET status = 'paid', paid_at = now()
WHERE provider_charge_id = $1 AND status IN ('pending', 'expired')
`

// Boleto (API Cobranças): a notificação casa pelo charge_id do Efí (provider_charge_id),
// não pelo correlation_id. Devolve nº de linhas afetadas (>0 = realmente marcou paga agora).
// Aceita 'expired' pelo mesmo motivo de MarkChargePaid: boleto liquida em D+1 e o
// gateway já confirmou o pagamento.
func (q *Queries) MarkChargePaidByProviderID(ctx context.Context, providerChargeID *string) (int64, error) {
	result, err := q.db.Exec(ctx, markChargePaidByProviderID, providerChargeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const payerEmailByCharge = `-- name: PayerEmailByCharge :one
SELECT COALESCE(NULLIF(st.name, ''),  cu.name, '') AS name,
       COALESCE(NULLIF(st.email, ''), cu.email, '') AS email
FROM pay_charges c
LEFT JOIN pay_students  st ON st.id = c.student_id
LEFT JOIN pay_customers cu ON cu.id = c.customer_id
WHERE c.id = $1
`

type PayerEmailByChargeRow struct {
	Name  string
	Email string
}

func (q *Queries) PayerEmailByCharge(ctx context.Context, id int64) (PayerEmailByChargeRow, error) {
	row := q.db.QueryRow(ctx, payerEmailByCharge, id)
	var i PayerEmailByChargeRow
	err := row.Scan(&i.Name, &i.Email)
	return i, err
}

const publicTokenByCorrelation = `-- name: PublicTokenByCorrelation :one
SELECT public_token
FROM pay_charges
WHERE correlation_id = $1
`

func (q *Queries) PublicTokenByCorrelation(ctx context.Context, correlationID string) (*string, error) {
	row := q.db.QueryRow(ctx, publicTokenByCorrelation, correlationID)
	var public_token *string
	err := row.Scan(&public_token)
	return public_token, err
}

const publicTokenByProviderID = `-- name: PublicTokenByProviderID :one
SELECT public_token
FROM pay_charges
WHERE provider_charge_id = $1
`

func (q *Queries) PublicTokenByProviderID(ctx context.Context, providerChargeID *string) (*string, error) {
	row := q.db.QueryRow(ctx, publicTokenByProviderID, providerChargeID)
	var public_token *string
	err := row.Scan(&public_token)
	return public_token, err
}
