// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"
)

const getCustomerByUserID = `-- name: GetCustomerByUserID :one
SELECT id, user_id, tax_id, phone, name, email
FROM pay_customers
WHERE user_id = $1
`

type GetCustomerByUserIDRow struct {
	ID     int64
	UserID int64
	TaxID  string
	Phone  string
	Name   string
	Email  string
}

func (q *Queries) GetCustomerByUserID(ctx context.Context, userID int64) (GetCustomerByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByUserID, userID)
	var i GetCustomerByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaxID,
		&i.Phone,
		&i.Name,
		&i.Email,
	)
	return i, err
}

const updateCustomerData = `-- name: UpdateCustomerData :exec
UPDATE pay_customers
SET tax_id = $2, phone = $3, name = $4, email = $5
WHERE user_id = $1
`

type UpdateCustomerDataParams struct {
	UserID int64
	TaxID  string
	Phone  string
	Name   string
	Email  string
}

func (q *Queries) UpdateCustomerData(ctx context.Context, arg UpdateCustomerDataParams) error {
	_, err := q.db.Exec(ctx, updateCustomerData,
		arg.UserID,
		arg.TaxID,
		arg.Phone,
		arg.Name,
		arg.Email,
	)
	return err
}

const upsertCustomer = `-- name: UpsertCustomer :one
INSERT INTO pay_customers (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, tax_id, phone, name, email
`

type UpsertCustomerRow struct {
	ID     int64
	UserID int64
	TaxID  string
	Phone  string
	Name   string
	Email  string
}

func (q *Queries) UpsertCustomer(ctx context.Context, userID int64) (UpsertCustomerRow, error) {
	row := q.db.QueryRow(ctx, upsertCustomer, userID)
	var i UpsertCustomerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaxID,
		&i.Phone,
		&i.Name,
		&i.Email,
	)
	return i, err
}
