// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"
)

const getCustomerByUserID = `-- name: GetCustomerByUserID :one
SELECT id, user_id, tax_id, phone, name, email
FROM pay_customers
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

type GetCustomerByUserIDRow struct {
	ID     int64
	UserID int64
	TaxID  string
	Phone  string
	Name   string
	Email  string
}

// Como a conta pode ter mais de um cliente (um por CPF), devolve o mais recente.
func (q *Queries) GetCustomerByUserID(ctx context.Context, userID int64) (GetCustomerByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByUserID, userID)
	var i GetCustomerByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaxID,
		&i.Phone,
		&i.Name,
		&i.Email,
	)
	return i, err
}

const upsertCustomer = `-- name: UpsertCustomer :one
INSERT INTO pay_customers (user_id, tax_id, phone, name, email)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, tax_id) DO UPDATE
  SET phone = EXCLUDED.phone, name = EXCLUDED.name, email = EXCLUDED.email
RETURNING id, user_id, tax_id, phone, name, email
`

type UpsertCustomerParams struct {
	UserID int64
	TaxID  string
	Phone  string
	Name   string
	Email  string
}

type UpsertCustomerRow struct {
	ID     int64
	UserID int64
	TaxID  string
	Phone  string
	Name   string
	Email  string
}

// Cliente único por (user_id, tax_id): cria ou atualiza os dados do pagador.
func (q *Queries) UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (UpsertCustomerRow, error) {
	row := q.db.QueryRow(ctx, upsertCustomer,
		arg.UserID,
		arg.TaxID,
		arg.Phone,
		arg.Name,
		arg.Email,
	)
	var i UpsertCustomerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaxID,
		&i.Phone,
		&i.Name,
		&i.Email,
	)
	return i, err
}
