// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, user_id, tax_id, phone, name, email, created_at
FROM pay_customers
WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id int64) (PayCustomer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i PayCustomer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaxID,
		&i.Phone,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByUserID = `-- name: GetCustomerByUserID :one
SELECT id, user_id, tax_id, phone, name, email
FROM pay_customers
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

type GetCustomerByUserIDRow struct {
	ID     int64
	UserID int64
	TaxID  string
	Phone  string
	Name   string
	Email  string
}

// Como a conta pode ter mais de um cliente (um por CPF), devolve o mais recente.
func (q *Queries) GetCustomerByUserID(ctx context.Context, userID int64) (GetCustomerByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByUserID, userID)
	var i GetCustomerByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaxID,
		&i.Phone,
		&i.Name,
		&i.Email,
	)
	return i, err
}

const listCustomersWithStats = `-- name: ListCustomersWithStats :many
SELECT (array_agg(cu.id ORDER BY cu.created_at DESC))[1]::bigint      AS id,
       (array_agg(cu.user_id ORDER BY cu.created_at DESC))[1]::bigint AS user_id,
       cu.tax_id,
       (array_agg(cu.phone ORDER BY cu.created_at DESC))[1]::text     AS phone,
       (array_agg(cu.name ORDER BY cu.created_at DESC))[1]::text      AS name,
       (array_agg(cu.email ORDER BY cu.created_at DESC))[1]::text     AS email,
       MIN(cu.created_at)::timestamptz AS created_at,
       (COUNT(c.id))::bigint AS charges_count,
       (COUNT(c.id) FILTER (WHERE c.status = 'paid'))::bigint AS paid_count,
       (COALESCE(SUM(c.amount_cents) FILTER (WHERE c.status = 'paid'), 0))::bigint AS paid_total_cents,
       MAX(c.created_at)::timestamptz AS last_charge_at
FROM pay_customers cu
LEFT JOIN pay_charges c ON c.customer_id = cu.id
GROUP BY cu.tax_id
ORDER BY MAX(c.created_at) DESC NULLS LAST, MIN(cu.created_at) DESC
`

type ListCustomersWithStatsRow struct {
	ID             int64
	UserID         int64
	TaxID          string
	Phone          string
	Name           string
	Email          string
	CreatedAt      pgtype.Timestamptz
	ChargesCount   int64
	PaidCount      int64
	PaidTotalCents int64
	LastChargeAt   pgtype.Timestamptz
}

// Lista clientes AGRUPADOS por CPF (uma linha por pessoa, mesmo que tenha logado com
// contas diferentes): dados do registro mais recente + agregados de TODAS as compras
// daquele CPF. LEFT JOIN para incluir clientes ainda sem cobrança. O id devolvido é o
// do registro mais recente (usado para abrir o detalhe, que consolida por CPF).
func (q *Queries) ListCustomersWithStats(ctx context.Context) ([]ListCustomersWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listCustomersWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersWithStatsRow
	for rows.Next() {
		var i ListCustomersWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaxID,
			&i.Phone,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.ChargesCount,
			&i.PaidCount,
			&i.PaidTotalCents,
			&i.LastChargeAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCustomer = `-- name: UpsertCustomer :one
INSERT INTO pay_customers (user_id, tax_id, phone, name, email)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, tax_id) DO UPDATE
  SET phone = EXCLUDED.phone, name = EXCLUDED.name, email = EXCLUDED.email
RETURNING id, user_id, tax_id, phone, name, email
`

type UpsertCustomerParams struct {
	UserID int64
	TaxID  string
	Phone  string
	Name   string
	Email  string
}

type UpsertCustomerRow struct {
	ID     int64
	UserID int64
	TaxID  string
	Phone  string
	Name   string
	Email  string
}

// Cliente único por (user_id, tax_id): cria ou atualiza os dados do pagador.
func (q *Queries) UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (UpsertCustomerRow, error) {
	row := q.db.QueryRow(ctx, upsertCustomer,
		arg.UserID,
		arg.TaxID,
		arg.Phone,
		arg.Name,
		arg.Email,
	)
	var i UpsertCustomerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaxID,
		&i.Phone,
		&i.Name,
		&i.Email,
	)
	return i, err
}
