// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: misc.sql

package db

import (
	"context"
)

const insertChargeItem = `-- name: InsertChargeItem :exec
INSERT INTO pay_charge_items (charge_id, product_id, name, price_cents, quantity)
VALUES ($1, $2, $3, $4, $5)
`

type InsertChargeItemParams struct {
	ChargeID   int64
	ProductID  *int64
	Name       string
	PriceCents int64
	Quantity   int32
}

func (q *Queries) InsertChargeItem(ctx context.Context, arg InsertChargeItemParams) error {
	_, err := q.db.Exec(ctx, insertChargeItem,
		arg.ChargeID,
		arg.ProductID,
		arg.Name,
		arg.PriceCents,
		arg.Quantity,
	)
	return err
}
