// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PayCharge struct {
	ID               int64
	Kind             string
	SubscriptionID   *int64
	RecurrenceID     *int64
	StudentID        *int64
	CustomerID       *int64
	AmountCents      int64
	DueDate          pgtype.Date
	ReferenceMonth   *string
	Status           string
	Provider         string
	ProviderChargeID *string
	CorrelationID    string
	PublicToken      *string
	PayerTaxID       *string
	Method           string
	BrCode           *string
	QrCode           *string
	PdfUrl           *string
	Barcode          *string
	PaidAt           pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type PayChargeItem struct {
	ID         int64
	ChargeID   int64
	ProductID  *int64
	Name       string
	PriceCents int64
	Quantity   int32
}

type PayCustomer struct {
	ID        int64
	UserID    int64
	TaxID     string
	Phone     string
	Name      string
	Email     string
	CreatedAt pgtype.Timestamptz
}

type PayPlan struct {
	ID          int64
	Name        string
	AmountCents int64
	DueDay      int32
	Active      bool
	CreatedAt   pgtype.Timestamptz
}

type PayProduct struct {
	ID                int64
	Slug              string
	Name              string
	Description       string
	PriceCents        int64
	Active            bool
	Recurring         bool
	Periodicity       *string
	DueDay            *int32
	ChargeOnSubscribe bool
	CreatedAt         pgtype.Timestamptz
}

type PayRecurrence struct {
	ID             int64
	SubscriptionID *int64
	ProductID      *int64
	CustomerID     *int64
	PayerTaxID     string
	PayerName      string
	AmountCents    int64
	Periodicity    string
	DueDay         *int32
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	Journey        int16
	EfiIDRec       *string
	BrCode         *string
	QrCode         *string
	Status         string
	PublicToken    *string
	CreatedAt      pgtype.Timestamptz
}

type PayStudent struct {
	ID        int64
	Name      string
	TaxID     string
	Email     string
	Phone     string
	CreatedAt pgtype.Timestamptz
}

type PaySubscription struct {
	ID          int64
	StudentID   int64
	PlanID      int64
	AmountCents int64
	DueDay      int32
	Status      string
	CreatedAt   pgtype.Timestamptz
}

type PayWebhookEvent struct {
	ID          string
	Type        string
	Payload     []byte
	ProcessedAt pgtype.Timestamptz
}
