// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO pay_plans (name, amount_cents, due_day)
VALUES ($1, $2, $3)
RETURNING id, name, amount_cents, due_day, active, created_at
`

type CreatePlanParams struct {
	Name        string
	AmountCents int64
	DueDay      int32
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (PayPlan, error) {
	row := q.db.QueryRow(ctx, createPlan, arg.Name, arg.AmountCents, arg.DueDay)
	var i PayPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AmountCents,
		&i.DueDay,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, amount_cents, due_day, active
FROM pay_plans
ORDER BY name
`

type ListPlansRow struct {
	ID          int64
	Name        string
	AmountCents int64
	DueDay      int32
	Active      bool
}

func (q *Queries) ListPlans(ctx context.Context) ([]ListPlansRow, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlansRow
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AmountCents,
			&i.DueDay,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
