// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO pay_products (slug, name, description, price_cents)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, description, price_cents, active, created_at
`

type CreateProductParams struct {
	Slug        string
	Name        string
	Description string
	PriceCents  int64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (PayProduct, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.PriceCents,
	)
	var i PayProduct
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM pay_products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, slug, name, description, price_cents, active
FROM pay_products
WHERE id = $1 AND active = true
`

type GetProductByIDRow struct {
	ID          int64
	Slug        string
	Name        string
	Description string
	PriceCents  int64
	Active      bool
}

func (q *Queries) GetProductByID(ctx context.Context, id int64) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Active,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, slug, name, description, price_cents, active
FROM pay_products
WHERE slug = $1 AND active = true
`

type GetProductBySlugRow struct {
	ID          int64
	Slug        string
	Name        string
	Description string
	PriceCents  int64
	Active      bool
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Active,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, slug, name, description, price_cents, active
FROM pay_products
ORDER BY name
`

type ListProductsRow struct {
	ID          int64
	Slug        string
	Name        string
	Description string
	PriceCents  int64
	Active      bool
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :execrows
UPDATE pay_products
SET name = $2, description = $3, price_cents = $4, active = $5
WHERE id = $1
`

type UpdateProductParams struct {
	ID          int64
	Name        string
	Description string
	PriceCents  int64
	Active      bool
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Active,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
