// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurrences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurrence = `-- name: CreateRecurrence :one
INSERT INTO pay_recurrences
  (subscription_id, product_id, customer_id, payer_tax_id, payer_name, amount_cents,
   periodicity, due_day, start_date, end_date, journey)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, status, created_at
`

type CreateRecurrenceParams struct {
	SubscriptionID *int64
	ProductID      *int64
	CustomerID     *int64
	PayerTaxID     string
	PayerName      string
	AmountCents    int64
	Periodicity    string
	DueDay         *int32
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	Journey        int16
}

type CreateRecurrenceRow struct {
	ID        int64
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateRecurrence(ctx context.Context, arg CreateRecurrenceParams) (CreateRecurrenceRow, error) {
	row := q.db.QueryRow(ctx, createRecurrence,
		arg.SubscriptionID,
		arg.ProductID,
		arg.CustomerID,
		arg.PayerTaxID,
		arg.PayerName,
		arg.AmountCents,
		arg.Periodicity,
		arg.DueDay,
		arg.StartDate,
		arg.EndDate,
		arg.Journey,
	)
	var i CreateRecurrenceRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getRecurrence = `-- name: GetRecurrence :one
SELECT id, subscription_id, product_id, customer_id, payer_tax_id, payer_name,
       amount_cents, periodicity, due_day, start_date::text, end_date::text, journey,
       COALESCE(efi_id_rec, ''), COALESCE(br_code, ''), COALESCE(qr_code, ''),
       status, created_at
FROM pay_recurrences
WHERE id = $1
`

type GetRecurrenceRow struct {
	ID             int64
	SubscriptionID *int64
	ProductID      *int64
	CustomerID     *int64
	PayerTaxID     string
	PayerName      string
	AmountCents    int64
	Periodicity    string
	DueDay         *int32
	StartDate      string
	EndDate        string
	Journey        int16
	EfiIDRec       string
	BrCode         string
	QrCode         string
	Status         string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetRecurrence(ctx context.Context, id int64) (GetRecurrenceRow, error) {
	row := q.db.QueryRow(ctx, getRecurrence, id)
	var i GetRecurrenceRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.ProductID,
		&i.CustomerID,
		&i.PayerTaxID,
		&i.PayerName,
		&i.AmountCents,
		&i.Periodicity,
		&i.DueDay,
		&i.StartDate,
		&i.EndDate,
		&i.Journey,
		&i.EfiIDRec,
		&i.BrCode,
		&i.QrCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getRecurrenceByEfiID = `-- name: GetRecurrenceByEfiID :one
SELECT id, subscription_id, product_id, customer_id, payer_tax_id, payer_name,
       amount_cents, periodicity, due_day, start_date::text, end_date::text, journey,
       COALESCE(efi_id_rec, ''), COALESCE(br_code, ''), COALESCE(qr_code, ''),
       status, created_at
FROM pay_recurrences
WHERE efi_id_rec = $1
`

type GetRecurrenceByEfiIDRow struct {
	ID             int64
	SubscriptionID *int64
	ProductID      *int64
	CustomerID     *int64
	PayerTaxID     string
	PayerName      string
	AmountCents    int64
	Periodicity    string
	DueDay         *int32
	StartDate      string
	EndDate        string
	Journey        int16
	EfiIDRec       string
	BrCode         string
	QrCode         string
	Status         string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetRecurrenceByEfiID(ctx context.Context, efiIDRec *string) (GetRecurrenceByEfiIDRow, error) {
	row := q.db.QueryRow(ctx, getRecurrenceByEfiID, efiIDRec)
	var i GetRecurrenceByEfiIDRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.ProductID,
		&i.CustomerID,
		&i.PayerTaxID,
		&i.PayerName,
		&i.AmountCents,
		&i.Periodicity,
		&i.DueDay,
		&i.StartDate,
		&i.EndDate,
		&i.Journey,
		&i.EfiIDRec,
		&i.BrCode,
		&i.QrCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listRecurrences = `-- name: ListRecurrences :many
SELECT id, subscription_id, product_id, customer_id, payer_tax_id, payer_name,
       amount_cents, periodicity, due_day, start_date::text, end_date::text, journey,
       COALESCE(efi_id_rec, ''), COALESCE(br_code, ''), COALESCE(qr_code, ''),
       status, created_at
FROM pay_recurrences
ORDER BY created_at DESC
`

type ListRecurrencesRow struct {
	ID             int64
	SubscriptionID *int64
	ProductID      *int64
	CustomerID     *int64
	PayerTaxID     string
	PayerName      string
	AmountCents    int64
	Periodicity    string
	DueDay         *int32
	StartDate      string
	EndDate        string
	Journey        int16
	EfiIDRec       string
	BrCode         string
	QrCode         string
	Status         string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ListRecurrences(ctx context.Context) ([]ListRecurrencesRow, error) {
	rows, err := q.db.Query(ctx, listRecurrences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecurrencesRow
	for rows.Next() {
		var i ListRecurrencesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.ProductID,
			&i.CustomerID,
			&i.PayerTaxID,
			&i.PayerName,
			&i.AmountCents,
			&i.Periodicity,
			&i.DueDay,
			&i.StartDate,
			&i.EndDate,
			&i.Journey,
			&i.EfiIDRec,
			&i.BrCode,
			&i.QrCode,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recurrencesDueToday = `-- name: RecurrencesDueToday :many
SELECT id, subscription_id, product_id, customer_id, payer_tax_id, payer_name,
       amount_cents, periodicity, due_day, start_date::text, end_date::text, journey,
       COALESCE(efi_id_rec, ''), COALESCE(br_code, ''), COALESCE(qr_code, ''),
       status, created_at
FROM pay_recurrences r
WHERE r.status = 'active'
  AND r.due_day = $1
  AND (r.end_date IS NULL OR r.end_date >= current_date)
  AND NOT EXISTS (
    SELECT 1 FROM pay_charges c
    WHERE c.recurrence_id = r.id
      AND c.reference_month = $2
  )
`

type RecurrencesDueTodayParams struct {
	DueDay         *int32
	ReferenceMonth *string
}

type RecurrencesDueTodayRow struct {
	ID             int64
	SubscriptionID *int64
	ProductID      *int64
	CustomerID     *int64
	PayerTaxID     string
	PayerName      string
	AmountCents    int64
	Periodicity    string
	DueDay         *int32
	StartDate      string
	EndDate        string
	Journey        int16
	EfiIDRec       string
	BrCode         string
	QrCode         string
	Status         string
	CreatedAt      pgtype.Timestamptz
}

// Recorrências 'active' cujo ciclo vence hoje (due_day == dia atual) e que ainda não
// têm a cobrança do ciclo (anti-duplicidade por reference_month, espelha SubscriptionsDueToday).
func (q *Queries) RecurrencesDueToday(ctx context.Context, arg RecurrencesDueTodayParams) ([]RecurrencesDueTodayRow, error) {
	rows, err := q.db.Query(ctx, recurrencesDueToday, arg.DueDay, arg.ReferenceMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurrencesDueTodayRow
	for rows.Next() {
		var i RecurrencesDueTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.ProductID,
			&i.CustomerID,
			&i.PayerTaxID,
			&i.PayerName,
			&i.AmountCents,
			&i.Periodicity,
			&i.DueDay,
			&i.StartDate,
			&i.EndDate,
			&i.Journey,
			&i.EfiIDRec,
			&i.BrCode,
			&i.QrCode,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecurrenceStatus = `-- name: SetRecurrenceStatus :exec
UPDATE pay_recurrences SET status = $2 WHERE id = $1
`

type SetRecurrenceStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) SetRecurrenceStatus(ctx context.Context, arg SetRecurrenceStatusParams) error {
	_, err := q.db.Exec(ctx, setRecurrenceStatus, arg.ID, arg.Status)
	return err
}

const updateRecurrenceAuth = `-- name: UpdateRecurrenceAuth :exec
UPDATE pay_recurrences
SET efi_id_rec = $2, br_code = $3, qr_code = $4, status = $5
WHERE id = $1
`

type UpdateRecurrenceAuthParams struct {
	ID       int64
	EfiIDRec *string
	BrCode   *string
	QrCode   *string
	Status   string
}

// Grava o resultado da criação na Efí (idRec + QR/copia-e-cola) e ativa o status.
func (q *Queries) UpdateRecurrenceAuth(ctx context.Context, arg UpdateRecurrenceAuthParams) error {
	_, err := q.db.Exec(ctx, updateRecurrenceAuth,
		arg.ID,
		arg.EfiIDRec,
		arg.BrCode,
		arg.QrCode,
		arg.Status,
	)
	return err
}
