// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package db

import (
	"context"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO pay_students (name, tax_id, email, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, name, tax_id, email, phone, created_at
`

type CreateStudentParams struct {
	Name  string
	TaxID string
	Email string
	Phone string
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (PayStudent, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.Name,
		arg.TaxID,
		arg.Email,
		arg.Phone,
	)
	var i PayStudent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TaxID,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const getStudent = `-- name: GetStudent :one
SELECT id, name, tax_id, email, phone, created_at
FROM pay_students
WHERE id = $1
`

func (q *Queries) GetStudent(ctx context.Context, id int64) (PayStudent, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i PayStudent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TaxID,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, name, tax_id, email, phone, created_at
FROM pay_students
ORDER BY name
`

func (q *Queries) ListStudents(ctx context.Context) ([]PayStudent, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayStudent
	for rows.Next() {
		var i PayStudent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TaxID,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
