// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO pay_subscriptions (student_id, plan_id, amount_cents, due_day)
VALUES ($1, $2, $3, $4)
RETURNING id, student_id, plan_id, amount_cents, due_day, status, created_at
`

type CreateSubscriptionParams struct {
	StudentID   int64
	PlanID      int64
	AmountCents int64
	DueDay      int32
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (PaySubscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.StudentID,
		arg.PlanID,
		arg.AmountCents,
		arg.DueDay,
	)
	var i PaySubscription
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.PlanID,
		&i.AmountCents,
		&i.DueDay,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, student_id, plan_id, amount_cents, due_day, status
FROM pay_subscriptions
ORDER BY id
`

type ListSubscriptionsRow struct {
	ID          int64
	StudentID   int64
	PlanID      int64
	AmountCents int64
	DueDay      int32
	Status      string
}

func (q *Queries) ListSubscriptions(ctx context.Context) ([]ListSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsRow
	for rows.Next() {
		var i ListSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.PlanID,
			&i.AmountCents,
			&i.DueDay,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSubscriptionStatus = `-- name: SetSubscriptionStatus :exec
UPDATE pay_subscriptions SET status = $2 WHERE id = $1
`

type SetSubscriptionStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) SetSubscriptionStatus(ctx context.Context, arg SetSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, setSubscriptionStatus, arg.ID, arg.Status)
	return err
}

const subscriptionsDueToday = `-- name: SubscriptionsDueToday :many
SELECT sub.id, sub.student_id, sub.plan_id, sub.amount_cents, sub.due_day, sub.status,
       st.id         AS student_id_2,
       st.name       AS student_name,
       st.tax_id     AS student_tax_id,
       st.email      AS student_email,
       st.phone      AS student_phone,
       st.created_at AS student_created_at
FROM pay_subscriptions sub
JOIN pay_students st ON st.id = sub.student_id
WHERE sub.status = 'active'
  AND sub.due_day = $1
  AND NOT EXISTS (
    SELECT 1 FROM pay_charges c
    WHERE c.subscription_id = sub.id
      AND c.reference_month = $2
  )
`

type SubscriptionsDueTodayParams struct {
	DueDay         int32
	ReferenceMonth *string
}

type SubscriptionsDueTodayRow struct {
	ID               int64
	StudentID        int64
	PlanID           int64
	AmountCents      int64
	DueDay           int32
	Status           string
	StudentID2       int64
	StudentName      string
	StudentTaxID     string
	StudentEmail     string
	StudentPhone     string
	StudentCreatedAt pgtype.Timestamptz
}

func (q *Queries) SubscriptionsDueToday(ctx context.Context, arg SubscriptionsDueTodayParams) ([]SubscriptionsDueTodayRow, error) {
	rows, err := q.db.Query(ctx, subscriptionsDueToday, arg.DueDay, arg.ReferenceMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionsDueTodayRow
	for rows.Next() {
		var i SubscriptionsDueTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.PlanID,
			&i.AmountCents,
			&i.DueDay,
			&i.Status,
			&i.StudentID2,
			&i.StudentName,
			&i.StudentTaxID,
			&i.StudentEmail,
			&i.StudentPhone,
			&i.StudentCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
