// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"
)

const markWebhookSeen = `-- name: MarkWebhookSeen :execrows
INSERT INTO pay_webhook_events (id, type, payload)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type MarkWebhookSeenParams struct {
	ID      string
	Type    string
	Payload []byte
}

func (q *Queries) MarkWebhookSeen(ctx context.Context, arg MarkWebhookSeenParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWebhookSeen, arg.ID, arg.Type, arg.Payload)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
