// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueJobs = `-- name: ClaimDueJobs :many
SELECT id, name, description, schedule_cron, timezone, enabled, action_kind, action_ref, http_method, http_url, http_headers, http_body, params, timeout_secs, max_retries, next_run_at, last_run_at, created_by, created_at, updated_at FROM cron_jobs
WHERE enabled = TRUE AND next_run_at IS NOT NULL AND next_run_at <= now()
ORDER BY next_run_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimDueJobs(ctx context.Context, limit int32) ([]CronJob, error) {
	rows, err := q.db.Query(ctx, claimDueJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CronJob
	for rows.Next() {
		var i CronJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ScheduleCron,
			&i.Timezone,
			&i.Enabled,
			&i.ActionKind,
			&i.ActionRef,
			&i.HttpMethod,
			&i.HttpUrl,
			&i.HttpHeaders,
			&i.HttpBody,
			&i.Params,
			&i.TimeoutSecs,
			&i.MaxRetries,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createJob = `-- name: CreateJob :one
INSERT INTO cron_jobs (name, description, schedule_cron, timezone, enabled,
    action_kind, action_ref, http_method, http_url, http_headers, http_body,
    params, timeout_secs, max_retries, next_run_at, created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
RETURNING id, name, description, schedule_cron, timezone, enabled, action_kind, action_ref, http_method, http_url, http_headers, http_body, params, timeout_secs, max_retries, next_run_at, last_run_at, created_by, created_at, updated_at
`

type CreateJobParams struct {
	Name         string             `json:"name"`
	Description  string             `json:"description"`
	ScheduleCron string             `json:"schedule_cron"`
	Timezone     string             `json:"timezone"`
	Enabled      bool               `json:"enabled"`
	ActionKind   string             `json:"action_kind"`
	ActionRef    string             `json:"action_ref"`
	HttpMethod   string             `json:"http_method"`
	HttpUrl      string             `json:"http_url"`
	HttpHeaders  []byte             `json:"http_headers"`
	HttpBody     string             `json:"http_body"`
	Params       []byte             `json:"params"`
	TimeoutSecs  int32              `json:"timeout_secs"`
	MaxRetries   int32              `json:"max_retries"`
	NextRunAt    pgtype.Timestamptz `json:"next_run_at"`
	CreatedBy    string             `json:"created_by"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (CronJob, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Name,
		arg.Description,
		arg.ScheduleCron,
		arg.Timezone,
		arg.Enabled,
		arg.ActionKind,
		arg.ActionRef,
		arg.HttpMethod,
		arg.HttpUrl,
		arg.HttpHeaders,
		arg.HttpBody,
		arg.Params,
		arg.TimeoutSecs,
		arg.MaxRetries,
		arg.NextRunAt,
		arg.CreatedBy,
	)
	var i CronJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ScheduleCron,
		&i.Timezone,
		&i.Enabled,
		&i.ActionKind,
		&i.ActionRef,
		&i.HttpMethod,
		&i.HttpUrl,
		&i.HttpHeaders,
		&i.HttpBody,
		&i.Params,
		&i.TimeoutSecs,
		&i.MaxRetries,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM cron_jobs WHERE id=$1
`

func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, name, description, schedule_cron, timezone, enabled, action_kind, action_ref, http_method, http_url, http_headers, http_body, params, timeout_secs, max_retries, next_run_at, last_run_at, created_by, created_at, updated_at FROM cron_jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (CronJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i CronJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ScheduleCron,
		&i.Timezone,
		&i.Enabled,
		&i.ActionKind,
		&i.ActionRef,
		&i.HttpMethod,
		&i.HttpUrl,
		&i.HttpHeaders,
		&i.HttpBody,
		&i.Params,
		&i.TimeoutSecs,
		&i.MaxRetries,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, name, description, schedule_cron, timezone, enabled, action_kind, action_ref, http_method, http_url, http_headers, http_body, params, timeout_secs, max_retries, next_run_at, last_run_at, created_by, created_at, updated_at FROM cron_jobs ORDER BY created_at DESC
`

func (q *Queries) ListJobs(ctx context.Context) ([]CronJob, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CronJob
	for rows.Next() {
		var i CronJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ScheduleCron,
			&i.Timezone,
			&i.Enabled,
			&i.ActionKind,
			&i.ActionRef,
			&i.HttpMethod,
			&i.HttpUrl,
			&i.HttpHeaders,
			&i.HttpBody,
			&i.Params,
			&i.TimeoutSecs,
			&i.MaxRetries,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setJobEnabled = `-- name: SetJobEnabled :exec
UPDATE cron_jobs SET enabled=$2, next_run_at=$3, updated_at=now() WHERE id=$1
`

type SetJobEnabledParams struct {
	ID        int64              `json:"id"`
	Enabled   bool               `json:"enabled"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) SetJobEnabled(ctx context.Context, arg SetJobEnabledParams) error {
	_, err := q.db.Exec(ctx, setJobEnabled, arg.ID, arg.Enabled, arg.NextRunAt)
	return err
}

const updateJob = `-- name: UpdateJob :one
UPDATE cron_jobs SET
    name=$2, description=$3, schedule_cron=$4, timezone=$5,
    action_kind=$6, action_ref=$7, http_method=$8, http_url=$9,
    http_headers=$10, http_body=$11, params=$12, timeout_secs=$13,
    max_retries=$14, next_run_at=$15, updated_at=now()
WHERE id=$1
RETURNING id, name, description, schedule_cron, timezone, enabled, action_kind, action_ref, http_method, http_url, http_headers, http_body, params, timeout_secs, max_retries, next_run_at, last_run_at, created_by, created_at, updated_at
`

type UpdateJobParams struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Description  string             `json:"description"`
	ScheduleCron string             `json:"schedule_cron"`
	Timezone     string             `json:"timezone"`
	ActionKind   string             `json:"action_kind"`
	ActionRef    string             `json:"action_ref"`
	HttpMethod   string             `json:"http_method"`
	HttpUrl      string             `json:"http_url"`
	HttpHeaders  []byte             `json:"http_headers"`
	HttpBody     string             `json:"http_body"`
	Params       []byte             `json:"params"`
	TimeoutSecs  int32              `json:"timeout_secs"`
	MaxRetries   int32              `json:"max_retries"`
	NextRunAt    pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (CronJob, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ScheduleCron,
		arg.Timezone,
		arg.ActionKind,
		arg.ActionRef,
		arg.HttpMethod,
		arg.HttpUrl,
		arg.HttpHeaders,
		arg.HttpBody,
		arg.Params,
		arg.TimeoutSecs,
		arg.MaxRetries,
		arg.NextRunAt,
	)
	var i CronJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ScheduleCron,
		&i.Timezone,
		&i.Enabled,
		&i.ActionKind,
		&i.ActionRef,
		&i.HttpMethod,
		&i.HttpUrl,
		&i.HttpHeaders,
		&i.HttpBody,
		&i.Params,
		&i.TimeoutSecs,
		&i.MaxRetries,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobAfterRun = `-- name: UpdateJobAfterRun :exec
UPDATE cron_jobs SET last_run_at=now(), next_run_at=$2, updated_at=now() WHERE id=$1
`

type UpdateJobAfterRunParams struct {
	ID        int64              `json:"id"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateJobAfterRun(ctx context.Context, arg UpdateJobAfterRunParams) error {
	_, err := q.db.Exec(ctx, updateJobAfterRun, arg.ID, arg.NextRunAt)
	return err
}
