// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CronJob struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Description  string             `json:"description"`
	ScheduleCron string             `json:"schedule_cron"`
	Timezone     string             `json:"timezone"`
	Enabled      bool               `json:"enabled"`
	ActionKind   string             `json:"action_kind"`
	ActionRef    string             `json:"action_ref"`
	HttpMethod   string             `json:"http_method"`
	HttpUrl      string             `json:"http_url"`
	HttpHeaders  []byte             `json:"http_headers"`
	HttpBody     string             `json:"http_body"`
	Params       []byte             `json:"params"`
	TimeoutSecs  int32              `json:"timeout_secs"`
	MaxRetries   int32              `json:"max_retries"`
	NextRunAt    pgtype.Timestamptz `json:"next_run_at"`
	LastRunAt    pgtype.Timestamptz `json:"last_run_at"`
	CreatedBy    string             `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type CronRun struct {
	ID              int64              `json:"id"`
	JobID           int64              `json:"job_id"`
	Status          string             `json:"status"`
	Attempt         int32              `json:"attempt"`
	HttpStatus      *int32             `json:"http_status"`
	ResponseExcerpt string             `json:"response_excerpt"`
	Error           string             `json:"error"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
}
