// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"
)

const createRun = `-- name: CreateRun :one
INSERT INTO cron_runs (job_id, status, attempt) VALUES ($1,$2,$3) RETURNING id, job_id, status, attempt, http_status, response_excerpt, error, started_at, finished_at
`

type CreateRunParams struct {
	JobID   int64  `json:"job_id"`
	Status  string `json:"status"`
	Attempt int32  `json:"attempt"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (CronRun, error) {
	row := q.db.QueryRow(ctx, createRun, arg.JobID, arg.Status, arg.Attempt)
	var i CronRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Status,
		&i.Attempt,
		&i.HttpStatus,
		&i.ResponseExcerpt,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishRun = `-- name: FinishRun :exec
UPDATE cron_runs SET status=$2, http_status=$3, response_excerpt=$4, error=$5,
    attempt=$6, finished_at=now()
WHERE id=$1
`

type FinishRunParams struct {
	ID              int64  `json:"id"`
	Status          string `json:"status"`
	HttpStatus      *int32 `json:"http_status"`
	ResponseExcerpt string `json:"response_excerpt"`
	Error           string `json:"error"`
	Attempt         int32  `json:"attempt"`
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.Exec(ctx, finishRun,
		arg.ID,
		arg.Status,
		arg.HttpStatus,
		arg.ResponseExcerpt,
		arg.Error,
		arg.Attempt,
	)
	return err
}

const hasRunningRun = `-- name: HasRunningRun :one
SELECT EXISTS(
    SELECT 1 FROM cron_runs WHERE job_id=$1 AND status='running'
) AS running
`

func (q *Queries) HasRunningRun(ctx context.Context, jobID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasRunningRun, jobID)
	var running bool
	err := row.Scan(&running)
	return running, err
}

const listRunsByJob = `-- name: ListRunsByJob :many
SELECT id, job_id, status, attempt, http_status, response_excerpt, error, started_at, finished_at FROM cron_runs WHERE job_id=$1 ORDER BY started_at DESC LIMIT $2
`

type ListRunsByJobParams struct {
	JobID int64 `json:"job_id"`
	Limit int32 `json:"limit"`
}

func (q *Queries) ListRunsByJob(ctx context.Context, arg ListRunsByJobParams) ([]CronRun, error) {
	rows, err := q.db.Query(ctx, listRunsByJob, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CronRun
	for rows.Next() {
		var i CronRun
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Status,
			&i.Attempt,
			&i.HttpStatus,
			&i.ResponseExcerpt,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
