// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cameras.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCamera = `-- name: CreateCamera :one
INSERT INTO cameras (
    name, ip, rtsp_user, rtsp_password_encrypted, quality_main, quality_sub, record_mode, motion_sensitivity, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, ip, rtsp_user, rtsp_password_encrypted, quality_main, quality_sub, record_mode, motion_sensitivity, is_active, created_at, updated_at
`

type CreateCameraParams struct {
	Name                  string `json:"name"`
	Ip                    string `json:"ip"`
	RtspUser              string `json:"rtsp_user"`
	RtspPasswordEncrypted string `json:"rtsp_password_encrypted"`
	QualityMain           string `json:"quality_main"`
	QualitySub            string `json:"quality_sub"`
	RecordMode            string `json:"record_mode"`
	MotionSensitivity     int32  `json:"motion_sensitivity"`
	IsActive              bool   `json:"is_active"`
}

func (q *Queries) CreateCamera(ctx context.Context, arg CreateCameraParams) (Camera, error) {
	row := q.db.QueryRow(ctx, createCamera,
		arg.Name,
		arg.Ip,
		arg.RtspUser,
		arg.RtspPasswordEncrypted,
		arg.QualityMain,
		arg.QualitySub,
		arg.RecordMode,
		arg.MotionSensitivity,
		arg.IsActive,
	)
	var i Camera
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.RtspUser,
		&i.RtspPasswordEncrypted,
		&i.QualityMain,
		&i.QualitySub,
		&i.RecordMode,
		&i.MotionSensitivity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCamera = `-- name: DeleteCamera :exec
DELETE FROM cameras WHERE id = $1
`

func (q *Queries) DeleteCamera(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCamera, id)
	return err
}

const getCamera = `-- name: GetCamera :one
SELECT id, name, ip, rtsp_user, rtsp_password_encrypted, quality_main, quality_sub, record_mode, motion_sensitivity, is_active, created_at, updated_at FROM cameras WHERE id = $1
`

func (q *Queries) GetCamera(ctx context.Context, id pgtype.UUID) (Camera, error) {
	row := q.db.QueryRow(ctx, getCamera, id)
	var i Camera
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.RtspUser,
		&i.RtspPasswordEncrypted,
		&i.QualityMain,
		&i.QualitySub,
		&i.RecordMode,
		&i.MotionSensitivity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCameras = `-- name: ListCameras :many
SELECT id, name, ip, rtsp_user, rtsp_password_encrypted, quality_main, quality_sub, record_mode, motion_sensitivity, is_active, created_at, updated_at FROM cameras ORDER BY name
`

func (q *Queries) ListCameras(ctx context.Context) ([]Camera, error) {
	rows, err := q.db.Query(ctx, listCameras)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Camera
	for rows.Next() {
		var i Camera
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ip,
			&i.RtspUser,
			&i.RtspPasswordEncrypted,
			&i.QualityMain,
			&i.QualitySub,
			&i.RecordMode,
			&i.MotionSensitivity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCamera = `-- name: UpdateCamera :one
UPDATE cameras SET
    name = $2,
    ip = $3,
    rtsp_user = $4,
    rtsp_password_encrypted = $5,
    quality_main = $6,
    quality_sub = $7,
    record_mode = $8,
    motion_sensitivity = $9,
    is_active = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, ip, rtsp_user, rtsp_password_encrypted, quality_main, quality_sub, record_mode, motion_sensitivity, is_active, created_at, updated_at
`

type UpdateCameraParams struct {
	ID                    pgtype.UUID `json:"id"`
	Name                  string      `json:"name"`
	Ip                    string      `json:"ip"`
	RtspUser              string      `json:"rtsp_user"`
	RtspPasswordEncrypted string      `json:"rtsp_password_encrypted"`
	QualityMain           string      `json:"quality_main"`
	QualitySub            string      `json:"quality_sub"`
	RecordMode            string      `json:"record_mode"`
	MotionSensitivity     int32       `json:"motion_sensitivity"`
	IsActive              bool        `json:"is_active"`
}

func (q *Queries) UpdateCamera(ctx context.Context, arg UpdateCameraParams) (Camera, error) {
	row := q.db.QueryRow(ctx, updateCamera,
		arg.ID,
		arg.Name,
		arg.Ip,
		arg.RtspUser,
		arg.RtspPasswordEncrypted,
		arg.QualityMain,
		arg.QualitySub,
		arg.RecordMode,
		arg.MotionSensitivity,
		arg.IsActive,
	)
	var i Camera
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ip,
		&i.RtspUser,
		&i.RtspPasswordEncrypted,
		&i.QualityMain,
		&i.QualitySub,
		&i.RecordMode,
		&i.MotionSensitivity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
