// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Camera struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	Ip                    string             `json:"ip"`
	RtspUser              string             `json:"rtsp_user"`
	RtspPasswordEncrypted string             `json:"rtsp_password_encrypted"`
	QualityMain           string             `json:"quality_main"`
	QualitySub            string             `json:"quality_sub"`
	RecordMode            string             `json:"record_mode"`
	MotionSensitivity     int32              `json:"motion_sensitivity"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Recording struct {
	ID          pgtype.UUID        `json:"id"`
	CameraID    pgtype.UUID        `json:"camera_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	SizeBytes   int64              `json:"size_bytes"`
	DriveFileID string             `json:"drive_file_id"`
	HasMotion   bool               `json:"has_motion"`
	KeepForever bool               `json:"keep_forever"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	ID                         int32              `json:"id"`
	StorageQuotaBytes          int64              `json:"storage_quota_bytes"`
	DriveRefreshTokenEncrypted string             `json:"drive_refresh_token_encrypted"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}
