// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recordings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecording = `-- name: CreateRecording :one
INSERT INTO recordings (
    camera_id, start_time, end_time, size_bytes, drive_file_id, has_motion, keep_forever
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, camera_id, start_time, end_time, size_bytes, drive_file_id, has_motion, keep_forever, created_at
`

type CreateRecordingParams struct {
	CameraID    pgtype.UUID        `json:"camera_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	SizeBytes   int64              `json:"size_bytes"`
	DriveFileID string             `json:"drive_file_id"`
	HasMotion   bool               `json:"has_motion"`
	KeepForever bool               `json:"keep_forever"`
}

func (q *Queries) CreateRecording(ctx context.Context, arg CreateRecordingParams) (Recording, error) {
	row := q.db.QueryRow(ctx, createRecording,
		arg.CameraID,
		arg.StartTime,
		arg.EndTime,
		arg.SizeBytes,
		arg.DriveFileID,
		arg.HasMotion,
		arg.KeepForever,
	)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.StartTime,
		&i.EndTime,
		&i.SizeBytes,
		&i.DriveFileID,
		&i.HasMotion,
		&i.KeepForever,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecording = `-- name: DeleteRecording :exec
DELETE FROM recordings WHERE id = $1
`

func (q *Queries) DeleteRecording(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecording, id)
	return err
}

const getRecording = `-- name: GetRecording :one
SELECT id, camera_id, start_time, end_time, size_bytes, drive_file_id, has_motion, keep_forever, created_at FROM recordings WHERE id = $1
`

func (q *Queries) GetRecording(ctx context.Context, id pgtype.UUID) (Recording, error) {
	row := q.db.QueryRow(ctx, getRecording, id)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.StartTime,
		&i.EndTime,
		&i.SizeBytes,
		&i.DriveFileID,
		&i.HasMotion,
		&i.KeepForever,
		&i.CreatedAt,
	)
	return i, err
}

const listOldestRecordings = `-- name: ListOldestRecordings :many
SELECT id, camera_id, start_time, end_time, size_bytes, drive_file_id, has_motion, keep_forever, created_at FROM recordings
WHERE keep_forever = false
ORDER BY start_time ASC
LIMIT $1
`

func (q *Queries) ListOldestRecordings(ctx context.Context, limit int32) ([]Recording, error) {
	rows, err := q.db.Query(ctx, listOldestRecordings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recording
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.StartTime,
			&i.EndTime,
			&i.SizeBytes,
			&i.DriveFileID,
			&i.HasMotion,
			&i.KeepForever,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordings = `-- name: ListRecordings :many
SELECT id, camera_id, start_time, end_time, size_bytes, drive_file_id, has_motion, keep_forever, created_at FROM recordings
WHERE camera_id = $1 AND start_time >= $2 AND start_time < $3
ORDER BY start_time ASC
`

type ListRecordingsParams struct {
	CameraID    pgtype.UUID        `json:"camera_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	StartTime_2 pgtype.Timestamptz `json:"start_time_2"`
}

func (q *Queries) ListRecordings(ctx context.Context, arg ListRecordingsParams) ([]Recording, error) {
	rows, err := q.db.Query(ctx, listRecordings, arg.CameraID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recording
	for rows.Next() {
		var i Recording
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.StartTime,
			&i.EndTime,
			&i.SizeBytes,
			&i.DriveFileID,
			&i.HasMotion,
			&i.KeepForever,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKeepForever = `-- name: UpdateKeepForever :exec
UPDATE recordings SET keep_forever = $2 WHERE id = $1
`

type UpdateKeepForeverParams struct {
	ID          pgtype.UUID `json:"id"`
	KeepForever bool        `json:"keep_forever"`
}

func (q *Queries) UpdateKeepForever(ctx context.Context, arg UpdateKeepForeverParams) error {
	_, err := q.db.Exec(ctx, updateKeepForever, arg.ID, arg.KeepForever)
	return err
}
