// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, storage_quota_bytes, drive_refresh_token_encrypted, updated_at FROM settings WHERE id = 1 LIMIT 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.StorageQuotaBytes,
		&i.DriveRefreshTokenEncrypted,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :one
INSERT INTO settings (
    id, storage_quota_bytes, drive_refresh_token_encrypted, updated_at
) VALUES (
    1, $1, $2, NOW()
)
ON CONFLICT (id) DO UPDATE SET
    storage_quota_bytes = EXCLUDED.storage_quota_bytes,
    drive_refresh_token_encrypted = EXCLUDED.drive_refresh_token_encrypted,
    updated_at = NOW()
RETURNING id, storage_quota_bytes, drive_refresh_token_encrypted, updated_at
`

type UpsertSettingsParams struct {
	StorageQuotaBytes          int64  `json:"storage_quota_bytes"`
	DriveRefreshTokenEncrypted string `json:"drive_refresh_token_encrypted"`
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, upsertSettings, arg.StorageQuotaBytes, arg.DriveRefreshTokenEncrypted)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.StorageQuotaBytes,
		&i.DriveRefreshTokenEncrypted,
		&i.UpdatedAt,
	)
	return i, err
}
